In [2]:
import pandas as pd
import pdb

from utils.experiment_utils import *
""
%load_ext autoreload
%autoreload 2

Read in all saved results and make Latex table

Metrics:
* marginal cov
* ACCG
* average set size


To get multiple row levels, set a multi-index. To get multiple column levels, concatenate dataframes along axis=1.

In [3]:
# Map from dataset to folder with saved results
# datasets = {'ImageNet': '.cache/paper/imagenet',
#             'CIFAR-100': '.cache/paper/cifar100',
#             'Places365': '.cache/paper/places365',
#             'iNaturalist': '.cache/paper/inaturalist'}
datasets = {'ImageNet': '.cache/paper/varying_n/imagenet',
            'CIFAR-100': '.cache/paper/varying_n/cifar-100',
            'Places365': '.cache/paper/varying_n/places365',
            'iNaturalist': '.cache/paper/varying_n/inaturalist'}

score_functions = {'softmax': '$\softmax$',
                  'APS': '$\APS$',
                  'RAPS': '$\RAPS$'}

methods = {'standard': '$\standard$', 
            'classwise': '$\classwise$',
#             'cluster_proportional': '$\clustered$',
            'cluster_random': '$\clustered$'} # TODO: update

calibration_sampling = 'random' # 'random' or 'balanced'

In [51]:
# # GENERATE TABLE - two n's and including marginal coverage
# n_totalcals = {10: '$n=10$', 50: '$n=50$'}

# horizontal_dict = {}
# for n_totalcal, n_name in n_totalcals.items():
#     vertical_list = []
#     for dataset, save_folder in datasets.items():
#         for score, score_name in score_functions.items():
#             for method, method_name in methods.items(): 

#                 folder = f'{save_folder}/{calibration_sampling}_calset/n_totalcal={n_totalcal}/score={score}/'
#                 print(folder)
#                 df = average_results_across_seeds(folder, print_results=False, methods=methods.keys()) # df = results DataFrame
#                 s = pd.Series({'Dataset': dataset, 'Score func.': score_name, 'Method': method_name, 
#                                'CovGap': f"{df[df['method'] == method]['class_cov_gap_mean'].values[0]:.1f}" 
#                                        f" ({df[df['method'] == method]['class_cov_gap_se'].values[0]:.1f})",
#                                'AvgSize': f"{df[df['method'] == method]['avg_set_size_mean'].values[0]:.1f}" 
#                                                f" ({df[df['method'] == method]['avg_set_size_se'].values[0]:.1f})",
#                                'MargCov': f"{df[df['method'] == method]['marginal_cov_mean'].values[0]*100:.1f}" 
#                                                    f" ({df[df['method'] == method]['marginal_cov_se'].values[0]*100:.1f})"})
#                 vertical_list.append(pd.DataFrame(s).transpose())                                        

#     df = pd.concat(vertical_list, ignore_index=True)                                                     
#     df = df.set_index(['Dataset', 'Score func.', 'Method'])
#     horizontal_dict[n_name] = df
# #     pdb.set_trace()

# df = pd.concat(horizontal_dict, axis=1)
# df_str = df.to_latex(multicolumn_format='c', # To center multilevel column headers
#     escape=False # So that backslashes are printed as `\' rather than '\textbackslash'
#                  )
# # Post-process
# df_str = df_str.replace('lllllllll', 'lllcrccrc')
# df_str = df_str.replace('\multicolumn{3}{c}{$n=10$} & \multicolumn{3}{c}{$n=50$} \\',
#                '\multicolumn{3}{c}{$n=10$} & \multicolumn{3}{c}{$n=50$} \\\\ \cmidrule(lr){4-6}\cmidrule(lr){7-9} \\')
# df_str = df_str.replace('CIFAR-100', '\midrule\nCIFAR-100')
# df_str = df_str.replace('Places365', '\midrule\nPlaces365')
# df_str = df_str.replace('iNaturalist', '\midrule\niNaturalist')
# print(df_str)

In [60]:
# GENERATE TABLE - three n's and excluding marginal coverage
n_totalcals = {10: '$n_{\text{avg}}=10$', 20: '$n_{\text{avg}}=20$', 
               50: '$n_{\text{avg}}=50$', 75: '$n_{\text{avg}}=75$'}

horizontal_dict = {}
for n_totalcal, n_name in n_totalcals.items():
    vertical_list = []
    for dataset, save_folder in datasets.items():
        for score, score_name in score_functions.items():
            for method, method_name in methods.items(): 

                folder = f'{save_folder}/{calibration_sampling}_calset/n_totalcal={n_totalcal}/score={score}/'
                print(folder)
                df = average_results_across_seeds(folder, print_results=False, methods=methods.keys()) # df = results DataFrame
                s = pd.Series({'Dataset': dataset, 'Score func.': score_name, 'Method': method_name, 
                               'CovGap': f"{df[df['method'] == method]['class_cov_gap_mean'].values[0]:.1f}" 
                                       f" ({df[df['method'] == method]['class_cov_gap_se'].values[0]:.1f})",
                               'AvgSize': f"{df[df['method'] == method]['avg_set_size_mean'].values[0]:.1f}" 
                                               f" ({df[df['method'] == method]['avg_set_size_se'].values[0]:.1f})"})
#                                'MargCov': f"{df[df['method'] == method]['marginal_cov_mean'].values[0]*100:.1f}" 
#                                                    f" ({df[df['method'] == method]['marginal_cov_se'].values[0]*100:.1f})"})
                vertical_list.append(pd.DataFrame(s).transpose())                                        

    df = pd.concat(vertical_list, ignore_index=True)                                                     
    df = df.set_index(['Dataset', 'Score func.', 'Method'])
    horizontal_dict[n_name] = df
#     pdb.set_trace()

df = pd.concat(horizontal_dict, axis=1)
df_str = df.to_latex(multicolumn_format='c', # To center multilevel column headers
    escape=False # So that backslashes are printed as `\' rather than '\textbackslash'
                 )
# Post-process
df_str = df_str.replace('lllllllllll', 'lllcrcrcrcr')
df_str = df_str.replace('\\multicolumn{2}{c}{$n_{\\text{avg}}=75$} \\\\',
               '\\multicolumn{2}{c}{$n_{\\text{avg}}=75$} \\\\ \cmidrule(lr){4-5}\cmidrule(lr){6-7} \cmidrule(lr){8-9} \cmidrule(lr){10-11}\\')
df_str = df_str.replace('CIFAR-100', '\midrule\nCIFAR-100')
df_str = df_str.replace('Places365', '\midrule\nPlaces365')
df_str = df_str.replace('iNaturalist', '\midrule\niNaturalist')
# Add horizontal lines between methods
df_str = df_str.replace('& $\APS$', '\cline{3-11} & $\APS$')
df_str = df_str.replace('& $\RAPS$', '\cline{3-11} & $\RAPS$')
print(df_str)

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.223009,0.026946,38.294309,0.320930,1.940409,0.017132,0.900390,0.000849,0.0784,0.003021
1,classwise,7.665144,0.045728,38.259073,1.171264,354.400610,2.023354,0.946082,0.000518,0.0547,0.001744
2,cluster_random,4.871419,0.087259,34.997894,1.532120,2.500469,0.121130,0.903487,0.002734,0.0682,0.008114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.223009,0.026946,38.294309,0.320930,1.940409,0.017132,0.900390,0.000849,0.0784,0.003021
1,classwise,7.665144,0.045728,38.259073,1.171264,354.400610,2.023354,0.946082,0.000518,0.0547,0.001744
2,cluster_random,4.871419,0.087259,34.997894,1.532120,2.500469,0.121130,0.903487,0.002734,0.0682,0.008114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.223009,0.026946,38.294309,0.320930,1.940409,0.017132,0.900390,0.000849,0.0784,0.003021
1,classwise,7.665144,0.045728,38.259073,1.171264,354.400610,2.023354,0.946082,0.000518,0.0547,0.001744
2,cluster_random,4.871419,0.087259,34.997894,1.532120,2.500469,0.121130,0.903487,0.002734,0.0682,0.008114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.560593,0.015334,21.132209,0.125715,25.928972,0.334066,0.900216,0.000964,0.0213,0.000401
1,classwise,7.634051,0.023135,37.179353,1.942818,394.186939,1.909254,0.946557,0.000868,0.0548,0.002440
2,cluster_random,2.962995,0.086207,20.778567,0.707501,29.590335,1.459991,0.904302,0.003109,0.0202,0.002116

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.560593,0.015334,21.132209,0.125715,25.928972,0.334066,0.900216,0.000964,0.0213,0.000401
1,classwise,7.634051,0.023135,37.179353,1.942818,394.186939,1.909254,0.946557,0.000868,0.0548,0.002440
2,cluster_random,2.962995,0.086207,20.778567,0.707501,29.590335,1.459991,0.904302,0.003109,0.0202,0.002116

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.560593,0.015334,21.132209,0.125715,25.928972,0.334066,0.900216,0.000964,0.0213,0.000401
1,classwise,7.634051,0.023135,37.179353,1.942818,394.186939,1.909254,0.946557,0.000868,0.0548,0.002440
2,cluster_random,2.962995,0.086207,20.778567,0.707501,29.590335,1.459991,0.904302,0.003109,0.0202,0.002116

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.022090,0.007071,25.111260,0.112823,5.161310,0.018058,0.900999,0.000676,0.0284,0.000429
1,classwise,7.681054,0.051617,38.346412,1.754499,361.878919,1.906141,0.945921,0.000715,0.0564,0.002250
2,cluster_random,3.094981,0.041255,22.642816,0.724716,7.724640,0.984096,0.903250,0.001972,0.0219,0.001100

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.022090,0.007071,25.111260,0.112823,5.161310,0.018058,0.900999,0.000676,0.0284,0.000429
1,classwise,7.681054,0.051617,38.346412,1.754499,361.878919,1.906141,0.945921,0.000715,0.0564,0.002250
2,cluster_random,3.094981,0.041255,22.642816,0.724716,7.724640,0.984096,0.903250,0.001972,0.0219,0.001100

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.022090,0.007071,25.111260,0.112823,5.161310,0.018058,0.900999,0.000676,0.0284,0.000429
1,classwise,7.681054,0.051617,38.346412,1.754499,361.878919,1.906141,0.945921,0.000715,0.0564,0.002250
2,cluster_random,3.094981,0.041255,22.642816,0.724716,7.724640,0.984096,0.903250,0.001972,0.0219,0.001100

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.991794,0.062632,12.098017,0.661933,8.069700,0.242667,0.900717,0.002582,0.041,0.009945
1,classwise,7.559482,0.131528,20.308118,1.912127,47.159469,0.566291,0.945045,0.001994,0.054,0.008025
2,cluster_random,4.190073,0.053389,15.083733,1.612104,8.891490,0.462414,0.899069,0.003287,0.057,0.010203

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.991794,0.062632,12.098017,0.661933,8.069700,0.242667,0.900717,0.002582,0.041,0.009945
1,classwise,7.559482,0.131528,20.308118,1.912127,47.159469,0.566291,0.945045,0.001994,0.054,0.008025
2,cluster_random,4.190073,0.053389,15.083733,1.612104,8.891490,0.462414,0.899069,0.003287,0.057,0.010203

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.991794,0.062632,12.098017,0.661933,8.069700,0.242667,0.900717,0.002582,0.041,0.009945
1,classwise,7.559482,0.131528,20.308118,1.912127,47.159469,0.566291,0.945045,0.001994,0.054,0.008025
2,cluster_random,4.190073,0.053389,15.083733,1.612104,8.891490,0.462414,0.899069,0.003287,0.057,0.010203

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.748099,0.050672,13.894415,0.603704,11.225545,0.326769,0.900997,0.002389,0.033,0.004909
1,classwise,7.495067,0.133726,21.949424,1.969486,49.383997,0.521603,0.946772,0.001657,0.051,0.006237
2,cluster_random,4.002394,0.066151,15.327333,0.935655,11.914952,0.487925,0.898421,0.002857,0.040,0.005292

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.748099,0.050672,13.894415,0.603704,11.225545,0.326769,0.900997,0.002389,0.033,0.004909
1,classwise,7.495067,0.133726,21.949424,1.969486,49.383997,0.521603,0.946772,0.001657,0.051,0.006237
2,cluster_random,4.002394,0.066151,15.327333,0.935655,11.914952,0.487925,0.898421,0.002857,0.040,0.005292

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.748099,0.050672,13.894415,0.603704,11.225545,0.326769,0.900997,0.002389,0.033,0.004909
1,classwise,7.495067,0.133726,21.949424,1.969486,49.383997,0.521603,0.946772,0.001657,0.051,0.006237
2,cluster_random,4.002394,0.066151,15.327333,0.935655,11.914952,0.487925,0.898421,0.002857,0.040,0.005292

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.740738,0.070109,14.064919,0.591192,8.597710,0.262783,0.903528,0.002335,0.062,0.010564
1,classwise,7.519487,0.109775,22.177778,1.879422,47.516069,0.693719,0.946024,0.001874,0.046,0.007376
2,cluster_random,4.898189,0.086024,15.371095,1.342234,9.511562,0.503472,0.903566,0.003484,0.069,0.013524

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.740738,0.070109,14.064919,0.591192,8.597710,0.262783,0.903528,0.002335,0.062,0.010564
1,classwise,7.519487,0.109775,22.177778,1.879422,47.516069,0.693719,0.946024,0.001874,0.046,0.007376
2,cluster_random,4.898189,0.086024,15.371095,1.342234,9.511562,0.503472,0.903566,0.003484,0.069,0.013524

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.740738,0.070109,14.064919,0.591192,8.597710,0.262783,0.903528,0.002335,0.062,0.010564
1,classwise,7.519487,0.109775,22.177778,1.879422,47.516069,0.693719,0.946024,0.001874,0.046,0.007376
2,cluster_random,4.898189,0.086024,15.371095,1.342234,9.511562,0.503472,0.903566,0.003484,0.069,0.013524

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.539968,0.040831,21.593402,0.293917,6.937257,0.077179,0.900641,0.001260,0.066575,0.004083
1,classwise,7.617882,0.054526,34.904122,2.151995,136.462855,1.651122,0.944868,0.001324,0.054247,0.003483
2,cluster_random,4.493055,0.052020,22.878184,0.802514,7.118502,0.129118,0.900720,0.001632,0.064110,0.004827

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.539968,0.040831,21.593402,0.293917,6.937257,0.077179,0.900641,0.001260,0.066575,0.004083
1,classwise,7.617882,0.054526,34.904122,2.151995,136.462855,1.651122,0.944868,0.001324,0.054247,0.003483
2,cluster_random,4.493055,0.052020,22.878184,0.802514,7.118502,0.129118,0.900720,0.001632,0.064110,0.004827

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.539968,0.040831,21.593402,0.293917,6.937257,0.077179,0.900641,0.001260,0.066575,0.004083
1,classwise,7.617882,0.054526,34.904122,2.151995,136.462855,1.651122,0.944868,0.001324,0.054247,0.003483
2,cluster_random,4.493055,0.052020,22.878184,0.802514,7.118502,0.129118,0.900720,0.001632,0.064110,0.004827

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.274661,0.017758,17.908601,0.213722,10.829566,0.112739,0.900707,0.001238,0.028219,0.002686
1,classwise,7.602339,0.079425,32.084500,1.477303,140.498516,1.652093,0.945362,0.001364,0.052877,0.003914
2,cluster_random,3.489825,0.061225,19.807614,1.096423,10.917162,0.268882,0.897820,0.002863,0.036164,0.004789

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.274661,0.017758,17.908601,0.213722,10.829566,0.112739,0.900707,0.001238,0.028219,0.002686
1,classwise,7.602339,0.079425,32.084500,1.477303,140.498516,1.652093,0.945362,0.001364,0.052877,0.003914
2,cluster_random,3.489825,0.061225,19.807614,1.096423,10.917162,0.268882,0.897820,0.002863,0.036164,0.004789

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.274661,0.017758,17.908601,0.213722,10.829566,0.112739,0.900707,0.001238,0.028219,0.002686
1,classwise,7.602339,0.079425,32.084500,1.477303,140.498516,1.652093,0.945362,0.001364,0.052877,0.003914
2,cluster_random,3.489825,0.061225,19.807614,1.096423,10.917162,0.268882,0.897820,0.002863,0.036164,0.004789

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.834070,0.004756,20.223127,0.224620,7.896427,0.043998,0.899286,0.000923,0.043288,0.002318
1,classwise,7.571418,0.056852,32.124852,1.461276,138.860085,1.673153,0.944816,0.001440,0.051507,0.004867
2,cluster_random,3.934281,0.059633,21.375731,1.005539,8.008258,0.118351,0.897750,0.002241,0.043836,0.005270

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.834070,0.004756,20.223127,0.224620,7.896427,0.043998,0.899286,0.000923,0.043288,0.002318
1,classwise,7.571418,0.056852,32.124852,1.461276,138.860085,1.673153,0.944816,0.001440,0.051507,0.004867
2,cluster_random,3.934281,0.059633,21.375731,1.005539,8.008258,0.118351,0.897750,0.002241,0.043836,0.005270

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.834070,0.004756,20.223127,0.224620,7.896427,0.043998,0.899286,0.000923,0.043288,0.002318
1,classwise,7.571418,0.056852,32.124852,1.461276,138.860085,1.673153,0.944816,0.001440,0.051507,0.004867
2,cluster_random,3.934281,0.059633,21.375731,1.005539,8.008258,0.118351,0.897750,0.002241,0.043836,0.005270

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.015272,0.087431,46.844151,0.670852,3.146679,0.038869,0.899139,0.001214,0.200790,0.005058
1,classwise,8.731317,0.023367,23.349363,2.361713,469.440028,1.800960,0.931566,0.000758,0.013586,0.001911
2,cluster_random,6.871503,0.162904,47.027582,1.299771,3.104652,0.068734,0.886143,0.002198,0.194155,0.006752

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.015272,0.087431,46.844151,0.670852,3.146679,0.038869,0.899139,0.001214,0.200790,0.005058
1,classwise,8.731317,0.023367,23.349363,2.361713,469.440028,1.800960,0.931566,0.000758,0.013586,0.001911
2,cluster_random,6.871503,0.162904,47.027582,1.299771,3.104652,0.068734,0.886143,0.002198,0.194155,0.006752

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.015272,0.087431,46.844151,0.670852,3.146679,0.038869,0.899139,0.001214,0.200790,0.005058
1,classwise,8.731317,0.023367,23.349363,2.361713,469.440028,1.800960,0.931566,0.000758,0.013586,0.001911
2,cluster_random,6.871503,0.162904,47.027582,1.299771,3.104652,0.068734,0.886143,0.002198,0.194155,0.006752

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.253885,0.075680,61.250285,0.416401,8.283288,0.105972,0.898767,0.001662,0.100158,0.004258
1,classwise,8.686154,0.020417,25.951450,1.838893,472.763706,1.767429,0.933501,0.001148,0.012954,0.000969
2,cluster_random,4.270996,0.078391,60.280680,0.653222,8.103065,0.098680,0.892965,0.001557,0.095577,0.004235

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.253885,0.075680,61.250285,0.416401,8.283288,0.105972,0.898767,0.001662,0.100158,0.004258
1,classwise,8.686154,0.020417,25.951450,1.838893,472.763706,1.767429,0.933501,0.001148,0.012954,0.000969
2,cluster_random,4.270996,0.078391,60.280680,0.653222,8.103065,0.098680,0.892965,0.001557,0.095577,0.004235

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.253885,0.075680,61.250285,0.416401,8.283288,0.105972,0.898767,0.001662,0.100158,0.004258
1,classwise,8.686154,0.020417,25.951450,1.838893,472.763706,1.767429,0.933501,0.001148,0.012954,0.000969
2,cluster_random,4.270996,0.078391,60.280680,0.653222,8.103065,0.098680,0.892965,0.001557,0.095577,0.004235

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.066155,0.079256,58.974116,0.632407,5.130720,0.043069,0.898280,0.001743,0.135387,0.005311
1,classwise,8.717976,0.010423,25.302377,2.156119,473.752873,1.898523,0.933670,0.000902,0.012954,0.000859
2,cluster_random,5.039199,0.088583,56.109144,0.926221,5.007765,0.034509,0.889918,0.001372,0.128910,0.005568

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.066155,0.079256,58.974116,0.632407,5.130720,0.043069,0.898280,0.001743,0.135387,0.005311
1,classwise,8.717976,0.010423,25.302377,2.156119,473.752873,1.898523,0.933670,0.000902,0.012954,0.000859
2,cluster_random,5.039199,0.088583,56.109144,0.926221,5.007765,0.034509,0.889918,0.001372,0.128910,0.005568

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.066155,0.079256,58.974116,0.632407,5.130720,0.043069,0.898280,0.001743,0.135387,0.005311
1,classwise,8.717976,0.010423,25.302377,2.156119,473.752873,1.898523,0.933670,0.000902,0.012954,0.000859
2,cluster_random,5.039199,0.088583,56.109144,0.926221,5.007765,0.034509,0.889918,0.001372,0.128910,0.005568

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242140,0.019744,38.588681,0.253128,1.925405,0.012752,0.899721,0.000633,0.0809,0.002418
1,classwise,5.351844,0.035587,28.072956,1.528633,22.995326,0.866654,0.923408,0.000471,0.0456,0.002290
2,cluster_random,3.910072,0.047958,26.188130,2.078601,2.691425,0.101411,0.902816,0.002088,0.0418,0.005132

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242140,0.019744,38.588681,0.253128,1.925405,0.012752,0.899721,0.000633,0.0809,0.002418
1,classwise,5.351844,0.035587,28.072956,1.528633,22.995326,0.866654,0.923408,0.000471,0.0456,0.002290
2,cluster_random,3.910072,0.047958,26.188130,2.078601,2.691425,0.101411,0.902816,0.002088,0.0418,0.005132

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242140,0.019744,38.588681,0.253128,1.925405,0.012752,0.899721,0.000633,0.0809,0.002418
1,classwise,5.351844,0.035587,28.072956,1.528633,22.995326,0.866654,0.923408,0.000471,0.0456,0.002290
2,cluster_random,3.910072,0.047958,26.188130,2.078601,2.691425,0.101411,0.902816,0.002088,0.0418,0.005132

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.579062,0.006664,21.130067,0.099829,25.836745,0.147786,0.899823,0.000456,0.0217,0.000145
1,classwise,5.454779,0.038000,30.687932,1.363243,76.892528,0.843063,0.922921,0.000485,0.0455,0.001423
2,cluster_random,2.618204,0.028570,18.718945,1.092662,26.988619,0.709796,0.899518,0.001936,0.0163,0.001908

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.579062,0.006664,21.130067,0.099829,25.836745,0.147786,0.899823,0.000456,0.0217,0.000145
1,classwise,5.454779,0.038000,30.687932,1.363243,76.892528,0.843063,0.922921,0.000485,0.0455,0.001423
2,cluster_random,2.618204,0.028570,18.718945,1.092662,26.988619,0.709796,0.899518,0.001936,0.0163,0.001908

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.579062,0.006664,21.130067,0.099829,25.836745,0.147786,0.899823,0.000456,0.0217,0.000145
1,classwise,5.454779,0.038000,30.687932,1.363243,76.892528,0.843063,0.922921,0.000485,0.0455,0.001423
2,cluster_random,2.618204,0.028570,18.718945,1.092662,26.988619,0.709796,0.899518,0.001936,0.0163,0.001908

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.002839,0.005155,24.895577,0.107940,5.120346,0.014104,0.899332,0.000551,0.0289,0.000411
1,classwise,5.568841,0.048260,30.413912,1.646779,34.228667,0.981603,0.925940,0.000640,0.0442,0.002068
2,cluster_random,2.914079,0.034705,20.420417,1.121158,6.647010,0.594168,0.900730,0.001944,0.0188,0.001821

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.002839,0.005155,24.895577,0.107940,5.120346,0.014104,0.899332,0.000551,0.0289,0.000411
1,classwise,5.568841,0.048260,30.413912,1.646779,34.228667,0.981603,0.925940,0.000640,0.0442,0.002068
2,cluster_random,2.914079,0.034705,20.420417,1.121158,6.647010,0.594168,0.900730,0.001944,0.0188,0.001821

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.002839,0.005155,24.895577,0.107940,5.120346,0.014104,0.899332,0.000551,0.0289,0.000411
1,classwise,5.568841,0.048260,30.413912,1.646779,34.228667,0.981603,0.925940,0.000640,0.0442,0.002068
2,cluster_random,2.914079,0.034705,20.420417,1.121158,6.647010,0.594168,0.900730,0.001944,0.0188,0.001821

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.034722,0.043785,12.983755,0.568526,7.855539,0.171175,0.898679,0.001844,0.046,0.008149
1,classwise,5.596848,0.082472,18.950410,1.208061,19.301886,0.489866,0.922043,0.001315,0.051,0.006701
2,cluster_random,3.632336,0.102766,12.697992,0.820957,8.895064,0.347512,0.903107,0.002977,0.023,0.007490

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.034722,0.043785,12.983755,0.568526,7.855539,0.171175,0.898679,0.001844,0.046,0.008149
1,classwise,5.596848,0.082472,18.950410,1.208061,19.301886,0.489866,0.922043,0.001315,0.051,0.006701
2,cluster_random,3.632336,0.102766,12.697992,0.820957,8.895064,0.347512,0.903107,0.002977,0.023,0.007490

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.034722,0.043785,12.983755,0.568526,7.855539,0.171175,0.898679,0.001844,0.046,0.008149
1,classwise,5.596848,0.082472,18.950410,1.208061,19.301886,0.489866,0.922043,0.001315,0.051,0.006701
2,cluster_random,3.632336,0.102766,12.697992,0.820957,8.895064,0.347512,0.903107,0.002977,0.023,0.007490

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.733895,0.045679,13.744097,0.354649,10.834100,0.153694,0.898196,0.001283,0.039,0.002983
1,classwise,5.606724,0.073194,20.365403,1.353927,22.646911,0.465817,0.922304,0.001308,0.055,0.003536
2,cluster_random,3.609810,0.090039,13.351927,1.042160,12.104261,0.456551,0.904429,0.003152,0.028,0.008809

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.733895,0.045679,13.744097,0.354649,10.834100,0.153694,0.898196,0.001283,0.039,0.002983
1,classwise,5.606724,0.073194,20.365403,1.353927,22.646911,0.465817,0.922304,0.001308,0.055,0.003536
2,cluster_random,3.609810,0.090039,13.351927,1.042160,12.104261,0.456551,0.904429,0.003152,0.028,0.008809

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.733895,0.045679,13.744097,0.354649,10.834100,0.153694,0.898196,0.001283,0.039,0.002983
1,classwise,5.606724,0.073194,20.365403,1.353927,22.646911,0.465817,0.922304,0.001308,0.055,0.003536
2,cluster_random,3.609810,0.090039,13.351927,1.042160,12.104261,0.456551,0.904429,0.003152,0.028,0.008809

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.802331,0.067221,14.824411,0.595375,8.334961,0.264027,0.901332,0.002234,0.076,0.010696
1,classwise,5.580447,0.110211,18.282706,1.479314,20.727804,0.648587,0.927489,0.001569,0.045,0.004743
2,cluster_random,4.546226,0.096520,17.570428,1.259491,8.672836,0.484433,0.899600,0.003694,0.066,0.014980

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.802331,0.067221,14.824411,0.595375,8.334961,0.264027,0.901332,0.002234,0.076,0.010696
1,classwise,5.580447,0.110211,18.282706,1.479314,20.727804,0.648587,0.927489,0.001569,0.045,0.004743
2,cluster_random,4.546226,0.096520,17.570428,1.259491,8.672836,0.484433,0.899600,0.003694,0.066,0.014980

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.802331,0.067221,14.824411,0.595375,8.334961,0.264027,0.901332,0.002234,0.076,0.010696
1,classwise,5.580447,0.110211,18.282706,1.479314,20.727804,0.648587,0.927489,0.001569,0.045,0.004743
2,cluster_random,4.546226,0.096520,17.570428,1.259491,8.672836,0.484433,0.899600,0.003694,0.066,0.014980

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.541674,0.025486,21.633060,0.263461,6.923882,0.048799,0.900492,0.000798,0.066849,0.002634
1,classwise,5.425627,0.032237,26.258985,1.358941,18.015213,0.233711,0.923452,0.000823,0.043014,0.002358
2,cluster_random,3.909844,0.081523,20.986968,1.359089,7.114558,0.145647,0.894724,0.002426,0.046575,0.005169

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.541674,0.025486,21.633060,0.263461,6.923882,0.048799,0.900492,0.000798,0.066849,0.002634
1,classwise,5.425627,0.032237,26.258985,1.358941,18.015213,0.233711,0.923452,0.000823,0.043014,0.002358
2,cluster_random,3.909844,0.081523,20.986968,1.359089,7.114558,0.145647,0.894724,0.002426,0.046575,0.005169

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.541674,0.025486,21.633060,0.263461,6.923882,0.048799,0.900492,0.000798,0.066849,0.002634
1,classwise,5.425627,0.032237,26.258985,1.358941,18.015213,0.233711,0.923452,0.000823,0.043014,0.002358
2,cluster_random,3.909844,0.081523,20.986968,1.359089,7.114558,0.145647,0.894724,0.002426,0.046575,0.005169

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.285192,0.014402,17.793849,0.166431,10.859993,0.102585,0.900801,0.001148,0.028493,0.002299
1,classwise,5.405772,0.072604,26.047756,1.515578,23.499041,0.271947,0.923760,0.000730,0.042192,0.002956
2,cluster_random,3.052464,0.037030,15.417303,0.484194,10.920591,0.243955,0.897251,0.002035,0.016986,0.002253

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.285192,0.014402,17.793849,0.166431,10.859993,0.102585,0.900801,0.001148,0.028493,0.002299
1,classwise,5.405772,0.072604,26.047756,1.515578,23.499041,0.271947,0.923760,0.000730,0.042192,0.002956
2,cluster_random,3.052464,0.037030,15.417303,0.484194,10.920591,0.243955,0.897251,0.002035,0.016986,0.002253

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.285192,0.014402,17.793849,0.166431,10.859993,0.102585,0.900801,0.001148,0.028493,0.002299
1,classwise,5.405772,0.072604,26.047756,1.515578,23.499041,0.271947,0.923760,0.000730,0.042192,0.002956
2,cluster_random,3.052464,0.037030,15.417303,0.484194,10.920591,0.243955,0.897251,0.002035,0.016986,0.002253

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.863657,0.002829,19.813327,0.139193,7.943046,0.042746,0.900394,0.000908,0.039452,0.001698
1,classwise,5.469234,0.058504,25.949552,1.443175,21.320141,0.326023,0.925214,0.000631,0.041096,0.003148
2,cluster_random,3.412354,0.038309,16.823011,1.159658,8.151959,0.174662,0.896920,0.002029,0.029315,0.003656

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.863657,0.002829,19.813327,0.139193,7.943046,0.042746,0.900394,0.000908,0.039452,0.001698
1,classwise,5.469234,0.058504,25.949552,1.443175,21.320141,0.326023,0.925214,0.000631,0.041096,0.003148
2,cluster_random,3.412354,0.038309,16.823011,1.159658,8.151959,0.174662,0.896920,0.002029,0.029315,0.003656

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.863657,0.002829,19.813327,0.139193,7.943046,0.042746,0.900394,0.000908,0.039452,0.001698
1,classwise,5.469234,0.058504,25.949552,1.443175,21.320141,0.326023,0.925214,0.000631,0.041096,0.003148
2,cluster_random,3.412354,0.038309,16.823011,1.159658,8.151959,0.174662,0.896920,0.002029,0.029315,0.003656

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.013092,0.054916,46.855327,0.592711,3.144770,0.024174,0.899156,0.000752,0.201896,0.003394
1,classwise,7.818879,0.021523,31.758727,2.106494,363.999650,1.449765,0.920161,0.000550,0.021011,0.002386
2,cluster_random,6.412864,0.115882,46.462627,0.964505,3.442862,0.071570,0.892755,0.001658,0.177725,0.004564

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.013092,0.054916,46.855327,0.592711,3.144770,0.024174,0.899156,0.000752,0.201896,0.003394
1,classwise,7.818879,0.021523,31.758727,2.106494,363.999650,1.449765,0.920161,0.000550,0.021011,0.002386
2,cluster_random,6.412864,0.115882,46.462627,0.964505,3.442862,0.071570,0.892755,0.001658,0.177725,0.004564

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.013092,0.054916,46.855327,0.592711,3.144770,0.024174,0.899156,0.000752,0.201896,0.003394
1,classwise,7.818879,0.021523,31.758727,2.106494,363.999650,1.449765,0.920161,0.000550,0.021011,0.002386
2,cluster_random,6.412864,0.115882,46.462627,0.964505,3.442862,0.071570,0.892755,0.001658,0.177725,0.004564

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.159961,0.053653,57.543882,0.433449,8.375728,0.070039,0.899902,0.001102,0.096524,0.002250
1,classwise,7.759054,0.021196,25.424009,2.046067,368.391984,1.402305,0.921396,0.000699,0.018799,0.001506
2,cluster_random,4.143421,0.079174,60.550941,0.451936,8.332210,0.112080,0.896453,0.002097,0.090047,0.003725

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.159961,0.053653,57.543882,0.433449,8.375728,0.070039,0.899902,0.001102,0.096524,0.002250
1,classwise,7.759054,0.021196,25.424009,2.046067,368.391984,1.402305,0.921396,0.000699,0.018799,0.001506
2,cluster_random,4.143421,0.079174,60.550941,0.451936,8.332210,0.112080,0.896453,0.002097,0.090047,0.003725

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.159961,0.053653,57.543882,0.433449,8.375728,0.070039,0.899902,0.001102,0.096524,0.002250
1,classwise,7.759054,0.021196,25.424009,2.046067,368.391984,1.402305,0.921396,0.000699,0.018799,0.001506
2,cluster_random,4.143421,0.079174,60.550941,0.451936,8.332210,0.112080,0.896453,0.002097,0.090047,0.003725

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.990115,0.049682,55.653438,0.449000,5.150563,0.029484,0.898890,0.001184,0.130490,0.002974
1,classwise,7.799607,0.019823,25.998071,1.967420,369.186434,1.456199,0.921288,0.000787,0.020537,0.001642
2,cluster_random,4.892857,0.081258,57.616667,0.939359,5.168215,0.047643,0.895563,0.002374,0.125750,0.005140

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.990115,0.049682,55.653438,0.449000,5.150563,0.029484,0.898890,0.001184,0.130490,0.002974
1,classwise,7.799607,0.019823,25.998071,1.967420,369.186434,1.456199,0.921288,0.000787,0.020537,0.001642
2,cluster_random,4.892857,0.081258,57.616667,0.939359,5.168215,0.047643,0.895563,0.002374,0.125750,0.005140

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.990115,0.049682,55.653438,0.449000,5.150563,0.029484,0.898890,0.001184,0.130490,0.002974
1,classwise,7.799607,0.019823,25.998071,1.967420,369.186434,1.456199,0.921288,0.000787,0.020537,0.001642
2,cluster_random,4.892857,0.081258,57.616667,0.939359,5.168215,0.047643,0.895563,0.002374,0.125750,0.005140

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.255063,0.016347,38.674388,0.190910,1.916796,0.009820,0.899290,0.000494,0.0824,0.001877
1,classwise,3.440016,0.022349,17.048546,0.766009,5.075701,0.078923,0.909475,0.000273,0.0123,0.001297
2,cluster_random,3.107672,0.028055,18.334423,0.794606,2.590801,0.057287,0.899607,0.000705,0.0178,0.001777

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.255063,0.016347,38.674388,0.190910,1.916796,0.009820,0.899290,0.000494,0.0824,0.001877
1,classwise,3.440016,0.022349,17.048546,0.766009,5.075701,0.078923,0.909475,0.000273,0.0123,0.001297
2,cluster_random,3.107672,0.028055,18.334423,0.794606,2.590801,0.057287,0.899607,0.000705,0.0178,0.001777

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.255063,0.016347,38.674388,0.190910,1.916796,0.009820,0.899290,0.000494,0.0824,0.001877
1,classwise,3.440016,0.022349,17.048546,0.766009,5.075701,0.078923,0.909475,0.000273,0.0123,0.001297
2,cluster_random,3.107672,0.028055,18.334423,0.794606,2.590801,0.057287,0.899607,0.000705,0.0178,0.001777

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.544407,0.003633,21.277486,0.067242,25.622265,0.111304,0.899361,0.000346,0.0215,0.000292
1,classwise,3.493231,0.018846,16.905574,1.215922,39.705516,0.233704,0.910155,0.000351,0.0137,0.000917
2,cluster_random,2.258431,0.042054,13.594943,0.753901,27.183637,0.534300,0.900078,0.001213,0.0050,0.001114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.544407,0.003633,21.277486,0.067242,25.622265,0.111304,0.899361,0.000346,0.0215,0.000292
1,classwise,3.493231,0.018846,16.905574,1.215922,39.705516,0.233704,0.910155,0.000351,0.0137,0.000917
2,cluster_random,2.258431,0.042054,13.594943,0.753901,27.183637,0.534300,0.900078,0.001213,0.0050,0.001114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.544407,0.003633,21.277486,0.067242,25.622265,0.111304,0.899361,0.000346,0.0215,0.000292
1,classwise,3.493231,0.018846,16.905574,1.215922,39.705516,0.233704,0.910155,0.000351,0.0137,0.000917
2,cluster_random,2.258431,0.042054,13.594943,0.753901,27.183637,0.534300,0.900078,0.001213,0.0050,0.001114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.012505,0.003235,24.986092,0.103738,5.130823,0.008090,0.899594,0.000336,0.0288,0.000310
1,classwise,3.445554,0.018924,15.925437,0.488810,8.845279,0.296235,0.910559,0.000297,0.0136,0.000982
2,cluster_random,2.596498,0.038149,16.365052,1.178874,6.469633,0.340526,0.901659,0.001300,0.0103,0.001543

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.012505,0.003235,24.986092,0.103738,5.130823,0.008090,0.899594,0.000336,0.0288,0.000310
1,classwise,3.445554,0.018924,15.925437,0.488810,8.845279,0.296235,0.910559,0.000297,0.0136,0.000982
2,cluster_random,2.596498,0.038149,16.365052,1.178874,6.469633,0.340526,0.901659,0.001300,0.0103,0.001543

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.012505,0.003235,24.986092,0.103738,5.130823,0.008090,0.899594,0.000336,0.0288,0.000310
1,classwise,3.445554,0.018924,15.925437,0.488810,8.845279,0.296235,0.910559,0.000297,0.0136,0.000982
2,cluster_random,2.596498,0.038149,16.365052,1.178874,6.469633,0.340526,0.901659,0.001300,0.0103,0.001543

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.060920,0.029904,12.731093,0.246655,7.944268,0.092258,0.899816,0.001174,0.053,0.006008
1,classwise,3.765921,0.049761,13.545768,1.012115,11.862752,0.202562,0.909124,0.000953,0.014,0.002098
2,cluster_random,2.910073,0.059641,11.881200,0.841146,9.315084,0.339112,0.903892,0.002606,0.011,0.002983

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.060920,0.029904,12.731093,0.246655,7.944268,0.092258,0.899816,0.001174,0.053,0.006008
1,classwise,3.765921,0.049761,13.545768,1.012115,11.862752,0.202562,0.909124,0.000953,0.014,0.002098
2,cluster_random,2.910073,0.059641,11.881200,0.841146,9.315084,0.339112,0.903892,0.002606,0.011,0.002983

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.060920,0.029904,12.731093,0.246655,7.944268,0.092258,0.899816,0.001174,0.053,0.006008
1,classwise,3.765921,0.049761,13.545768,1.012115,11.862752,0.202562,0.909124,0.000953,0.014,0.002098
2,cluster_random,2.910073,0.059641,11.881200,0.841146,9.315084,0.339112,0.903892,0.002606,0.011,0.002983

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.794926,0.040595,13.969376,0.300137,11.015248,0.132524,0.899576,0.001049,0.040,0.004000
1,classwise,3.838417,0.055273,13.676308,0.758143,15.000924,0.232260,0.908252,0.001134,0.025,0.003536
2,cluster_random,3.124563,0.089137,12.263758,0.862369,12.172664,0.358775,0.902916,0.002286,0.015,0.004062

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.794926,0.040595,13.969376,0.300137,11.015248,0.132524,0.899576,0.001049,0.040,0.004000
1,classwise,3.838417,0.055273,13.676308,0.758143,15.000924,0.232260,0.908252,0.001134,0.025,0.003536
2,cluster_random,3.124563,0.089137,12.263758,0.862369,12.172664,0.358775,0.902916,0.002286,0.015,0.004062

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.794926,0.040595,13.969376,0.300137,11.015248,0.132524,0.899576,0.001049,0.040,0.004000
1,classwise,3.838417,0.055273,13.676308,0.758143,15.000924,0.232260,0.908252,0.001134,0.025,0.003536
2,cluster_random,3.124563,0.089137,12.263758,0.862369,12.172664,0.358775,0.902916,0.002286,0.015,0.004062

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.818078,0.044583,15.632404,0.500775,8.282496,0.117101,0.900956,0.001256,0.071,0.005559
1,classwise,3.760621,0.058908,13.194248,0.715879,13.321652,0.209580,0.911844,0.001280,0.021,0.004111
2,cluster_random,3.653425,0.096456,14.782338,1.163044,9.532576,0.342673,0.902620,0.002749,0.028,0.005621

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.818078,0.044583,15.632404,0.500775,8.282496,0.117101,0.900956,0.001256,0.071,0.005559
1,classwise,3.760621,0.058908,13.194248,0.715879,13.321652,0.209580,0.911844,0.001280,0.021,0.004111
2,cluster_random,3.653425,0.096456,14.782338,1.163044,9.532576,0.342673,0.902620,0.002749,0.028,0.005621

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.818078,0.044583,15.632404,0.500775,8.282496,0.117101,0.900956,0.001256,0.071,0.005559
1,classwise,3.760621,0.058908,13.194248,0.715879,13.321652,0.209580,0.911844,0.001280,0.021,0.004111
2,cluster_random,3.653425,0.096456,14.782338,1.163044,9.532576,0.342673,0.902620,0.002749,0.028,0.005621

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.557883,0.017559,22.226534,0.318183,6.894202,0.029251,0.900052,0.000528,0.066849,0.001826
1,classwise,3.529299,0.039731,14.194968,0.597971,10.119469,0.080556,0.910324,0.000498,0.013425,0.001473
2,cluster_random,3.014302,0.048158,14.360796,0.904853,7.800403,0.093450,0.902192,0.001467,0.012329,0.002518

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.557883,0.017559,22.226534,0.318183,6.894202,0.029251,0.900052,0.000528,0.066849,0.001826
1,classwise,3.529299,0.039731,14.194968,0.597971,10.119469,0.080556,0.910324,0.000498,0.013425,0.001473
2,cluster_random,3.014302,0.048158,14.360796,0.904853,7.800403,0.093450,0.902192,0.001467,0.012329,0.002518

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.557883,0.017559,22.226534,0.318183,6.894202,0.029251,0.900052,0.000528,0.066849,0.001826
1,classwise,3.529299,0.039731,14.194968,0.597971,10.119469,0.080556,0.910324,0.000498,0.013425,0.001473
2,cluster_random,3.014302,0.048158,14.360796,0.904853,7.800403,0.093450,0.902192,0.001467,0.012329,0.002518

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.266891,0.013101,17.715231,0.274245,10.810746,0.075307,0.900370,0.000887,0.029041,0.002363
1,classwise,3.540893,0.046500,14.109071,0.759182,14.420730,0.139286,0.910420,0.000669,0.014795,0.002605
2,cluster_random,2.644636,0.042808,12.087248,0.636751,11.759405,0.140879,0.904021,0.001782,0.005479,0.001501

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.266891,0.013101,17.715231,0.274245,10.810746,0.075307,0.900370,0.000887,0.029041,0.002363
1,classwise,3.540893,0.046500,14.109071,0.759182,14.420730,0.139286,0.910420,0.000669,0.014795,0.002605
2,cluster_random,2.644636,0.042808,12.087248,0.636751,11.759405,0.140879,0.904021,0.001782,0.005479,0.001501

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.266891,0.013101,17.715231,0.274245,10.810746,0.075307,0.900370,0.000887,0.029041,0.002363
1,classwise,3.540893,0.046500,14.109071,0.759182,14.420730,0.139286,0.910420,0.000669,0.014795,0.002605
2,cluster_random,2.644636,0.042808,12.087248,0.636751,11.759405,0.140879,0.904021,0.001782,0.005479,0.001501

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.829433,0.004131,20.486255,0.310308,7.913165,0.030951,0.899760,0.000710,0.044932,0.001945
1,classwise,3.557721,0.049719,14.685682,0.727140,11.415326,0.103420,0.910827,0.000494,0.014521,0.001860
2,cluster_random,2.971410,0.037041,12.163625,0.724442,8.769927,0.091061,0.902991,0.001307,0.006575,0.001460

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.829433,0.004131,20.486255,0.310308,7.913165,0.030951,0.899760,0.000710,0.044932,0.001945
1,classwise,3.557721,0.049719,14.685682,0.727140,11.415326,0.103420,0.910827,0.000494,0.014521,0.001860
2,cluster_random,2.971410,0.037041,12.163625,0.724442,8.769927,0.091061,0.902991,0.001307,0.006575,0.001460

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.829433,0.004131,20.486255,0.310308,7.913165,0.030951,0.899760,0.000710,0.044932,0.001945
1,classwise,3.557721,0.049719,14.685682,0.727140,11.415326,0.103420,0.910827,0.000494,0.014521,0.001860
2,cluster_random,2.971410,0.037041,12.163625,0.724442,8.769927,0.091061,0.902991,0.001307,0.006575,0.001460

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.986350,0.051192,46.357924,0.486381,3.158427,0.022346,0.899590,0.000714,0.200000,0.003081
1,classwise,5.790269,0.025053,27.994279,1.754111,148.701598,2.213135,0.909733,0.000525,0.032701,0.002257
2,cluster_random,5.714272,0.079176,46.128941,0.582503,3.719296,0.039736,0.896847,0.001393,0.141864,0.004853

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.986350,0.051192,46.357924,0.486381,3.158427,0.022346,0.899590,0.000714,0.200000,0.003081
1,classwise,5.790269,0.025053,27.994279,1.754111,148.701598,2.213135,0.909733,0.000525,0.032701,0.002257
2,cluster_random,5.714272,0.079176,46.128941,0.582503,3.719296,0.039736,0.896847,0.001393,0.141864,0.004853

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.986350,0.051192,46.357924,0.486381,3.158427,0.022346,0.899590,0.000714,0.200000,0.003081
1,classwise,5.790269,0.025053,27.994279,1.754111,148.701598,2.213135,0.909733,0.000525,0.032701,0.002257
2,cluster_random,5.714272,0.079176,46.128941,0.582503,3.719296,0.039736,0.896847,0.001393,0.141864,0.004853

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.124665,0.029993,59.696853,0.310326,8.326705,0.044617,0.899428,0.000702,0.094787,0.001431
1,classwise,5.749162,0.031729,30.743042,2.630208,153.895984,2.169553,0.909410,0.000690,0.030964,0.002377
2,cluster_random,3.920263,0.049843,60.151538,0.406266,8.459967,0.058875,0.896829,0.000934,0.079463,0.002246

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.124665,0.029993,59.696853,0.310326,8.326705,0.044617,0.899428,0.000702,0.094787,0.001431
1,classwise,5.749162,0.031729,30.743042,2.630208,153.895984,2.169553,0.909410,0.000690,0.030964,0.002377
2,cluster_random,3.920263,0.049843,60.151538,0.406266,8.459967,0.058875,0.896829,0.000934,0.079463,0.002246

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.124665,0.029993,59.696853,0.310326,8.326705,0.044617,0.899428,0.000702,0.094787,0.001431
1,classwise,5.749162,0.031729,30.743042,2.630208,153.895984,2.169553,0.909410,0.000690,0.030964,0.002377
2,cluster_random,3.920263,0.049843,60.151538,0.406266,8.459967,0.058875,0.896829,0.000934,0.079463,0.002246

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.008053,0.022852,57.473321,0.189640,5.141045,0.013047,0.898621,0.000530,0.126540,0.002041
1,classwise,5.769286,0.034619,31.210096,2.576995,155.268758,2.308431,0.909784,0.000640,0.029068,0.002038
2,cluster_random,4.548881,0.052214,57.647726,0.303686,5.379246,0.096459,0.895893,0.001107,0.105055,0.002991

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.008053,0.022852,57.473321,0.189640,5.141045,0.013047,0.898621,0.000530,0.126540,0.002041
1,classwise,5.769286,0.034619,31.210096,2.576995,155.268758,2.308431,0.909784,0.000640,0.029068,0.002038
2,cluster_random,4.548881,0.052214,57.647726,0.303686,5.379246,0.096459,0.895893,0.001107,0.105055,0.002991

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.008053,0.022852,57.473321,0.189640,5.141045,0.013047,0.898621,0.000530,0.126540,0.002041
1,classwise,5.769286,0.034619,31.210096,2.576995,155.268758,2.308431,0.909784,0.000640,0.029068,0.002038
2,cluster_random,4.548881,0.052214,57.647726,0.303686,5.379246,0.096459,0.895893,0.001107,0.105055,0.002991

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.249914,0.015911,38.509857,0.159223,1.920399,0.009198,0.899465,0.000475,0.0825,0.001961
1,classwise,2.805084,0.020637,13.439692,0.591760,4.152084,0.054713,0.906443,0.000328,0.0058,0.000759
2,cluster_random,2.763149,0.015632,14.988452,0.583557,2.712350,0.035263,0.900915,0.000556,0.0087,0.000722

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.249914,0.015911,38.509857,0.159223,1.920399,0.009198,0.899465,0.000475,0.0825,0.001961
1,classwise,2.805084,0.020637,13.439692,0.591760,4.152084,0.054713,0.906443,0.000328,0.0058,0.000759
2,cluster_random,2.763149,0.015632,14.988452,0.583557,2.712350,0.035263,0.900915,0.000556,0.0087,0.000722

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.249914,0.015911,38.509857,0.159223,1.920399,0.009198,0.899465,0.000475,0.0825,0.001961
1,classwise,2.805084,0.020637,13.439692,0.591760,4.152084,0.054713,0.906443,0.000328,0.0058,0.000759
2,cluster_random,2.763149,0.015632,14.988452,0.583557,2.712350,0.035263,0.900915,0.000556,0.0087,0.000722

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.581067,0.003474,21.538192,0.124123,25.678643,0.084803,0.899664,0.000265,0.0214,0.000155
1,classwise,2.851441,0.018811,13.603989,0.508577,34.983663,0.171415,0.906735,0.000316,0.0056,0.000636
2,cluster_random,2.202699,0.028626,13.803442,0.464076,27.309433,0.409062,0.900550,0.001175,0.0037,0.000584

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.581067,0.003474,21.538192,0.124123,25.678643,0.084803,0.899664,0.000265,0.0214,0.000155
1,classwise,2.851441,0.018811,13.603989,0.508577,34.983663,0.171415,0.906735,0.000316,0.0056,0.000636
2,cluster_random,2.202699,0.028626,13.803442,0.464076,27.309433,0.409062,0.900550,0.001175,0.0037,0.000584

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.581067,0.003474,21.538192,0.124123,25.678643,0.084803,0.899664,0.000265,0.0214,0.000155
1,classwise,2.851441,0.018811,13.603989,0.508577,34.983663,0.171415,0.906735,0.000316,0.0056,0.000636
2,cluster_random,2.202699,0.028626,13.803442,0.464076,27.309433,0.409062,0.900550,0.001175,0.0037,0.000584

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.017877,0.001368,25.147991,0.113629,5.121456,0.006868,0.899513,0.000285,0.0294,0.000352
1,classwise,2.848706,0.023445,14.113776,0.622130,7.283570,0.105987,0.906942,0.000318,0.0058,0.000465
2,cluster_random,2.399224,0.041172,13.596154,0.360776,6.813776,0.310162,0.900248,0.001033,0.0052,0.000525

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.017877,0.001368,25.147991,0.113629,5.121456,0.006868,0.899513,0.000285,0.0294,0.000352
1,classwise,2.848706,0.023445,14.113776,0.622130,7.283570,0.105987,0.906942,0.000318,0.0058,0.000465
2,cluster_random,2.399224,0.041172,13.596154,0.360776,6.813776,0.310162,0.900248,0.001033,0.0052,0.000525

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.017877,0.001368,25.147991,0.113629,5.121456,0.006868,0.899513,0.000285,0.0294,0.000352
1,classwise,2.848706,0.023445,14.113776,0.622130,7.283570,0.105987,0.906942,0.000318,0.0058,0.000465
2,cluster_random,2.399224,0.041172,13.596154,0.360776,6.813776,0.310162,0.900248,0.001033,0.0052,0.000525

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.111595,0.031117,13.208247,0.387584,7.960422,0.086798,0.900089,0.001275,0.052,0.006293
1,classwise,3.230817,0.079223,11.833915,1.292336,10.767978,0.134374,0.906644,0.001146,0.007,0.002470
2,cluster_random,2.819645,0.024655,10.683185,1.004404,9.128711,0.154848,0.902351,0.001733,0.005,0.002121

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.111595,0.031117,13.208247,0.387584,7.960422,0.086798,0.900089,0.001275,0.052,0.006293
1,classwise,3.230817,0.079223,11.833915,1.292336,10.767978,0.134374,0.906644,0.001146,0.007,0.002470
2,cluster_random,2.819645,0.024655,10.683185,1.004404,9.128711,0.154848,0.902351,0.001733,0.005,0.002121

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.111595,0.031117,13.208247,0.387584,7.960422,0.086798,0.900089,0.001275,0.052,0.006293
1,classwise,3.230817,0.079223,11.833915,1.292336,10.767978,0.134374,0.906644,0.001146,0.007,0.002470
2,cluster_random,2.819645,0.024655,10.683185,1.004404,9.128711,0.154848,0.902351,0.001733,0.005,0.002121

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.813230,0.044349,14.326751,0.488346,11.027729,0.103392,0.899978,0.000952,0.037,0.004701
1,classwise,3.172777,0.076518,12.509021,0.897185,13.689400,0.131919,0.906347,0.001031,0.009,0.001703
2,cluster_random,2.845385,0.073895,12.065695,0.530006,12.191720,0.244148,0.903587,0.001631,0.013,0.003178

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.813230,0.044349,14.326751,0.488346,11.027729,0.103392,0.899978,0.000952,0.037,0.004701
1,classwise,3.172777,0.076518,12.509021,0.897185,13.689400,0.131919,0.906347,0.001031,0.009,0.001703
2,cluster_random,2.845385,0.073895,12.065695,0.530006,12.191720,0.244148,0.903587,0.001631,0.013,0.003178

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.813230,0.044349,14.326751,0.488346,11.027729,0.103392,0.899978,0.000952,0.037,0.004701
1,classwise,3.172777,0.076518,12.509021,0.897185,13.689400,0.131919,0.906347,0.001031,0.009,0.001703
2,cluster_random,2.845385,0.073895,12.065695,0.530006,12.191720,0.244148,0.903587,0.001631,0.013,0.003178

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.856711,0.050029,15.903742,0.566875,8.143880,0.122721,0.900653,0.001293,0.073,0.006790
1,classwise,3.290470,0.058563,12.776595,1.058569,12.066396,0.104426,0.908782,0.001077,0.009,0.002214
2,cluster_random,3.393141,0.078233,15.795460,0.803086,9.866116,0.124130,0.904022,0.001319,0.021,0.003302

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.856711,0.050029,15.903742,0.566875,8.143880,0.122721,0.900653,0.001293,0.073,0.006790
1,classwise,3.290470,0.058563,12.776595,1.058569,12.066396,0.104426,0.908782,0.001077,0.009,0.002214
2,cluster_random,3.393141,0.078233,15.795460,0.803086,9.866116,0.124130,0.904022,0.001319,0.021,0.003302

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.856711,0.050029,15.903742,0.566875,8.143880,0.122721,0.900653,0.001293,0.073,0.006790
1,classwise,3.290470,0.058563,12.776595,1.058569,12.066396,0.104426,0.908782,0.001077,0.009,0.002214
2,cluster_random,3.393141,0.078233,15.795460,0.803086,9.866116,0.124130,0.904022,0.001319,0.021,0.003302

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.560404,0.017632,22.233482,0.302304,6.912210,0.023928,0.900348,0.000449,0.065205,0.001010
1,classwise,2.970193,0.021675,12.025111,0.539365,9.335470,0.064083,0.907208,0.000550,0.005479,0.001225
2,cluster_random,2.861739,0.056389,13.270487,0.630777,7.876492,0.100794,0.901326,0.001121,0.010137,0.001503

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.560404,0.017632,22.233482,0.302304,6.912210,0.023928,0.900348,0.000449,0.065205,0.001010
1,classwise,2.970193,0.021675,12.025111,0.539365,9.335470,0.064083,0.907208,0.000550,0.005479,0.001225
2,cluster_random,2.861739,0.056389,13.270487,0.630777,7.876492,0.100794,0.901326,0.001121,0.010137,0.001503

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.560404,0.017632,22.233482,0.302304,6.912210,0.023928,0.900348,0.000449,0.065205,0.001010
1,classwise,2.970193,0.021675,12.025111,0.539365,9.335470,0.064083,0.907208,0.000550,0.005479,0.001225
2,cluster_random,2.861739,0.056389,13.270487,0.630777,7.876492,0.100794,0.901326,0.001121,0.010137,0.001503

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.272919,0.009931,18.288718,0.277755,10.784092,0.051382,0.899891,0.000638,0.030959,0.001452
1,classwise,2.964360,0.024100,13.839720,0.734918,13.403690,0.080439,0.907011,0.000541,0.006301,0.000780
2,cluster_random,2.697650,0.058367,12.206661,0.666917,11.632419,0.232729,0.899610,0.001844,0.008767,0.002842

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.272919,0.009931,18.288718,0.277755,10.784092,0.051382,0.899891,0.000638,0.030959,0.001452
1,classwise,2.964360,0.024100,13.839720,0.734918,13.403690,0.080439,0.907011,0.000541,0.006301,0.000780
2,cluster_random,2.697650,0.058367,12.206661,0.666917,11.632419,0.232729,0.899610,0.001844,0.008767,0.002842

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.272919,0.009931,18.288718,0.277755,10.784092,0.051382,0.899891,0.000638,0.030959,0.001452
1,classwise,2.964360,0.024100,13.839720,0.734918,13.403690,0.080439,0.907011,0.000541,0.006301,0.000780
2,cluster_random,2.697650,0.058367,12.206661,0.666917,11.632419,0.232729,0.899610,0.001844,0.008767,0.002842

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.833976,0.005698,19.891162,0.267609,7.942699,0.019807,0.900272,0.000474,0.043562,0.001571
1,classwise,2.969699,0.031512,13.817297,0.808982,10.471721,0.083128,0.907536,0.000438,0.006301,0.001029
2,cluster_random,2.924348,0.032836,12.648759,0.339402,8.962038,0.156656,0.899649,0.001555,0.007945,0.001523

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.833976,0.005698,19.891162,0.267609,7.942699,0.019807,0.900272,0.000474,0.043562,0.001571
1,classwise,2.969699,0.031512,13.817297,0.808982,10.471721,0.083128,0.907536,0.000438,0.006301,0.001029
2,cluster_random,2.924348,0.032836,12.648759,0.339402,8.962038,0.156656,0.899649,0.001555,0.007945,0.001523

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.833976,0.005698,19.891162,0.267609,7.942699,0.019807,0.900272,0.000474,0.043562,0.001571
1,classwise,2.969699,0.031512,13.817297,0.808982,10.471721,0.083128,0.907536,0.000438,0.006301,0.001029
2,cluster_random,2.924348,0.032836,12.648759,0.339402,8.962038,0.156656,0.899649,0.001555,0.007945,0.001523

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.972572,0.039347,46.215629,0.478789,3.162420,0.016724,0.899730,0.000538,0.198894,0.002029
1,classwise,4.838617,0.031674,30.939660,2.667140,55.312337,1.572485,0.906084,0.000583,0.034597,0.001253
2,cluster_random,5.314805,0.075520,46.777539,0.480995,3.751900,0.028016,0.897918,0.000636,0.130490,0.004234

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.972572,0.039347,46.215629,0.478789,3.162420,0.016724,0.899730,0.000538,0.198894,0.002029
1,classwise,4.838617,0.031674,30.939660,2.667140,55.312337,1.572485,0.906084,0.000583,0.034597,0.001253
2,cluster_random,5.314805,0.075520,46.777539,0.480995,3.751900,0.028016,0.897918,0.000636,0.130490,0.004234

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.972572,0.039347,46.215629,0.478789,3.162420,0.016724,0.899730,0.000538,0.198894,0.002029
1,classwise,4.838617,0.031674,30.939660,2.667140,55.312337,1.572485,0.906084,0.000583,0.034597,0.001253
2,cluster_random,5.314805,0.075520,46.777539,0.480995,3.751900,0.028016,0.897918,0.000636,0.130490,0.004234

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.166114,0.022271,59.660843,0.213661,8.332199,0.030000,0.899429,0.000475,0.099210,0.001240
1,classwise,4.759949,0.039305,28.125582,1.349976,60.695288,1.541884,0.906200,0.000415,0.032859,0.002093
2,cluster_random,3.523028,0.042416,59.532954,0.556044,8.668709,0.072714,0.897923,0.000913,0.058136,0.001113

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.166114,0.022271,59.660843,0.213661,8.332199,0.030000,0.899429,0.000475,0.099210,0.001240
1,classwise,4.759949,0.039305,28.125582,1.349976,60.695288,1.541884,0.906200,0.000415,0.032859,0.002093
2,cluster_random,3.523028,0.042416,59.532954,0.556044,8.668709,0.072714,0.897923,0.000913,0.058136,0.001113

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.166114,0.022271,59.660843,0.213661,8.332199,0.030000,0.899429,0.000475,0.099210,0.001240
1,classwise,4.759949,0.039305,28.125582,1.349976,60.695288,1.541884,0.906200,0.000415,0.032859,0.002093
2,cluster_random,3.523028,0.042416,59.532954,0.556044,8.668709,0.072714,0.897923,0.000913,0.058136,0.001113

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.962075,0.018908,56.892585,0.233436,5.158425,0.011148,0.899221,0.000467,0.127488,0.001323
1,classwise,4.856312,0.043951,27.448262,1.082188,63.111438,1.672252,0.906876,0.000483,0.032385,0.002134
2,cluster_random,4.104375,0.054755,57.146218,0.295667,5.424337,0.057444,0.897728,0.000859,0.082780,0.002819

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.962075,0.018908,56.892585,0.233436,5.158425,0.011148,0.899221,0.000467,0.127488,0.001323
1,classwise,4.856312,0.043951,27.448262,1.082188,63.111438,1.672252,0.906876,0.000483,0.032385,0.002134
2,cluster_random,4.104375,0.054755,57.146218,0.295667,5.424337,0.057444,0.897728,0.000859,0.082780,0.002819

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.962075,0.018908,56.892585,0.233436,5.158425,0.011148,0.899221,0.000467,0.127488,0.001323
1,classwise,4.856312,0.043951,27.448262,1.082188,63.111438,1.672252,0.906876,0.000483,0.032385,0.002134
2,cluster_random,4.104375,0.054755,57.146218,0.295667,5.424337,0.057444,0.897728,0.000859,0.082780,0.002819

\begin{tabular}{lllcrcrcrcr}
\toprule
            &         &              & \multicolumn{2}{c}{$n_{\text{avg}}=10$} & \multicolumn{2}{c}{$n_{\text{avg}}=20$} & \multicolumn{2}{c}{$n_{\text{avg}}=50$} & \multicolumn{2}{c}{$n_{\text{avg}}=75$} \\ \cmidrule(lr){4-5}\cmidrule(lr){6-7} \cmidrule(lr){8-9} \cmidrule(lr){10-11}\
            &         &              &              CovGap &      AvgSize &              CovGap &      AvgSize &              CovGap &      AvgSize &              CovGap &     AvgSize \\
Dataset & Score func. & Method &                     &              &                     &              &                     &              &                     &             \\
\midrule
ImageNet & $\softmax$ & $\standard$ &           5.2 (0.0) &    1.9 (0.0) &           5.2 (0.0) &    1.9 (0.0) &           5.3 (0.0) &    1.9 (0.0) &           5.2 (0.0) &   1.9 (0.0) \\
            &         & $\classwise$ &           7.7 (0.0) &  354.4 (2.0) &           5.4 (0.0) &   23.0 (0.9) &           3.4 (0.0) &    5.1 (0.1) &           2.8 (0.0) &   4.2 (0.1) \\
            &         & $\clustered$ &           4.9 (0.1) &    2.5 (0.1) &           3.9 (0.0) &    2.7 (0.1) &           3.1 (0.0) &    2.6 (0.1) &           2.8 (0.0) &   2.7 (0.0) \\
            \cline{3-11} & $\APS$ & $\standard$ &           2.6 (0.0) &   25.9 (0.3) &           2.6 (0.0) &   25.8 (0.1) &           2.5 (0.0) &   25.6 (0.1) &           2.6 (0.0) &  25.7 (0.1) \\
            &         & $\classwise$ &           7.6 (0.0) &  394.2 (1.9) &           5.5 (0.0) &   76.9 (0.8) &           3.5 (0.0) &   39.7 (0.2) &           2.9 (0.0) &  35.0 (0.2) \\
            &         & $\clustered$ &           3.0 (0.1) &   29.6 (1.5) &           2.6 (0.0) &   27.0 (0.7) &           2.3 (0.0) &   27.2 (0.5) &           2.2 (0.0) &  27.3 (0.4) \\
            \cline{3-11} & $\RAPS$ & $\standard$ &           3.0 (0.0) &    5.2 (0.0) &           3.0 (0.0) &    5.1 (0.0) &           3.0 (0.0) &    5.1 (0.0) &           3.0 (0.0) &   5.1 (0.0) \\
            &         & $\classwise$ &           7.7 (0.1) &  361.9 (1.9) &           5.6 (0.0) &   34.2 (1.0) &           3.4 (0.0) &    8.8 (0.3) &           2.8 (0.0) &   7.3 (0.1) \\
            &         & $\clustered$ &           3.1 (0.0) &    7.7 (1.0) &           2.9 (0.0) &    6.6 (0.6) &           2.6 (0.0) &    6.5 (0.3) &           2.4 (0.0) &   6.8 (0.3) \\
\midrule
CIFAR-100 & $\softmax$ & $\standard$ &           4.0 (0.1) &    8.1 (0.2) &           4.0 (0.0) &    7.9 (0.2) &           4.1 (0.0) &    7.9 (0.1) &           4.1 (0.0) &   8.0 (0.1) \\
            &         & $\classwise$ &           7.6 (0.1) &   47.2 (0.6) &           5.6 (0.1) &   19.3 (0.5) &           3.8 (0.0) &   11.9 (0.2) &           3.2 (0.1) &  10.8 (0.1) \\
            &         & $\clustered$ &           4.2 (0.1) &    8.9 (0.5) &           3.6 (0.1) &    8.9 (0.3) &           2.9 (0.1) &    9.3 (0.3) &           2.8 (0.0) &   9.1 (0.2) \\
            \cline{3-11} & $\APS$ & $\standard$ &           3.7 (0.1) &   11.2 (0.3) &           3.7 (0.0) &   10.8 (0.2) &           3.8 (0.0) &   11.0 (0.1) &           3.8 (0.0) &  11.0 (0.1) \\
            &         & $\classwise$ &           7.5 (0.1) &   49.4 (0.5) &           5.6 (0.1) &   22.6 (0.5) &           3.8 (0.1) &   15.0 (0.2) &           3.2 (0.1) &  13.7 (0.1) \\
            &         & $\clustered$ &           4.0 (0.1) &   11.9 (0.5) &           3.6 (0.1) &   12.1 (0.5) &           3.1 (0.1) &   12.2 (0.4) &           2.8 (0.1) &  12.2 (0.2) \\
            \cline{3-11} & $\RAPS$ & $\standard$ &           4.7 (0.1) &    8.6 (0.3) &           4.8 (0.1) &    8.3 (0.3) &           4.8 (0.0) &    8.3 (0.1) &           4.9 (0.1) &   8.1 (0.1) \\
            &         & $\classwise$ &           7.5 (0.1) &   47.5 (0.7) &           5.6 (0.1) &   20.7 (0.6) &           3.8 (0.1) &   13.3 (0.2) &           3.3 (0.1) &  12.1 (0.1) \\
            &         & $\clustered$ &           4.9 (0.1) &    9.5 (0.5) &           4.5 (0.1) &    8.7 (0.5) &           3.7 (0.1) &    9.5 (0.3) &           3.4 (0.1) &   9.9 (0.1) \\
\midrule
Places365 & $\softmax$ & $\standard$ &           4.5 (0.0) &    6.9 (0.1) &           4.5 (0.0) &    6.9 (0.0) &           4.6 (0.0) &    6.9 (0.0) &           4.6 (0.0) &   6.9 (0.0) \\
            &         & $\classwise$ &           7.6 (0.1) &  136.5 (1.7) &           5.4 (0.0) &   18.0 (0.2) &           3.5 (0.0) &   10.1 (0.1) &           3.0 (0.0) &   9.3 (0.1) \\
            &         & $\clustered$ &           4.5 (0.1) &    7.1 (0.1) &           3.9 (0.1) &    7.1 (0.1) &           3.0 (0.0) &    7.8 (0.1) &           2.9 (0.1) &   7.9 (0.1) \\
            \cline{3-11} & $\APS$ & $\standard$ &           3.3 (0.0) &   10.8 (0.1) &           3.3 (0.0) &   10.9 (0.1) &           3.3 (0.0) &   10.8 (0.1) &           3.3 (0.0) &  10.8 (0.1) \\
            &         & $\classwise$ &           7.6 (0.1) &  140.5 (1.7) &           5.4 (0.1) &   23.5 (0.3) &           3.5 (0.0) &   14.4 (0.1) &           3.0 (0.0) &  13.4 (0.1) \\
            &         & $\clustered$ &           3.5 (0.1) &   10.9 (0.3) &           3.1 (0.0) &   10.9 (0.2) &           2.6 (0.0) &   11.8 (0.1) &           2.7 (0.1) &  11.6 (0.2) \\
            \cline{3-11} & $\RAPS$ & $\standard$ &           3.8 (0.0) &    7.9 (0.0) &           3.9 (0.0) &    7.9 (0.0) &           3.8 (0.0) &    7.9 (0.0) &           3.8 (0.0) &   7.9 (0.0) \\
            &         & $\classwise$ &           7.6 (0.1) &  138.9 (1.7) &           5.5 (0.1) &   21.3 (0.3) &           3.6 (0.0) &   11.4 (0.1) &           3.0 (0.0) &  10.5 (0.1) \\
            &         & $\clustered$ &           3.9 (0.1) &    8.0 (0.1) &           3.4 (0.0) &    8.2 (0.2) &           3.0 (0.0) &    8.8 (0.1) &           2.9 (0.0) &   9.0 (0.2) \\
\midrule
iNaturalist & $\softmax$ & $\standard$ &           7.0 (0.1) &    3.1 (0.0) &           7.0 (0.1) &    3.1 (0.0) &           7.0 (0.1) &    3.2 (0.0) &           7.0 (0.0) &   3.2 (0.0) \\
            &         & $\classwise$ &           8.7 (0.0) &  469.4 (1.8) &           7.8 (0.0) &  364.0 (1.4) &           5.8 (0.0) &  148.7 (2.2) &           4.8 (0.0) &  55.3 (1.6) \\
            &         & $\clustered$ &           6.9 (0.2) &    3.1 (0.1) &           6.4 (0.1) &    3.4 (0.1) &           5.7 (0.1) &    3.7 (0.0) &           5.3 (0.1) &   3.8 (0.0) \\
            \cline{3-11} & $\APS$ & $\standard$ &           4.3 (0.1) &    8.3 (0.1) &           4.2 (0.1) &    8.4 (0.1) &           4.1 (0.0) &    8.3 (0.0) &           4.2 (0.0) &   8.3 (0.0) \\
            &         & $\classwise$ &           8.7 (0.0) &  472.8 (1.8) &           7.8 (0.0) &  368.4 (1.4) &           5.7 (0.0) &  153.9 (2.2) &           4.8 (0.0) &  60.7 (1.5) \\
            &         & $\clustered$ &           4.3 (0.1) &    8.1 (0.1) &           4.1 (0.1) &    8.3 (0.1) &           3.9 (0.0) &    8.5 (0.1) &           3.5 (0.0) &   8.7 (0.1) \\
            \cline{3-11} & $\RAPS$ & $\standard$ &           5.1 (0.1) &    5.1 (0.0) &           5.0 (0.0) &    5.2 (0.0) &           5.0 (0.0) &    5.1 (0.0) &           5.0 (0.0) &   5.2 (0.0) \\
            &         & $\classwise$ &           8.7 (0.0) &  473.8 (1.9) &           7.8 (0.0) &  369.2 (1.5) &           5.8 (0.0) &  155.3 (2.3) &           4.9 (0.0) &  63.1 (1.7) \\
            &         & $\clustered$ &           5.0 (0.1) &    5.0 (0.0) &           4.9 (0.1) &    5.2 (0.0) &           4.5 (0.1) &    5.4 (0.1) &           4.1 (0.1) &   5.4 (0.1) \\
\bottomrule
\end{tabular}

/tmp/ipykernel_1785434/3021232834.py:30: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  df_str = df.to_latex(multicolumn_format='c', # To center multilevel column headers

In [32]:
# Investigate marginal coverage
# n_totalcals = {10: '$n_{\text{avg}}=10$', 30: '$n_{\text{avg}}=30$', 75: '$n_{\text{avg}}=75$'}
n_totalcals = {10: '$n_{\text{avg}}=10$', 
               20: '$n_{\text{avg}}=20$', 
               30: '$n_{\text{avg}}=30$', 
               40: '$n_{\text{avg}}=40$', 
               50: '$n_{\text{avg}}=50$', 
               75: '$n_{\text{avg}}=75$',
               100: '$n_{\text{avg}}=100$'}

methods = {'standard': '$\standard$', 
            'classwise': '$\classwise$',
            'exact_coverage_classwise': 'ExactCov-$\classwise$',
            'cluster_random': '$\clustered$'} # TODO: update

horizontal_dict = {}
for n_totalcal, n_name in n_totalcals.items():
    vertical_list = []
    for dataset, save_folder in datasets.items():
        for score, score_name in score_functions.items():
            for method, method_name in methods.items(): 

                folder = f'{save_folder}/{calibration_sampling}_calset/n_totalcal={n_totalcal}/score={score}/'
                print(folder)
                df = average_results_across_seeds(folder, print_results=False, methods=methods.keys()) # df = results DataFrame
                s = pd.Series({'Dataset': dataset, 'Score func.': score_name, 'Method': method_name, 
#                                'CovGap': f"{df[df['method'] == method]['class_cov_gap_mean'].values[0]:.1f}" 
#                                        f" ({df[df['method'] == method]['class_cov_gap_se'].values[0]:.1f})",
#                                'AvgSize': f"{df[df['method'] == method]['avg_set_size_mean'].values[0]:.1f}" 
#                                                f" ({df[df['method'] == method]['avg_set_size_se'].values[0]:.1f})",
                               'MargCov': f"{df[df['method'] == method]['marginal_cov_mean'].values[0]*100:.1f}" 
                                                   f" ({df[df['method'] == method]['marginal_cov_se'].values[0]*100:.1f})"})
                vertical_list.append(pd.DataFrame(s).transpose())                                        

    df = pd.concat(vertical_list, ignore_index=True)                                                     
    df = df.set_index(['Dataset', 'Score func.', 'Method'])
    horizontal_dict[n_name] = df
#     pdb.set_trace()

df = pd.concat(horizontal_dict, axis=1)
df_str = df.to_latex(multicolumn_format='c', # To center multilevel column headers
    escape=False # So that backslashes are printed as `\' rather than '\textbackslash'
                 )
# Post-process
# df_str = df_str.replace('lllllllll', 'lllcrccrc')
# df_str = df_str.replace('$n_{\\text{avg}}=75$ \\',
#                '$n_{\\text{avg}}=75$ \\\\ \cmidrule(lr){4}\cmidrule(lr){5} \cmidrule(lr){6}\\')
df_str = df_str.replace('CIFAR-100', '\midrule\nCIFAR-100')
df_str = df_str.replace('Places365', '\midrule\nPlaces365')
df_str = df_str.replace('iNaturalist', '\midrule\niNaturalist')
print(df_str)

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.223009,0.026946,38.294309,0.320930,1.940409,0.017132,0.900390,0.000849,0.0784,0.003021
1,classwise,7.665144,0.045728,38.259073,1.171264,354.400610,2.023354,0.946082,0.000518,0.0547,0.001744
2,exact_coverage_classwise,6.379476,0.036736,41.728767,1.626773,99.981451,0.651829,0.899728,0.000598,0.1198,0.002257
3,cluster_random,4.871419,0.087259,34.997894,1.532120,2.500469,0.121130,0.903487,0.002734,0.0682,0.008114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.223009,0.026946,38.294309,0.320930,1.940409,0.017132,0.900390,0.000849,0.0784,0.003021
1,classwise,7.665144,0.045728,38.259073,1.171264,354.400610,2.023354,0.946082,0.000518,0.0547,0.001744
2,exact_coverage_classwise,6.379476,0.036736,41.728767,1.626773,99.981451,0.651829,0.899728,0.000598,0.1198,0.002257
3,cluster_random,4.871419,0.087259,34.997894,1.532120,2.500469,0.121130,0.903487,0.002734,0.0682,0.008114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.223009,0.026946,38.294309,0.320930,1.940409,0.017132,0.900390,0.000849,0.0784,0.003021
1,classwise,7.665144,0.045728,38.259073,1.171264,354.400610,2.023354,0.946082,0.000518,0.0547,0.001744
2,exact_coverage_classwise,6.379476,0.036736,41.728767,1.626773,99.981451,0.651829,0.899728,0.000598,0.1198,0.002257
3,cluster_random,4.871419,0.087259,34.997894,1.532120,2.500469,0.121130,0.903487,0.002734,0.0682,0.008114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.223009,0.026946,38.294309,0.320930,1.940409,0.017132,0.900390,0.000849,0.0784,0.003021
1,classwise,7.665144,0.045728,38.259073,1.171264,354.400610,2.023354,0.946082,0.000518,0.0547,0.001744
2,exact_coverage_classwise,6.379476,0.036736,41.728767,1.626773,99.981451,0.651829,0.899728,0.000598,0.1198,0.002257
3,cluster_random,4.871419,0.087259,34.997894,1.532120,2.500469,0.121130,0.903487,0.002734,0.0682,0.008114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.560593,0.015334,21.132209,0.125715,25.928972,0.334066,0.900216,0.000964,0.0213,0.000401
1,classwise,7.634051,0.023135,37.179353,1.942818,394.186939,1.909254,0.946557,0.000868,0.0548,0.002440
2,exact_coverage_classwise,6.237662,0.040271,40.414106,1.712896,144.463966,0.602221,0.900927,0.000715,0.1160,0.002739
3,cluster_random,2.962995,0.086207,20.778567,0.707501,29.590335,1.459991,0.904302,0.003109,0.0202,0.002116

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.560593,0.015334,21.132209,0.125715,25.928972,0.334066,0.900216,0.000964,0.0213,0.000401
1,classwise,7.634051,0.023135,37.179353,1.942818,394.186939,1.909254,0.946557,0.000868,0.0548,0.002440
2,exact_coverage_classwise,6.237662,0.040271,40.414106,1.712896,144.463966,0.602221,0.900927,0.000715,0.1160,0.002739
3,cluster_random,2.962995,0.086207,20.778567,0.707501,29.590335,1.459991,0.904302,0.003109,0.0202,0.002116

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.560593,0.015334,21.132209,0.125715,25.928972,0.334066,0.900216,0.000964,0.0213,0.000401
1,classwise,7.634051,0.023135,37.179353,1.942818,394.186939,1.909254,0.946557,0.000868,0.0548,0.002440
2,exact_coverage_classwise,6.237662,0.040271,40.414106,1.712896,144.463966,0.602221,0.900927,0.000715,0.1160,0.002739
3,cluster_random,2.962995,0.086207,20.778567,0.707501,29.590335,1.459991,0.904302,0.003109,0.0202,0.002116

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.560593,0.015334,21.132209,0.125715,25.928972,0.334066,0.900216,0.000964,0.0213,0.000401
1,classwise,7.634051,0.023135,37.179353,1.942818,394.186939,1.909254,0.946557,0.000868,0.0548,0.002440
2,exact_coverage_classwise,6.237662,0.040271,40.414106,1.712896,144.463966,0.602221,0.900927,0.000715,0.1160,0.002739
3,cluster_random,2.962995,0.086207,20.778567,0.707501,29.590335,1.459991,0.904302,0.003109,0.0202,0.002116

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.022090,0.007071,25.111260,0.112823,5.161310,0.018058,0.900999,0.000676,0.0284,0.000429
1,classwise,7.681054,0.051617,38.346412,1.754499,361.878919,1.906141,0.945921,0.000715,0.0564,0.002250
2,exact_coverage_classwise,6.275739,0.043626,41.844070,2.013668,108.051240,0.879088,0.900623,0.000853,0.1154,0.003073
3,cluster_random,3.094981,0.041255,22.642816,0.724716,7.724640,0.984096,0.903250,0.001972,0.0219,0.001100

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.022090,0.007071,25.111260,0.112823,5.161310,0.018058,0.900999,0.000676,0.0284,0.000429
1,classwise,7.681054,0.051617,38.346412,1.754499,361.878919,1.906141,0.945921,0.000715,0.0564,0.002250
2,exact_coverage_classwise,6.275739,0.043626,41.844070,2.013668,108.051240,0.879088,0.900623,0.000853,0.1154,0.003073
3,cluster_random,3.094981,0.041255,22.642816,0.724716,7.724640,0.984096,0.903250,0.001972,0.0219,0.001100

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.022090,0.007071,25.111260,0.112823,5.161310,0.018058,0.900999,0.000676,0.0284,0.000429
1,classwise,7.681054,0.051617,38.346412,1.754499,361.878919,1.906141,0.945921,0.000715,0.0564,0.002250
2,exact_coverage_classwise,6.275739,0.043626,41.844070,2.013668,108.051240,0.879088,0.900623,0.000853,0.1154,0.003073
3,cluster_random,3.094981,0.041255,22.642816,0.724716,7.724640,0.984096,0.903250,0.001972,0.0219,0.001100

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.022090,0.007071,25.111260,0.112823,5.161310,0.018058,0.900999,0.000676,0.0284,0.000429
1,classwise,7.681054,0.051617,38.346412,1.754499,361.878919,1.906141,0.945921,0.000715,0.0564,0.002250
2,exact_coverage_classwise,6.275739,0.043626,41.844070,2.013668,108.051240,0.879088,0.900623,0.000853,0.1154,0.003073
3,cluster_random,3.094981,0.041255,22.642816,0.724716,7.724640,0.984096,0.903250,0.001972,0.0219,0.001100

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.991794,0.062632,12.098017,0.661933,8.069700,0.242667,0.900717,0.002582,0.041,0.009945
1,classwise,7.559482,0.131528,20.308118,1.912127,47.159469,0.566291,0.945045,0.001994,0.054,0.008025
2,exact_coverage_classwise,6.397871,0.116683,28.604453,1.507737,24.092431,0.421477,0.900669,0.001641,0.118,0.007975
3,cluster_random,4.190073,0.053389,15.083733,1.612104,8.891490,0.462414,0.899069,0.003287,0.057,0.010203

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.991794,0.062632,12.098017,0.661933,8.069700,0.242667,0.900717,0.002582,0.041,0.009945
1,classwise,7.559482,0.131528,20.308118,1.912127,47.159469,0.566291,0.945045,0.001994,0.054,0.008025
2,exact_coverage_classwise,6.397871,0.116683,28.604453,1.507737,24.092431,0.421477,0.900669,0.001641,0.118,0.007975
3,cluster_random,4.190073,0.053389,15.083733,1.612104,8.891490,0.462414,0.899069,0.003287,0.057,0.010203

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.991794,0.062632,12.098017,0.661933,8.069700,0.242667,0.900717,0.002582,0.041,0.009945
1,classwise,7.559482,0.131528,20.308118,1.912127,47.159469,0.566291,0.945045,0.001994,0.054,0.008025
2,exact_coverage_classwise,6.397871,0.116683,28.604453,1.507737,24.092431,0.421477,0.900669,0.001641,0.118,0.007975
3,cluster_random,4.190073,0.053389,15.083733,1.612104,8.891490,0.462414,0.899069,0.003287,0.057,0.010203

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.991794,0.062632,12.098017,0.661933,8.069700,0.242667,0.900717,0.002582,0.041,0.009945
1,classwise,7.559482,0.131528,20.308118,1.912127,47.159469,0.566291,0.945045,0.001994,0.054,0.008025
2,exact_coverage_classwise,6.397871,0.116683,28.604453,1.507737,24.092431,0.421477,0.900669,0.001641,0.118,0.007975
3,cluster_random,4.190073,0.053389,15.083733,1.612104,8.891490,0.462414,0.899069,0.003287,0.057,0.010203

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.748099,0.050672,13.894415,0.603704,11.225545,0.326769,0.900997,0.002389,0.033,0.004909
1,classwise,7.495067,0.133726,21.949424,1.969486,49.383997,0.521603,0.946772,0.001657,0.051,0.006237
2,exact_coverage_classwise,6.456921,0.132069,31.431830,2.647375,26.740914,0.398491,0.899824,0.002024,0.120,0.007616
3,cluster_random,4.002394,0.066151,15.327333,0.935655,11.914952,0.487925,0.898421,0.002857,0.040,0.005292

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.748099,0.050672,13.894415,0.603704,11.225545,0.326769,0.900997,0.002389,0.033,0.004909
1,classwise,7.495067,0.133726,21.949424,1.969486,49.383997,0.521603,0.946772,0.001657,0.051,0.006237
2,exact_coverage_classwise,6.456921,0.132069,31.431830,2.647375,26.740914,0.398491,0.899824,0.002024,0.120,0.007616
3,cluster_random,4.002394,0.066151,15.327333,0.935655,11.914952,0.487925,0.898421,0.002857,0.040,0.005292

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.748099,0.050672,13.894415,0.603704,11.225545,0.326769,0.900997,0.002389,0.033,0.004909
1,classwise,7.495067,0.133726,21.949424,1.969486,49.383997,0.521603,0.946772,0.001657,0.051,0.006237
2,exact_coverage_classwise,6.456921,0.132069,31.431830,2.647375,26.740914,0.398491,0.899824,0.002024,0.120,0.007616
3,cluster_random,4.002394,0.066151,15.327333,0.935655,11.914952,0.487925,0.898421,0.002857,0.040,0.005292

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.748099,0.050672,13.894415,0.603704,11.225545,0.326769,0.900997,0.002389,0.033,0.004909
1,classwise,7.495067,0.133726,21.949424,1.969486,49.383997,0.521603,0.946772,0.001657,0.051,0.006237
2,exact_coverage_classwise,6.456921,0.132069,31.431830,2.647375,26.740914,0.398491,0.899824,0.002024,0.120,0.007616
3,cluster_random,4.002394,0.066151,15.327333,0.935655,11.914952,0.487925,0.898421,0.002857,0.040,0.005292

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.740738,0.070109,14.064919,0.591192,8.597710,0.262783,0.903528,0.002335,0.062,0.010564
1,classwise,7.519487,0.109775,22.177778,1.879422,47.516069,0.693719,0.946024,0.001874,0.046,0.007376
2,exact_coverage_classwise,6.570705,0.169342,31.502707,2.629987,24.722245,0.495500,0.899762,0.002542,0.118,0.007589
3,cluster_random,4.898189,0.086024,15.371095,1.342234,9.511562,0.503472,0.903566,0.003484,0.069,0.013524

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.740738,0.070109,14.064919,0.591192,8.597710,0.262783,0.903528,0.002335,0.062,0.010564
1,classwise,7.519487,0.109775,22.177778,1.879422,47.516069,0.693719,0.946024,0.001874,0.046,0.007376
2,exact_coverage_classwise,6.570705,0.169342,31.502707,2.629987,24.722245,0.495500,0.899762,0.002542,0.118,0.007589
3,cluster_random,4.898189,0.086024,15.371095,1.342234,9.511562,0.503472,0.903566,0.003484,0.069,0.013524

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.740738,0.070109,14.064919,0.591192,8.597710,0.262783,0.903528,0.002335,0.062,0.010564
1,classwise,7.519487,0.109775,22.177778,1.879422,47.516069,0.693719,0.946024,0.001874,0.046,0.007376
2,exact_coverage_classwise,6.570705,0.169342,31.502707,2.629987,24.722245,0.495500,0.899762,0.002542,0.118,0.007589
3,cluster_random,4.898189,0.086024,15.371095,1.342234,9.511562,0.503472,0.903566,0.003484,0.069,0.013524

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.740738,0.070109,14.064919,0.591192,8.597710,0.262783,0.903528,0.002335,0.062,0.010564
1,classwise,7.519487,0.109775,22.177778,1.879422,47.516069,0.693719,0.946024,0.001874,0.046,0.007376
2,exact_coverage_classwise,6.570705,0.169342,31.502707,2.629987,24.722245,0.495500,0.899762,0.002542,0.118,0.007589
3,cluster_random,4.898189,0.086024,15.371095,1.342234,9.511562,0.503472,0.903566,0.003484,0.069,0.013524

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.539968,0.040831,21.593402,0.293917,6.937257,0.077179,0.900641,0.001260,0.066575,0.004083
1,classwise,7.617882,0.054526,34.904122,2.151995,136.462855,1.651122,0.944868,0.001324,0.054247,0.003483
2,exact_coverage_classwise,6.310241,0.079760,40.214168,2.070136,44.500889,0.388295,0.899440,0.001255,0.112603,0.005319
3,cluster_random,4.493055,0.052020,22.878184,0.802514,7.118502,0.129118,0.900720,0.001632,0.064110,0.004827

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.539968,0.040831,21.593402,0.293917,6.937257,0.077179,0.900641,0.001260,0.066575,0.004083
1,classwise,7.617882,0.054526,34.904122,2.151995,136.462855,1.651122,0.944868,0.001324,0.054247,0.003483
2,exact_coverage_classwise,6.310241,0.079760,40.214168,2.070136,44.500889,0.388295,0.899440,0.001255,0.112603,0.005319
3,cluster_random,4.493055,0.052020,22.878184,0.802514,7.118502,0.129118,0.900720,0.001632,0.064110,0.004827

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.539968,0.040831,21.593402,0.293917,6.937257,0.077179,0.900641,0.001260,0.066575,0.004083
1,classwise,7.617882,0.054526,34.904122,2.151995,136.462855,1.651122,0.944868,0.001324,0.054247,0.003483
2,exact_coverage_classwise,6.310241,0.079760,40.214168,2.070136,44.500889,0.388295,0.899440,0.001255,0.112603,0.005319
3,cluster_random,4.493055,0.052020,22.878184,0.802514,7.118502,0.129118,0.900720,0.001632,0.064110,0.004827

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.539968,0.040831,21.593402,0.293917,6.937257,0.077179,0.900641,0.001260,0.066575,0.004083
1,classwise,7.617882,0.054526,34.904122,2.151995,136.462855,1.651122,0.944868,0.001324,0.054247,0.003483
2,exact_coverage_classwise,6.310241,0.079760,40.214168,2.070136,44.500889,0.388295,0.899440,0.001255,0.112603,0.005319
3,cluster_random,4.493055,0.052020,22.878184,0.802514,7.118502,0.129118,0.900720,0.001632,0.064110,0.004827

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.274661,0.017758,17.908601,0.213722,10.829566,0.112739,0.900707,0.001238,0.028219,0.002686
1,classwise,7.602339,0.079425,32.084500,1.477303,140.498516,1.652093,0.945362,0.001364,0.052877,0.003914
2,exact_coverage_classwise,6.322595,0.120599,35.858269,1.929318,49.168157,0.395703,0.900172,0.001719,0.116438,0.007334
3,cluster_random,3.489825,0.061225,19.807614,1.096423,10.917162,0.268882,0.897820,0.002863,0.036164,0.004789

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.274661,0.017758,17.908601,0.213722,10.829566,0.112739,0.900707,0.001238,0.028219,0.002686
1,classwise,7.602339,0.079425,32.084500,1.477303,140.498516,1.652093,0.945362,0.001364,0.052877,0.003914
2,exact_coverage_classwise,6.322595,0.120599,35.858269,1.929318,49.168157,0.395703,0.900172,0.001719,0.116438,0.007334
3,cluster_random,3.489825,0.061225,19.807614,1.096423,10.917162,0.268882,0.897820,0.002863,0.036164,0.004789

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.274661,0.017758,17.908601,0.213722,10.829566,0.112739,0.900707,0.001238,0.028219,0.002686
1,classwise,7.602339,0.079425,32.084500,1.477303,140.498516,1.652093,0.945362,0.001364,0.052877,0.003914
2,exact_coverage_classwise,6.322595,0.120599,35.858269,1.929318,49.168157,0.395703,0.900172,0.001719,0.116438,0.007334
3,cluster_random,3.489825,0.061225,19.807614,1.096423,10.917162,0.268882,0.897820,0.002863,0.036164,0.004789

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.274661,0.017758,17.908601,0.213722,10.829566,0.112739,0.900707,0.001238,0.028219,0.002686
1,classwise,7.602339,0.079425,32.084500,1.477303,140.498516,1.652093,0.945362,0.001364,0.052877,0.003914
2,exact_coverage_classwise,6.322595,0.120599,35.858269,1.929318,49.168157,0.395703,0.900172,0.001719,0.116438,0.007334
3,cluster_random,3.489825,0.061225,19.807614,1.096423,10.917162,0.268882,0.897820,0.002863,0.036164,0.004789

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.834070,0.004756,20.223127,0.224620,7.896427,0.043998,0.899286,0.000923,0.043288,0.002318
1,classwise,7.571418,0.056852,32.124852,1.461276,138.860085,1.673153,0.944816,0.001440,0.051507,0.004867
2,exact_coverage_classwise,6.347706,0.121688,35.669236,1.900504,47.266030,0.416994,0.899749,0.001515,0.117260,0.006831
3,cluster_random,3.934281,0.059633,21.375731,1.005539,8.008258,0.118351,0.897750,0.002241,0.043836,0.005270

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.834070,0.004756,20.223127,0.224620,7.896427,0.043998,0.899286,0.000923,0.043288,0.002318
1,classwise,7.571418,0.056852,32.124852,1.461276,138.860085,1.673153,0.944816,0.001440,0.051507,0.004867
2,exact_coverage_classwise,6.347706,0.121688,35.669236,1.900504,47.266030,0.416994,0.899749,0.001515,0.117260,0.006831
3,cluster_random,3.934281,0.059633,21.375731,1.005539,8.008258,0.118351,0.897750,0.002241,0.043836,0.005270

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.834070,0.004756,20.223127,0.224620,7.896427,0.043998,0.899286,0.000923,0.043288,0.002318
1,classwise,7.571418,0.056852,32.124852,1.461276,138.860085,1.673153,0.944816,0.001440,0.051507,0.004867
2,exact_coverage_classwise,6.347706,0.121688,35.669236,1.900504,47.266030,0.416994,0.899749,0.001515,0.117260,0.006831
3,cluster_random,3.934281,0.059633,21.375731,1.005539,8.008258,0.118351,0.897750,0.002241,0.043836,0.005270

.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.834070,0.004756,20.223127,0.224620,7.896427,0.043998,0.899286,0.000923,0.043288,0.002318
1,classwise,7.571418,0.056852,32.124852,1.461276,138.860085,1.673153,0.944816,0.001440,0.051507,0.004867
2,exact_coverage_classwise,6.347706,0.121688,35.669236,1.900504,47.266030,0.416994,0.899749,0.001515,0.117260,0.006831
3,cluster_random,3.934281,0.059633,21.375731,1.005539,8.008258,0.118351,0.897750,0.002241,0.043836,0.005270

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.015272,0.087431,46.844151,0.670852,3.146679,0.038869,0.899139,0.001214,0.200790,0.005058
1,classwise,8.731317,0.023367,23.349363,2.361713,469.440028,1.800960,0.931566,0.000758,0.013586,0.001911
2,exact_coverage_classwise,6.829743,0.589616,36.787848,3.430023,292.508120,5.909465,0.898528,0.001230,0.104107,0.017931
3,cluster_random,6.871503,0.162904,47.027582,1.299771,3.104652,0.068734,0.886143,0.002198,0.194155,0.006752

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.015272,0.087431,46.844151,0.670852,3.146679,0.038869,0.899139,0.001214,0.200790,0.005058
1,classwise,8.731317,0.023367,23.349363,2.361713,469.440028,1.800960,0.931566,0.000758,0.013586,0.001911
2,exact_coverage_classwise,6.829743,0.589616,36.787848,3.430023,292.508120,5.909465,0.898528,0.001230,0.104107,0.017931
3,cluster_random,6.871503,0.162904,47.027582,1.299771,3.104652,0.068734,0.886143,0.002198,0.194155,0.006752

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.015272,0.087431,46.844151,0.670852,3.146679,0.038869,0.899139,0.001214,0.200790,0.005058
1,classwise,8.731317,0.023367,23.349363,2.361713,469.440028,1.800960,0.931566,0.000758,0.013586,0.001911
2,exact_coverage_classwise,6.829743,0.589616,36.787848,3.430023,292.508120,5.909465,0.898528,0.001230,0.104107,0.017931
3,cluster_random,6.871503,0.162904,47.027582,1.299771,3.104652,0.068734,0.886143,0.002198,0.194155,0.006752

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.015272,0.087431,46.844151,0.670852,3.146679,0.038869,0.899139,0.001214,0.200790,0.005058
1,classwise,8.731317,0.023367,23.349363,2.361713,469.440028,1.800960,0.931566,0.000758,0.013586,0.001911
2,exact_coverage_classwise,6.829743,0.589616,36.787848,3.430023,292.508120,5.909465,0.898528,0.001230,0.104107,0.017931
3,cluster_random,6.871503,0.162904,47.027582,1.299771,3.104652,0.068734,0.886143,0.002198,0.194155,0.006752

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.253885,0.075680,61.250285,0.416401,8.283288,0.105972,0.898767,0.001662,0.100158,0.004258
1,classwise,8.686154,0.020417,25.951450,1.838893,472.763706,1.767429,0.933501,0.001148,0.012954,0.000969
2,exact_coverage_classwise,6.216109,0.062698,32.840223,2.013749,302.045693,1.222591,0.901024,0.000727,0.089889,0.003332
3,cluster_random,4.270996,0.078391,60.280680,0.653222,8.103065,0.098680,0.892965,0.001557,0.095577,0.004235

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.253885,0.075680,61.250285,0.416401,8.283288,0.105972,0.898767,0.001662,0.100158,0.004258
1,classwise,8.686154,0.020417,25.951450,1.838893,472.763706,1.767429,0.933501,0.001148,0.012954,0.000969
2,exact_coverage_classwise,6.216109,0.062698,32.840223,2.013749,302.045693,1.222591,0.901024,0.000727,0.089889,0.003332
3,cluster_random,4.270996,0.078391,60.280680,0.653222,8.103065,0.098680,0.892965,0.001557,0.095577,0.004235

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.253885,0.075680,61.250285,0.416401,8.283288,0.105972,0.898767,0.001662,0.100158,0.004258
1,classwise,8.686154,0.020417,25.951450,1.838893,472.763706,1.767429,0.933501,0.001148,0.012954,0.000969
2,exact_coverage_classwise,6.216109,0.062698,32.840223,2.013749,302.045693,1.222591,0.901024,0.000727,0.089889,0.003332
3,cluster_random,4.270996,0.078391,60.280680,0.653222,8.103065,0.098680,0.892965,0.001557,0.095577,0.004235

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.253885,0.075680,61.250285,0.416401,8.283288,0.105972,0.898767,0.001662,0.100158,0.004258
1,classwise,8.686154,0.020417,25.951450,1.838893,472.763706,1.767429,0.933501,0.001148,0.012954,0.000969
2,exact_coverage_classwise,6.216109,0.062698,32.840223,2.013749,302.045693,1.222591,0.901024,0.000727,0.089889,0.003332
3,cluster_random,4.270996,0.078391,60.280680,0.653222,8.103065,0.098680,0.892965,0.001557,0.095577,0.004235

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.066155,0.079256,58.974116,0.632407,5.130720,0.043069,0.898280,0.001743,0.135387,0.005311
1,classwise,8.717976,0.010423,25.302377,2.156119,473.752873,1.898523,0.933670,0.000902,0.012954,0.000859
2,exact_coverage_classwise,6.250757,0.058698,32.762369,2.163604,303.327690,1.230016,0.901197,0.000635,0.090837,0.003375
3,cluster_random,5.039199,0.088583,56.109144,0.926221,5.007765,0.034509,0.889918,0.001372,0.128910,0.005568

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.066155,0.079256,58.974116,0.632407,5.130720,0.043069,0.898280,0.001743,0.135387,0.005311
1,classwise,8.717976,0.010423,25.302377,2.156119,473.752873,1.898523,0.933670,0.000902,0.012954,0.000859
2,exact_coverage_classwise,6.250757,0.058698,32.762369,2.163604,303.327690,1.230016,0.901197,0.000635,0.090837,0.003375
3,cluster_random,5.039199,0.088583,56.109144,0.926221,5.007765,0.034509,0.889918,0.001372,0.128910,0.005568

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.066155,0.079256,58.974116,0.632407,5.130720,0.043069,0.898280,0.001743,0.135387,0.005311
1,classwise,8.717976,0.010423,25.302377,2.156119,473.752873,1.898523,0.933670,0.000902,0.012954,0.000859
2,exact_coverage_classwise,6.250757,0.058698,32.762369,2.163604,303.327690,1.230016,0.901197,0.000635,0.090837,0.003375
3,cluster_random,5.039199,0.088583,56.109144,0.926221,5.007765,0.034509,0.889918,0.001372,0.128910,0.005568

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.066155,0.079256,58.974116,0.632407,5.130720,0.043069,0.898280,0.001743,0.135387,0.005311
1,classwise,8.717976,0.010423,25.302377,2.156119,473.752873,1.898523,0.933670,0.000902,0.012954,0.000859
2,exact_coverage_classwise,6.250757,0.058698,32.762369,2.163604,303.327690,1.230016,0.901197,0.000635,0.090837,0.003375
3,cluster_random,5.039199,0.088583,56.109144,0.926221,5.007765,0.034509,0.889918,0.001372,0.128910,0.005568

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242140,0.019744,38.588681,0.253128,1.925405,0.012752,0.899721,0.000633,0.0809,0.002418
1,classwise,5.351844,0.035587,28.072956,1.528633,22.995326,0.866654,0.923408,0.000471,0.0456,0.002290
2,exact_coverage_classwise,4.921403,0.041673,29.472191,1.304616,11.160402,0.287338,0.899779,0.000515,0.0783,0.002409
3,cluster_random,3.910072,0.047958,26.188130,2.078601,2.691425,0.101411,0.902816,0.002088,0.0418,0.005132

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242140,0.019744,38.588681,0.253128,1.925405,0.012752,0.899721,0.000633,0.0809,0.002418
1,classwise,5.351844,0.035587,28.072956,1.528633,22.995326,0.866654,0.923408,0.000471,0.0456,0.002290
2,exact_coverage_classwise,4.921403,0.041673,29.472191,1.304616,11.160402,0.287338,0.899779,0.000515,0.0783,0.002409
3,cluster_random,3.910072,0.047958,26.188130,2.078601,2.691425,0.101411,0.902816,0.002088,0.0418,0.005132

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242140,0.019744,38.588681,0.253128,1.925405,0.012752,0.899721,0.000633,0.0809,0.002418
1,classwise,5.351844,0.035587,28.072956,1.528633,22.995326,0.866654,0.923408,0.000471,0.0456,0.002290
2,exact_coverage_classwise,4.921403,0.041673,29.472191,1.304616,11.160402,0.287338,0.899779,0.000515,0.0783,0.002409
3,cluster_random,3.910072,0.047958,26.188130,2.078601,2.691425,0.101411,0.902816,0.002088,0.0418,0.005132

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242140,0.019744,38.588681,0.253128,1.925405,0.012752,0.899721,0.000633,0.0809,0.002418
1,classwise,5.351844,0.035587,28.072956,1.528633,22.995326,0.866654,0.923408,0.000471,0.0456,0.002290
2,exact_coverage_classwise,4.921403,0.041673,29.472191,1.304616,11.160402,0.287338,0.899779,0.000515,0.0783,0.002409
3,cluster_random,3.910072,0.047958,26.188130,2.078601,2.691425,0.101411,0.902816,0.002088,0.0418,0.005132

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.579062,0.006664,21.130067,0.099829,25.836745,0.147786,0.899823,0.000456,0.0217,0.000145
1,classwise,5.454779,0.038000,30.687932,1.363243,76.892528,0.843063,0.922921,0.000485,0.0455,0.001423
2,exact_coverage_classwise,4.897756,0.033703,31.125327,1.640377,51.769381,0.303526,0.900113,0.000388,0.0752,0.002493
3,cluster_random,2.618204,0.028570,18.718945,1.092662,26.988619,0.709796,0.899518,0.001936,0.0163,0.001908

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.579062,0.006664,21.130067,0.099829,25.836745,0.147786,0.899823,0.000456,0.0217,0.000145
1,classwise,5.454779,0.038000,30.687932,1.363243,76.892528,0.843063,0.922921,0.000485,0.0455,0.001423
2,exact_coverage_classwise,4.897756,0.033703,31.125327,1.640377,51.769381,0.303526,0.900113,0.000388,0.0752,0.002493
3,cluster_random,2.618204,0.028570,18.718945,1.092662,26.988619,0.709796,0.899518,0.001936,0.0163,0.001908

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.579062,0.006664,21.130067,0.099829,25.836745,0.147786,0.899823,0.000456,0.0217,0.000145
1,classwise,5.454779,0.038000,30.687932,1.363243,76.892528,0.843063,0.922921,0.000485,0.0455,0.001423
2,exact_coverage_classwise,4.897756,0.033703,31.125327,1.640377,51.769381,0.303526,0.900113,0.000388,0.0752,0.002493
3,cluster_random,2.618204,0.028570,18.718945,1.092662,26.988619,0.709796,0.899518,0.001936,0.0163,0.001908

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.579062,0.006664,21.130067,0.099829,25.836745,0.147786,0.899823,0.000456,0.0217,0.000145
1,classwise,5.454779,0.038000,30.687932,1.363243,76.892528,0.843063,0.922921,0.000485,0.0455,0.001423
2,exact_coverage_classwise,4.897756,0.033703,31.125327,1.640377,51.769381,0.303526,0.900113,0.000388,0.0752,0.002493
3,cluster_random,2.618204,0.028570,18.718945,1.092662,26.988619,0.709796,0.899518,0.001936,0.0163,0.001908

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.002839,0.005155,24.895577,0.107940,5.120346,0.014104,0.899332,0.000551,0.0289,0.000411
1,classwise,5.568841,0.048260,30.413912,1.646779,34.228667,0.981603,0.925940,0.000640,0.0442,0.002068
2,exact_coverage_classwise,4.937327,0.038749,33.579567,1.872578,17.149374,0.397443,0.899616,0.000417,0.0774,0.001945
3,cluster_random,2.914079,0.034705,20.420417,1.121158,6.647010,0.594168,0.900730,0.001944,0.0188,0.001821

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.002839,0.005155,24.895577,0.107940,5.120346,0.014104,0.899332,0.000551,0.0289,0.000411
1,classwise,5.568841,0.048260,30.413912,1.646779,34.228667,0.981603,0.925940,0.000640,0.0442,0.002068
2,exact_coverage_classwise,4.937327,0.038749,33.579567,1.872578,17.149374,0.397443,0.899616,0.000417,0.0774,0.001945
3,cluster_random,2.914079,0.034705,20.420417,1.121158,6.647010,0.594168,0.900730,0.001944,0.0188,0.001821

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.002839,0.005155,24.895577,0.107940,5.120346,0.014104,0.899332,0.000551,0.0289,0.000411
1,classwise,5.568841,0.048260,30.413912,1.646779,34.228667,0.981603,0.925940,0.000640,0.0442,0.002068
2,exact_coverage_classwise,4.937327,0.038749,33.579567,1.872578,17.149374,0.397443,0.899616,0.000417,0.0774,0.001945
3,cluster_random,2.914079,0.034705,20.420417,1.121158,6.647010,0.594168,0.900730,0.001944,0.0188,0.001821

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.002839,0.005155,24.895577,0.107940,5.120346,0.014104,0.899332,0.000551,0.0289,0.000411
1,classwise,5.568841,0.048260,30.413912,1.646779,34.228667,0.981603,0.925940,0.000640,0.0442,0.002068
2,exact_coverage_classwise,4.937327,0.038749,33.579567,1.872578,17.149374,0.397443,0.899616,0.000417,0.0774,0.001945
3,cluster_random,2.914079,0.034705,20.420417,1.121158,6.647010,0.594168,0.900730,0.001944,0.0188,0.001821

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.034722,0.043785,12.983755,0.568526,7.855539,0.171175,0.898679,0.001844,0.046,0.008149
1,classwise,5.596848,0.082472,18.950410,1.208061,19.301886,0.489866,0.922043,0.001315,0.051,0.006701
2,exact_coverage_classwise,5.142764,0.084491,21.664556,0.907688,14.261432,0.316847,0.898914,0.001289,0.090,0.009899
3,cluster_random,3.632336,0.102766,12.697992,0.820957,8.895064,0.347512,0.903107,0.002977,0.023,0.007490

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.034722,0.043785,12.983755,0.568526,7.855539,0.171175,0.898679,0.001844,0.046,0.008149
1,classwise,5.596848,0.082472,18.950410,1.208061,19.301886,0.489866,0.922043,0.001315,0.051,0.006701
2,exact_coverage_classwise,5.142764,0.084491,21.664556,0.907688,14.261432,0.316847,0.898914,0.001289,0.090,0.009899
3,cluster_random,3.632336,0.102766,12.697992,0.820957,8.895064,0.347512,0.903107,0.002977,0.023,0.007490

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.034722,0.043785,12.983755,0.568526,7.855539,0.171175,0.898679,0.001844,0.046,0.008149
1,classwise,5.596848,0.082472,18.950410,1.208061,19.301886,0.489866,0.922043,0.001315,0.051,0.006701
2,exact_coverage_classwise,5.142764,0.084491,21.664556,0.907688,14.261432,0.316847,0.898914,0.001289,0.090,0.009899
3,cluster_random,3.632336,0.102766,12.697992,0.820957,8.895064,0.347512,0.903107,0.002977,0.023,0.007490

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.034722,0.043785,12.983755,0.568526,7.855539,0.171175,0.898679,0.001844,0.046,0.008149
1,classwise,5.596848,0.082472,18.950410,1.208061,19.301886,0.489866,0.922043,0.001315,0.051,0.006701
2,exact_coverage_classwise,5.142764,0.084491,21.664556,0.907688,14.261432,0.316847,0.898914,0.001289,0.090,0.009899
3,cluster_random,3.632336,0.102766,12.697992,0.820957,8.895064,0.347512,0.903107,0.002977,0.023,0.007490

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.733895,0.045679,13.744097,0.354649,10.834100,0.153694,0.898196,0.001283,0.039,0.002983
1,classwise,5.606724,0.073194,20.365403,1.353927,22.646911,0.465817,0.922304,0.001308,0.055,0.003536
2,exact_coverage_classwise,5.236817,0.119666,24.359697,1.356666,17.200168,0.348839,0.898507,0.001516,0.083,0.006641
3,cluster_random,3.609810,0.090039,13.351927,1.042160,12.104261,0.456551,0.904429,0.003152,0.028,0.008809

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.733895,0.045679,13.744097,0.354649,10.834100,0.153694,0.898196,0.001283,0.039,0.002983
1,classwise,5.606724,0.073194,20.365403,1.353927,22.646911,0.465817,0.922304,0.001308,0.055,0.003536
2,exact_coverage_classwise,5.236817,0.119666,24.359697,1.356666,17.200168,0.348839,0.898507,0.001516,0.083,0.006641
3,cluster_random,3.609810,0.090039,13.351927,1.042160,12.104261,0.456551,0.904429,0.003152,0.028,0.008809

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.733895,0.045679,13.744097,0.354649,10.834100,0.153694,0.898196,0.001283,0.039,0.002983
1,classwise,5.606724,0.073194,20.365403,1.353927,22.646911,0.465817,0.922304,0.001308,0.055,0.003536
2,exact_coverage_classwise,5.236817,0.119666,24.359697,1.356666,17.200168,0.348839,0.898507,0.001516,0.083,0.006641
3,cluster_random,3.609810,0.090039,13.351927,1.042160,12.104261,0.456551,0.904429,0.003152,0.028,0.008809

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.733895,0.045679,13.744097,0.354649,10.834100,0.153694,0.898196,0.001283,0.039,0.002983
1,classwise,5.606724,0.073194,20.365403,1.353927,22.646911,0.465817,0.922304,0.001308,0.055,0.003536
2,exact_coverage_classwise,5.236817,0.119666,24.359697,1.356666,17.200168,0.348839,0.898507,0.001516,0.083,0.006641
3,cluster_random,3.609810,0.090039,13.351927,1.042160,12.104261,0.456551,0.904429,0.003152,0.028,0.008809

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.802331,0.067221,14.824411,0.595375,8.334961,0.264027,0.901332,0.002234,0.076,0.010696
1,classwise,5.580447,0.110211,18.282706,1.479314,20.727804,0.648587,0.927489,0.001569,0.045,0.004743
2,exact_coverage_classwise,5.156352,0.109397,24.198815,1.630612,15.047004,0.428876,0.899704,0.001558,0.078,0.008695
3,cluster_random,4.546226,0.096520,17.570428,1.259491,8.672836,0.484433,0.899600,0.003694,0.066,0.014980

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.802331,0.067221,14.824411,0.595375,8.334961,0.264027,0.901332,0.002234,0.076,0.010696
1,classwise,5.580447,0.110211,18.282706,1.479314,20.727804,0.648587,0.927489,0.001569,0.045,0.004743
2,exact_coverage_classwise,5.156352,0.109397,24.198815,1.630612,15.047004,0.428876,0.899704,0.001558,0.078,0.008695
3,cluster_random,4.546226,0.096520,17.570428,1.259491,8.672836,0.484433,0.899600,0.003694,0.066,0.014980

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.802331,0.067221,14.824411,0.595375,8.334961,0.264027,0.901332,0.002234,0.076,0.010696
1,classwise,5.580447,0.110211,18.282706,1.479314,20.727804,0.648587,0.927489,0.001569,0.045,0.004743
2,exact_coverage_classwise,5.156352,0.109397,24.198815,1.630612,15.047004,0.428876,0.899704,0.001558,0.078,0.008695
3,cluster_random,4.546226,0.096520,17.570428,1.259491,8.672836,0.484433,0.899600,0.003694,0.066,0.014980

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.802331,0.067221,14.824411,0.595375,8.334961,0.264027,0.901332,0.002234,0.076,0.010696
1,classwise,5.580447,0.110211,18.282706,1.479314,20.727804,0.648587,0.927489,0.001569,0.045,0.004743
2,exact_coverage_classwise,5.156352,0.109397,24.198815,1.630612,15.047004,0.428876,0.899704,0.001558,0.078,0.008695
3,cluster_random,4.546226,0.096520,17.570428,1.259491,8.672836,0.484433,0.899600,0.003694,0.066,0.014980

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.541674,0.025486,21.633060,0.263461,6.923882,0.048799,0.900492,0.000798,0.066849,0.002634
1,classwise,5.425627,0.032237,26.258985,1.358941,18.015213,0.233711,0.923452,0.000823,0.043014,0.002358
2,exact_coverage_classwise,4.980768,0.047437,27.715232,1.017968,12.396252,0.142965,0.899939,0.000937,0.079726,0.003410
3,cluster_random,3.909844,0.081523,20.986968,1.359089,7.114558,0.145647,0.894724,0.002426,0.046575,0.005169

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.541674,0.025486,21.633060,0.263461,6.923882,0.048799,0.900492,0.000798,0.066849,0.002634
1,classwise,5.425627,0.032237,26.258985,1.358941,18.015213,0.233711,0.923452,0.000823,0.043014,0.002358
2,exact_coverage_classwise,4.980768,0.047437,27.715232,1.017968,12.396252,0.142965,0.899939,0.000937,0.079726,0.003410
3,cluster_random,3.909844,0.081523,20.986968,1.359089,7.114558,0.145647,0.894724,0.002426,0.046575,0.005169

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.541674,0.025486,21.633060,0.263461,6.923882,0.048799,0.900492,0.000798,0.066849,0.002634
1,classwise,5.425627,0.032237,26.258985,1.358941,18.015213,0.233711,0.923452,0.000823,0.043014,0.002358
2,exact_coverage_classwise,4.980768,0.047437,27.715232,1.017968,12.396252,0.142965,0.899939,0.000937,0.079726,0.003410
3,cluster_random,3.909844,0.081523,20.986968,1.359089,7.114558,0.145647,0.894724,0.002426,0.046575,0.005169

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.541674,0.025486,21.633060,0.263461,6.923882,0.048799,0.900492,0.000798,0.066849,0.002634
1,classwise,5.425627,0.032237,26.258985,1.358941,18.015213,0.233711,0.923452,0.000823,0.043014,0.002358
2,exact_coverage_classwise,4.980768,0.047437,27.715232,1.017968,12.396252,0.142965,0.899939,0.000937,0.079726,0.003410
3,cluster_random,3.909844,0.081523,20.986968,1.359089,7.114558,0.145647,0.894724,0.002426,0.046575,0.005169

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.285192,0.014402,17.793849,0.166431,10.859993,0.102585,0.900801,0.001148,0.028493,0.002299
1,classwise,5.405772,0.072604,26.047756,1.515578,23.499041,0.271947,0.923760,0.000730,0.042192,0.002956
2,exact_coverage_classwise,4.937768,0.071365,27.338701,1.682355,17.042996,0.180090,0.900076,0.001133,0.072329,0.004266
3,cluster_random,3.052464,0.037030,15.417303,0.484194,10.920591,0.243955,0.897251,0.002035,0.016986,0.002253

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.285192,0.014402,17.793849,0.166431,10.859993,0.102585,0.900801,0.001148,0.028493,0.002299
1,classwise,5.405772,0.072604,26.047756,1.515578,23.499041,0.271947,0.923760,0.000730,0.042192,0.002956
2,exact_coverage_classwise,4.937768,0.071365,27.338701,1.682355,17.042996,0.180090,0.900076,0.001133,0.072329,0.004266
3,cluster_random,3.052464,0.037030,15.417303,0.484194,10.920591,0.243955,0.897251,0.002035,0.016986,0.002253

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.285192,0.014402,17.793849,0.166431,10.859993,0.102585,0.900801,0.001148,0.028493,0.002299
1,classwise,5.405772,0.072604,26.047756,1.515578,23.499041,0.271947,0.923760,0.000730,0.042192,0.002956
2,exact_coverage_classwise,4.937768,0.071365,27.338701,1.682355,17.042996,0.180090,0.900076,0.001133,0.072329,0.004266
3,cluster_random,3.052464,0.037030,15.417303,0.484194,10.920591,0.243955,0.897251,0.002035,0.016986,0.002253

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.285192,0.014402,17.793849,0.166431,10.859993,0.102585,0.900801,0.001148,0.028493,0.002299
1,classwise,5.405772,0.072604,26.047756,1.515578,23.499041,0.271947,0.923760,0.000730,0.042192,0.002956
2,exact_coverage_classwise,4.937768,0.071365,27.338701,1.682355,17.042996,0.180090,0.900076,0.001133,0.072329,0.004266
3,cluster_random,3.052464,0.037030,15.417303,0.484194,10.920591,0.243955,0.897251,0.002035,0.016986,0.002253

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.863657,0.002829,19.813327,0.139193,7.943046,0.042746,0.900394,0.000908,0.039452,0.001698
1,classwise,5.469234,0.058504,25.949552,1.443175,21.320141,0.326023,0.925214,0.000631,0.041096,0.003148
2,exact_coverage_classwise,4.950414,0.069016,26.205758,1.769469,14.379434,0.164684,0.900128,0.001038,0.070411,0.004682
3,cluster_random,3.412354,0.038309,16.823011,1.159658,8.151959,0.174662,0.896920,0.002029,0.029315,0.003656

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.863657,0.002829,19.813327,0.139193,7.943046,0.042746,0.900394,0.000908,0.039452,0.001698
1,classwise,5.469234,0.058504,25.949552,1.443175,21.320141,0.326023,0.925214,0.000631,0.041096,0.003148
2,exact_coverage_classwise,4.950414,0.069016,26.205758,1.769469,14.379434,0.164684,0.900128,0.001038,0.070411,0.004682
3,cluster_random,3.412354,0.038309,16.823011,1.159658,8.151959,0.174662,0.896920,0.002029,0.029315,0.003656

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.863657,0.002829,19.813327,0.139193,7.943046,0.042746,0.900394,0.000908,0.039452,0.001698
1,classwise,5.469234,0.058504,25.949552,1.443175,21.320141,0.326023,0.925214,0.000631,0.041096,0.003148
2,exact_coverage_classwise,4.950414,0.069016,26.205758,1.769469,14.379434,0.164684,0.900128,0.001038,0.070411,0.004682
3,cluster_random,3.412354,0.038309,16.823011,1.159658,8.151959,0.174662,0.896920,0.002029,0.029315,0.003656

.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.863657,0.002829,19.813327,0.139193,7.943046,0.042746,0.900394,0.000908,0.039452,0.001698
1,classwise,5.469234,0.058504,25.949552,1.443175,21.320141,0.326023,0.925214,0.000631,0.041096,0.003148
2,exact_coverage_classwise,4.950414,0.069016,26.205758,1.769469,14.379434,0.164684,0.900128,0.001038,0.070411,0.004682
3,cluster_random,3.412354,0.038309,16.823011,1.159658,8.151959,0.174662,0.896920,0.002029,0.029315,0.003656

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.013092,0.054916,46.855327,0.592711,3.144770,0.024174,0.899156,0.000752,0.201896,0.003394
1,classwise,7.818879,0.021523,31.758727,2.106494,363.999650,1.449765,0.920161,0.000550,0.021011,0.002386
2,exact_coverage_classwise,6.014226,0.264507,37.886567,3.579713,187.747904,1.494598,0.898209,0.000980,0.102212,0.009266
3,cluster_random,6.412864,0.115882,46.462627,0.964505,3.442862,0.071570,0.892755,0.001658,0.177725,0.004564

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.013092,0.054916,46.855327,0.592711,3.144770,0.024174,0.899156,0.000752,0.201896,0.003394
1,classwise,7.818879,0.021523,31.758727,2.106494,363.999650,1.449765,0.920161,0.000550,0.021011,0.002386
2,exact_coverage_classwise,6.014226,0.264507,37.886567,3.579713,187.747904,1.494598,0.898209,0.000980,0.102212,0.009266
3,cluster_random,6.412864,0.115882,46.462627,0.964505,3.442862,0.071570,0.892755,0.001658,0.177725,0.004564

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.013092,0.054916,46.855327,0.592711,3.144770,0.024174,0.899156,0.000752,0.201896,0.003394
1,classwise,7.818879,0.021523,31.758727,2.106494,363.999650,1.449765,0.920161,0.000550,0.021011,0.002386
2,exact_coverage_classwise,6.014226,0.264507,37.886567,3.579713,187.747904,1.494598,0.898209,0.000980,0.102212,0.009266
3,cluster_random,6.412864,0.115882,46.462627,0.964505,3.442862,0.071570,0.892755,0.001658,0.177725,0.004564

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.013092,0.054916,46.855327,0.592711,3.144770,0.024174,0.899156,0.000752,0.201896,0.003394
1,classwise,7.818879,0.021523,31.758727,2.106494,363.999650,1.449765,0.920161,0.000550,0.021011,0.002386
2,exact_coverage_classwise,6.014226,0.264507,37.886567,3.579713,187.747904,1.494598,0.898209,0.000980,0.102212,0.009266
3,cluster_random,6.412864,0.115882,46.462627,0.964505,3.442862,0.071570,0.892755,0.001658,0.177725,0.004564

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.159961,0.053653,57.543882,0.433449,8.375728,0.070039,0.899902,0.001102,0.096524,0.002250
1,classwise,7.759054,0.021196,25.424009,2.046067,368.391984,1.402305,0.921396,0.000699,0.018799,0.001506
2,exact_coverage_classwise,5.808487,0.061969,35.298100,2.222727,191.163241,1.399390,0.899675,0.000802,0.102844,0.003107
3,cluster_random,4.143421,0.079174,60.550941,0.451936,8.332210,0.112080,0.896453,0.002097,0.090047,0.003725

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.159961,0.053653,57.543882,0.433449,8.375728,0.070039,0.899902,0.001102,0.096524,0.002250
1,classwise,7.759054,0.021196,25.424009,2.046067,368.391984,1.402305,0.921396,0.000699,0.018799,0.001506
2,exact_coverage_classwise,5.808487,0.061969,35.298100,2.222727,191.163241,1.399390,0.899675,0.000802,0.102844,0.003107
3,cluster_random,4.143421,0.079174,60.550941,0.451936,8.332210,0.112080,0.896453,0.002097,0.090047,0.003725

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.159961,0.053653,57.543882,0.433449,8.375728,0.070039,0.899902,0.001102,0.096524,0.002250
1,classwise,7.759054,0.021196,25.424009,2.046067,368.391984,1.402305,0.921396,0.000699,0.018799,0.001506
2,exact_coverage_classwise,5.808487,0.061969,35.298100,2.222727,191.163241,1.399390,0.899675,0.000802,0.102844,0.003107
3,cluster_random,4.143421,0.079174,60.550941,0.451936,8.332210,0.112080,0.896453,0.002097,0.090047,0.003725

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.159961,0.053653,57.543882,0.433449,8.375728,0.070039,0.899902,0.001102,0.096524,0.002250
1,classwise,7.759054,0.021196,25.424009,2.046067,368.391984,1.402305,0.921396,0.000699,0.018799,0.001506
2,exact_coverage_classwise,5.808487,0.061969,35.298100,2.222727,191.163241,1.399390,0.899675,0.000802,0.102844,0.003107
3,cluster_random,4.143421,0.079174,60.550941,0.451936,8.332210,0.112080,0.896453,0.002097,0.090047,0.003725

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.990115,0.049682,55.653438,0.449000,5.150563,0.029484,0.898890,0.001184,0.130490,0.002974
1,classwise,7.799607,0.019823,25.998071,1.967420,369.186434,1.456199,0.921288,0.000787,0.020537,0.001642
2,exact_coverage_classwise,5.838113,0.053656,35.656321,2.164279,192.279551,1.329087,0.899312,0.000713,0.105055,0.003008
3,cluster_random,4.892857,0.081258,57.616667,0.939359,5.168215,0.047643,0.895563,0.002374,0.125750,0.005140

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.990115,0.049682,55.653438,0.449000,5.150563,0.029484,0.898890,0.001184,0.130490,0.002974
1,classwise,7.799607,0.019823,25.998071,1.967420,369.186434,1.456199,0.921288,0.000787,0.020537,0.001642
2,exact_coverage_classwise,5.838113,0.053656,35.656321,2.164279,192.279551,1.329087,0.899312,0.000713,0.105055,0.003008
3,cluster_random,4.892857,0.081258,57.616667,0.939359,5.168215,0.047643,0.895563,0.002374,0.125750,0.005140

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.990115,0.049682,55.653438,0.449000,5.150563,0.029484,0.898890,0.001184,0.130490,0.002974
1,classwise,7.799607,0.019823,25.998071,1.967420,369.186434,1.456199,0.921288,0.000787,0.020537,0.001642
2,exact_coverage_classwise,5.838113,0.053656,35.656321,2.164279,192.279551,1.329087,0.899312,0.000713,0.105055,0.003008
3,cluster_random,4.892857,0.081258,57.616667,0.939359,5.168215,0.047643,0.895563,0.002374,0.125750,0.005140

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.990115,0.049682,55.653438,0.449000,5.150563,0.029484,0.898890,0.001184,0.130490,0.002974
1,classwise,7.799607,0.019823,25.998071,1.967420,369.186434,1.456199,0.921288,0.000787,0.020537,0.001642
2,exact_coverage_classwise,5.838113,0.053656,35.656321,2.164279,192.279551,1.329087,0.899312,0.000713,0.105055,0.003008
3,cluster_random,4.892857,0.081258,57.616667,0.939359,5.168215,0.047643,0.895563,0.002374,0.125750,0.005140

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.250223,0.012286,38.583880,0.136763,1.919477,0.008245,0.899439,0.000407,0.0821,0.001957
1,classwise,4.368803,0.036288,21.368351,0.931701,8.690074,0.168919,0.915885,0.000416,0.0315,0.002550
2,exact_coverage_classwise,4.150790,0.050971,23.774799,0.993428,5.953621,0.103586,0.899545,0.000409,0.0512,0.003098
3,cluster_random,3.506111,0.041403,20.184996,0.734359,2.647949,0.088670,0.901536,0.002095,0.0282,0.003370

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.250223,0.012286,38.583880,0.136763,1.919477,0.008245,0.899439,0.000407,0.0821,0.001957
1,classwise,4.368803,0.036288,21.368351,0.931701,8.690074,0.168919,0.915885,0.000416,0.0315,0.002550
2,exact_coverage_classwise,4.150790,0.050971,23.774799,0.993428,5.953621,0.103586,0.899545,0.000409,0.0512,0.003098
3,cluster_random,3.506111,0.041403,20.184996,0.734359,2.647949,0.088670,0.901536,0.002095,0.0282,0.003370

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.250223,0.012286,38.583880,0.136763,1.919477,0.008245,0.899439,0.000407,0.0821,0.001957
1,classwise,4.368803,0.036288,21.368351,0.931701,8.690074,0.168919,0.915885,0.000416,0.0315,0.002550
2,exact_coverage_classwise,4.150790,0.050971,23.774799,0.993428,5.953621,0.103586,0.899545,0.000409,0.0512,0.003098
3,cluster_random,3.506111,0.041403,20.184996,0.734359,2.647949,0.088670,0.901536,0.002095,0.0282,0.003370

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.250223,0.012286,38.583880,0.136763,1.919477,0.008245,0.899439,0.000407,0.0821,0.001957
1,classwise,4.368803,0.036288,21.368351,0.931701,8.690074,0.168919,0.915885,0.000416,0.0315,0.002550
2,exact_coverage_classwise,4.150790,0.050971,23.774799,0.993428,5.953621,0.103586,0.899545,0.000409,0.0512,0.003098
3,cluster_random,3.506111,0.041403,20.184996,0.734359,2.647949,0.088670,0.901536,0.002095,0.0282,0.003370

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.541452,0.006235,21.270378,0.073531,25.632269,0.160846,0.899402,0.000483,0.0213,0.000318
1,classwise,4.464821,0.021889,24.553002,0.879332,51.700152,0.509151,0.916161,0.000623,0.0326,0.001298
2,exact_coverage_classwise,4.217261,0.019215,26.636954,0.809095,40.612052,0.359333,0.899501,0.000577,0.0544,0.001505
3,cluster_random,2.558991,0.081864,16.355646,0.815082,27.944118,0.997261,0.900936,0.002453,0.0108,0.001271

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.541452,0.006235,21.270378,0.073531,25.632269,0.160846,0.899402,0.000483,0.0213,0.000318
1,classwise,4.464821,0.021889,24.553002,0.879332,51.700152,0.509151,0.916161,0.000623,0.0326,0.001298
2,exact_coverage_classwise,4.217261,0.019215,26.636954,0.809095,40.612052,0.359333,0.899501,0.000577,0.0544,0.001505
3,cluster_random,2.558991,0.081864,16.355646,0.815082,27.944118,0.997261,0.900936,0.002453,0.0108,0.001271

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.541452,0.006235,21.270378,0.073531,25.632269,0.160846,0.899402,0.000483,0.0213,0.000318
1,classwise,4.464821,0.021889,24.553002,0.879332,51.700152,0.509151,0.916161,0.000623,0.0326,0.001298
2,exact_coverage_classwise,4.217261,0.019215,26.636954,0.809095,40.612052,0.359333,0.899501,0.000577,0.0544,0.001505
3,cluster_random,2.558991,0.081864,16.355646,0.815082,27.944118,0.997261,0.900936,0.002453,0.0108,0.001271

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.541452,0.006235,21.270378,0.073531,25.632269,0.160846,0.899402,0.000483,0.0213,0.000318
1,classwise,4.464821,0.021889,24.553002,0.879332,51.700152,0.509151,0.916161,0.000623,0.0326,0.001298
2,exact_coverage_classwise,4.217261,0.019215,26.636954,0.809095,40.612052,0.359333,0.899501,0.000577,0.0544,0.001505
3,cluster_random,2.558991,0.081864,16.355646,0.815082,27.944118,0.997261,0.900936,0.002453,0.0108,0.001271

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.025392,0.005480,24.854501,0.106708,5.131355,0.015527,0.899769,0.000592,0.0302,0.000486
1,classwise,4.557516,0.038216,24.122371,1.065589,14.817628,0.479895,0.918924,0.000513,0.0299,0.001578
2,exact_coverage_classwise,4.141267,0.042314,27.658863,1.357604,9.967188,0.275338,0.899321,0.000419,0.0484,0.002616
3,cluster_random,2.745741,0.042586,19.028795,1.489233,6.179956,0.398987,0.899522,0.001348,0.0173,0.001908

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.025392,0.005480,24.854501,0.106708,5.131355,0.015527,0.899769,0.000592,0.0302,0.000486
1,classwise,4.557516,0.038216,24.122371,1.065589,14.817628,0.479895,0.918924,0.000513,0.0299,0.001578
2,exact_coverage_classwise,4.141267,0.042314,27.658863,1.357604,9.967188,0.275338,0.899321,0.000419,0.0484,0.002616
3,cluster_random,2.745741,0.042586,19.028795,1.489233,6.179956,0.398987,0.899522,0.001348,0.0173,0.001908

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.025392,0.005480,24.854501,0.106708,5.131355,0.015527,0.899769,0.000592,0.0302,0.000486
1,classwise,4.557516,0.038216,24.122371,1.065589,14.817628,0.479895,0.918924,0.000513,0.0299,0.001578
2,exact_coverage_classwise,4.141267,0.042314,27.658863,1.357604,9.967188,0.275338,0.899321,0.000419,0.0484,0.002616
3,cluster_random,2.745741,0.042586,19.028795,1.489233,6.179956,0.398987,0.899522,0.001348,0.0173,0.001908

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.025392,0.005480,24.854501,0.106708,5.131355,0.015527,0.899769,0.000592,0.0302,0.000486
1,classwise,4.557516,0.038216,24.122371,1.065589,14.817628,0.479895,0.918924,0.000513,0.0299,0.001578
2,exact_coverage_classwise,4.141267,0.042314,27.658863,1.357604,9.967188,0.275338,0.899321,0.000419,0.0484,0.002616
3,cluster_random,2.745741,0.042586,19.028795,1.489233,6.179956,0.398987,0.899522,0.001348,0.0173,0.001908

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.119113,0.054712,13.305494,0.485206,7.720296,0.158273,0.897093,0.001954,0.056,0.007772
1,classwise,4.607987,0.087819,15.291272,1.313797,14.495393,0.395335,0.913467,0.000975,0.029,0.004990
2,exact_coverage_classwise,4.475825,0.079903,17.534232,0.973235,11.887722,0.249397,0.897578,0.000879,0.055,0.006964
3,cluster_random,3.166087,0.082726,11.532238,0.696641,8.747826,0.282274,0.901207,0.002498,0.013,0.004701

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.119113,0.054712,13.305494,0.485206,7.720296,0.158273,0.897093,0.001954,0.056,0.007772
1,classwise,4.607987,0.087819,15.291272,1.313797,14.495393,0.395335,0.913467,0.000975,0.029,0.004990
2,exact_coverage_classwise,4.475825,0.079903,17.534232,0.973235,11.887722,0.249397,0.897578,0.000879,0.055,0.006964
3,cluster_random,3.166087,0.082726,11.532238,0.696641,8.747826,0.282274,0.901207,0.002498,0.013,0.004701

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.119113,0.054712,13.305494,0.485206,7.720296,0.158273,0.897093,0.001954,0.056,0.007772
1,classwise,4.607987,0.087819,15.291272,1.313797,14.495393,0.395335,0.913467,0.000975,0.029,0.004990
2,exact_coverage_classwise,4.475825,0.079903,17.534232,0.973235,11.887722,0.249397,0.897578,0.000879,0.055,0.006964
3,cluster_random,3.166087,0.082726,11.532238,0.696641,8.747826,0.282274,0.901207,0.002498,0.013,0.004701

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.119113,0.054712,13.305494,0.485206,7.720296,0.158273,0.897093,0.001954,0.056,0.007772
1,classwise,4.607987,0.087819,15.291272,1.313797,14.495393,0.395335,0.913467,0.000975,0.029,0.004990
2,exact_coverage_classwise,4.475825,0.079903,17.534232,0.973235,11.887722,0.249397,0.897578,0.000879,0.055,0.006964
3,cluster_random,3.166087,0.082726,11.532238,0.696641,8.747826,0.282274,0.901207,0.002498,0.013,0.004701

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.916770,0.059341,14.983639,0.481274,10.644563,0.158770,0.896404,0.001343,0.044,0.004290
1,classwise,4.683344,0.085307,16.039657,1.272188,17.757600,0.425632,0.913567,0.001138,0.041,0.005736
2,exact_coverage_classwise,4.550784,0.083971,18.196623,1.175409,14.765456,0.275779,0.897426,0.000823,0.060,0.006481
3,cluster_random,3.403484,0.112703,13.588844,0.785506,11.571326,0.309158,0.901322,0.002758,0.024,0.006512

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.916770,0.059341,14.983639,0.481274,10.644563,0.158770,0.896404,0.001343,0.044,0.004290
1,classwise,4.683344,0.085307,16.039657,1.272188,17.757600,0.425632,0.913567,0.001138,0.041,0.005736
2,exact_coverage_classwise,4.550784,0.083971,18.196623,1.175409,14.765456,0.275779,0.897426,0.000823,0.060,0.006481
3,cluster_random,3.403484,0.112703,13.588844,0.785506,11.571326,0.309158,0.901322,0.002758,0.024,0.006512

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.916770,0.059341,14.983639,0.481274,10.644563,0.158770,0.896404,0.001343,0.044,0.004290
1,classwise,4.683344,0.085307,16.039657,1.272188,17.757600,0.425632,0.913567,0.001138,0.041,0.005736
2,exact_coverage_classwise,4.550784,0.083971,18.196623,1.175409,14.765456,0.275779,0.897426,0.000823,0.060,0.006481
3,cluster_random,3.403484,0.112703,13.588844,0.785506,11.571326,0.309158,0.901322,0.002758,0.024,0.006512

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.916770,0.059341,14.983639,0.481274,10.644563,0.158770,0.896404,0.001343,0.044,0.004290
1,classwise,4.683344,0.085307,16.039657,1.272188,17.757600,0.425632,0.913567,0.001138,0.041,0.005736
2,exact_coverage_classwise,4.550784,0.083971,18.196623,1.175409,14.765456,0.275779,0.897426,0.000823,0.060,0.006481
3,cluster_random,3.403484,0.112703,13.588844,0.785506,11.571326,0.309158,0.901322,0.002758,0.024,0.006512

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.830991,0.074640,15.283529,0.534496,8.101163,0.224187,0.900178,0.002259,0.079,0.011086
1,classwise,4.755161,0.098281,14.020932,0.988523,16.427393,0.431232,0.920322,0.001628,0.030,0.004472
2,exact_coverage_classwise,4.538356,0.076044,17.474813,1.010809,13.153893,0.372165,0.900333,0.001512,0.061,0.004572
3,cluster_random,3.972799,0.110022,16.003971,1.110456,9.507363,0.382422,0.904448,0.002668,0.044,0.008025

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.830991,0.074640,15.283529,0.534496,8.101163,0.224187,0.900178,0.002259,0.079,0.011086
1,classwise,4.755161,0.098281,14.020932,0.988523,16.427393,0.431232,0.920322,0.001628,0.030,0.004472
2,exact_coverage_classwise,4.538356,0.076044,17.474813,1.010809,13.153893,0.372165,0.900333,0.001512,0.061,0.004572
3,cluster_random,3.972799,0.110022,16.003971,1.110456,9.507363,0.382422,0.904448,0.002668,0.044,0.008025

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.830991,0.074640,15.283529,0.534496,8.101163,0.224187,0.900178,0.002259,0.079,0.011086
1,classwise,4.755161,0.098281,14.020932,0.988523,16.427393,0.431232,0.920322,0.001628,0.030,0.004472
2,exact_coverage_classwise,4.538356,0.076044,17.474813,1.010809,13.153893,0.372165,0.900333,0.001512,0.061,0.004572
3,cluster_random,3.972799,0.110022,16.003971,1.110456,9.507363,0.382422,0.904448,0.002668,0.044,0.008025

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.830991,0.074640,15.283529,0.534496,8.101163,0.224187,0.900178,0.002259,0.079,0.011086
1,classwise,4.755161,0.098281,14.020932,0.988523,16.427393,0.431232,0.920322,0.001628,0.030,0.004472
2,exact_coverage_classwise,4.538356,0.076044,17.474813,1.010809,13.153893,0.372165,0.900333,0.001512,0.061,0.004572
3,cluster_random,3.972799,0.110022,16.003971,1.110456,9.507363,0.382422,0.904448,0.002668,0.044,0.008025

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.534072,0.021466,21.665572,0.245888,6.936513,0.042329,0.900726,0.000713,0.066575,0.002601
1,classwise,4.433891,0.032210,20.454203,1.063334,12.339946,0.190434,0.916832,0.000707,0.028219,0.002326
2,exact_coverage_classwise,4.197639,0.025870,22.936889,0.909153,10.300182,0.144279,0.900561,0.000822,0.047123,0.001680
3,cluster_random,3.401351,0.062478,16.402142,0.713207,7.556776,0.219990,0.900279,0.002233,0.024110,0.003439

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.534072,0.021466,21.665572,0.245888,6.936513,0.042329,0.900726,0.000713,0.066575,0.002601
1,classwise,4.433891,0.032210,20.454203,1.063334,12.339946,0.190434,0.916832,0.000707,0.028219,0.002326
2,exact_coverage_classwise,4.197639,0.025870,22.936889,0.909153,10.300182,0.144279,0.900561,0.000822,0.047123,0.001680
3,cluster_random,3.401351,0.062478,16.402142,0.713207,7.556776,0.219990,0.900279,0.002233,0.024110,0.003439

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.534072,0.021466,21.665572,0.245888,6.936513,0.042329,0.900726,0.000713,0.066575,0.002601
1,classwise,4.433891,0.032210,20.454203,1.063334,12.339946,0.190434,0.916832,0.000707,0.028219,0.002326
2,exact_coverage_classwise,4.197639,0.025870,22.936889,0.909153,10.300182,0.144279,0.900561,0.000822,0.047123,0.001680
3,cluster_random,3.401351,0.062478,16.402142,0.713207,7.556776,0.219990,0.900279,0.002233,0.024110,0.003439

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.534072,0.021466,21.665572,0.245888,6.936513,0.042329,0.900726,0.000713,0.066575,0.002601
1,classwise,4.433891,0.032210,20.454203,1.063334,12.339946,0.190434,0.916832,0.000707,0.028219,0.002326
2,exact_coverage_classwise,4.197639,0.025870,22.936889,0.909153,10.300182,0.144279,0.900561,0.000822,0.047123,0.001680
3,cluster_random,3.401351,0.062478,16.402142,0.713207,7.556776,0.219990,0.900279,0.002233,0.024110,0.003439

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.288432,0.011114,17.664301,0.119808,10.874006,0.093290,0.900728,0.001021,0.029589,0.002707
1,classwise,4.467268,0.037504,24.034262,1.287085,17.068602,0.277958,0.916408,0.001031,0.033151,0.002274
2,exact_coverage_classwise,4.208780,0.052062,21.722461,1.281129,14.431065,0.228405,0.900094,0.001042,0.048219,0.002826
3,cluster_random,2.759318,0.029884,12.853085,0.827123,11.324087,0.230959,0.901724,0.001849,0.007397,0.001345

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.288432,0.011114,17.664301,0.119808,10.874006,0.093290,0.900728,0.001021,0.029589,0.002707
1,classwise,4.467268,0.037504,24.034262,1.287085,17.068602,0.277958,0.916408,0.001031,0.033151,0.002274
2,exact_coverage_classwise,4.208780,0.052062,21.722461,1.281129,14.431065,0.228405,0.900094,0.001042,0.048219,0.002826
3,cluster_random,2.759318,0.029884,12.853085,0.827123,11.324087,0.230959,0.901724,0.001849,0.007397,0.001345

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.288432,0.011114,17.664301,0.119808,10.874006,0.093290,0.900728,0.001021,0.029589,0.002707
1,classwise,4.467268,0.037504,24.034262,1.287085,17.068602,0.277958,0.916408,0.001031,0.033151,0.002274
2,exact_coverage_classwise,4.208780,0.052062,21.722461,1.281129,14.431065,0.228405,0.900094,0.001042,0.048219,0.002826
3,cluster_random,2.759318,0.029884,12.853085,0.827123,11.324087,0.230959,0.901724,0.001849,0.007397,0.001345

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.288432,0.011114,17.664301,0.119808,10.874006,0.093290,0.900728,0.001021,0.029589,0.002707
1,classwise,4.467268,0.037504,24.034262,1.287085,17.068602,0.277958,0.916408,0.001031,0.033151,0.002274
2,exact_coverage_classwise,4.208780,0.052062,21.722461,1.281129,14.431065,0.228405,0.900094,0.001042,0.048219,0.002826
3,cluster_random,2.759318,0.029884,12.853085,0.827123,11.324087,0.230959,0.901724,0.001849,0.007397,0.001345

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.824987,0.005112,19.759049,0.183192,7.959007,0.034851,0.900438,0.000742,0.040548,0.001491
1,classwise,4.577641,0.047525,23.869522,1.280700,14.444604,0.137651,0.918091,0.000563,0.031781,0.003006
2,exact_coverage_classwise,4.221111,0.047245,21.879860,1.478981,11.740781,0.120260,0.900610,0.000770,0.048493,0.002124
3,cluster_random,3.199262,0.053235,14.034160,0.847001,8.434287,0.177660,0.901196,0.001943,0.014795,0.003448

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.824987,0.005112,19.759049,0.183192,7.959007,0.034851,0.900438,0.000742,0.040548,0.001491
1,classwise,4.577641,0.047525,23.869522,1.280700,14.444604,0.137651,0.918091,0.000563,0.031781,0.003006
2,exact_coverage_classwise,4.221111,0.047245,21.879860,1.478981,11.740781,0.120260,0.900610,0.000770,0.048493,0.002124
3,cluster_random,3.199262,0.053235,14.034160,0.847001,8.434287,0.177660,0.901196,0.001943,0.014795,0.003448

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.824987,0.005112,19.759049,0.183192,7.959007,0.034851,0.900438,0.000742,0.040548,0.001491
1,classwise,4.577641,0.047525,23.869522,1.280700,14.444604,0.137651,0.918091,0.000563,0.031781,0.003006
2,exact_coverage_classwise,4.221111,0.047245,21.879860,1.478981,11.740781,0.120260,0.900610,0.000770,0.048493,0.002124
3,cluster_random,3.199262,0.053235,14.034160,0.847001,8.434287,0.177660,0.901196,0.001943,0.014795,0.003448

.cache/paper/varying_n/places365/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.824987,0.005112,19.759049,0.183192,7.959007,0.034851,0.900438,0.000742,0.040548,0.001491
1,classwise,4.577641,0.047525,23.869522,1.280700,14.444604,0.137651,0.918091,0.000563,0.031781,0.003006
2,exact_coverage_classwise,4.221111,0.047245,21.879860,1.478981,11.740781,0.120260,0.900610,0.000770,0.048493,0.002124
3,cluster_random,3.199262,0.053235,14.034160,0.847001,8.434287,0.177660,0.901196,0.001943,0.014795,0.003448

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.953594,0.038792,46.209325,0.402094,3.171536,0.017554,0.900024,0.000540,0.198420,0.002408
1,classwise,7.027864,0.029759,30.668064,1.663928,278.632244,2.532426,0.915902,0.000395,0.023855,0.001693
2,exact_coverage_classwise,5.488694,0.049305,33.319416,1.354607,120.739929,1.371209,0.900030,0.000501,0.091785,0.003457
3,cluster_random,6.131646,0.070076,45.827413,0.746468,3.549158,0.068032,0.894369,0.000927,0.161453,0.004337

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.953594,0.038792,46.209325,0.402094,3.171536,0.017554,0.900024,0.000540,0.198420,0.002408
1,classwise,7.027864,0.029759,30.668064,1.663928,278.632244,2.532426,0.915902,0.000395,0.023855,0.001693
2,exact_coverage_classwise,5.488694,0.049305,33.319416,1.354607,120.739929,1.371209,0.900030,0.000501,0.091785,0.003457
3,cluster_random,6.131646,0.070076,45.827413,0.746468,3.549158,0.068032,0.894369,0.000927,0.161453,0.004337

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.953594,0.038792,46.209325,0.402094,3.171536,0.017554,0.900024,0.000540,0.198420,0.002408
1,classwise,7.027864,0.029759,30.668064,1.663928,278.632244,2.532426,0.915902,0.000395,0.023855,0.001693
2,exact_coverage_classwise,5.488694,0.049305,33.319416,1.354607,120.739929,1.371209,0.900030,0.000501,0.091785,0.003457
3,cluster_random,6.131646,0.070076,45.827413,0.746468,3.549158,0.068032,0.894369,0.000927,0.161453,0.004337

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.953594,0.038792,46.209325,0.402094,3.171536,0.017554,0.900024,0.000540,0.198420,0.002408
1,classwise,7.027864,0.029759,30.668064,1.663928,278.632244,2.532426,0.915902,0.000395,0.023855,0.001693
2,exact_coverage_classwise,5.488694,0.049305,33.319416,1.354607,120.739929,1.371209,0.900030,0.000501,0.091785,0.003457
3,cluster_random,6.131646,0.070076,45.827413,0.746468,3.549158,0.068032,0.894369,0.000927,0.161453,0.004337

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.190941,0.034676,60.997419,0.179444,8.291944,0.043556,0.898917,0.000706,0.098894,0.001748
1,classwise,7.014254,0.030490,35.259652,3.413415,283.273064,2.495136,0.915307,0.000511,0.028436,0.002364
2,exact_coverage_classwise,5.463122,0.045370,34.038886,1.251268,125.599567,1.371635,0.899158,0.000887,0.093365,0.003885
3,cluster_random,4.159522,0.069099,60.874307,0.406935,8.132017,0.083415,0.893615,0.001357,0.091627,0.002300

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.190941,0.034676,60.997419,0.179444,8.291944,0.043556,0.898917,0.000706,0.098894,0.001748
1,classwise,7.014254,0.030490,35.259652,3.413415,283.273064,2.495136,0.915307,0.000511,0.028436,0.002364
2,exact_coverage_classwise,5.463122,0.045370,34.038886,1.251268,125.599567,1.371635,0.899158,0.000887,0.093365,0.003885
3,cluster_random,4.159522,0.069099,60.874307,0.406935,8.132017,0.083415,0.893615,0.001357,0.091627,0.002300

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.190941,0.034676,60.997419,0.179444,8.291944,0.043556,0.898917,0.000706,0.098894,0.001748
1,classwise,7.014254,0.030490,35.259652,3.413415,283.273064,2.495136,0.915307,0.000511,0.028436,0.002364
2,exact_coverage_classwise,5.463122,0.045370,34.038886,1.251268,125.599567,1.371635,0.899158,0.000887,0.093365,0.003885
3,cluster_random,4.159522,0.069099,60.874307,0.406935,8.132017,0.083415,0.893615,0.001357,0.091627,0.002300

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.190941,0.034676,60.997419,0.179444,8.291944,0.043556,0.898917,0.000706,0.098894,0.001748
1,classwise,7.014254,0.030490,35.259652,3.413415,283.273064,2.495136,0.915307,0.000511,0.028436,0.002364
2,exact_coverage_classwise,5.463122,0.045370,34.038886,1.251268,125.599567,1.371635,0.899158,0.000887,0.093365,0.003885
3,cluster_random,4.159522,0.069099,60.874307,0.406935,8.132017,0.083415,0.893615,0.001357,0.091627,0.002300

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.004017,0.021326,57.397348,0.214557,5.131887,0.012396,0.898207,0.000503,0.132227,0.001816
1,classwise,7.078095,0.039873,35.619076,3.372181,284.592466,2.449225,0.915932,0.000515,0.026382,0.001843
2,exact_coverage_classwise,5.486583,0.057472,34.433235,1.219452,127.024548,1.521159,0.899561,0.000730,0.093365,0.004218
3,cluster_random,4.842092,0.067478,57.594475,0.361308,5.197881,0.063193,0.893716,0.001334,0.123855,0.004385

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.004017,0.021326,57.397348,0.214557,5.131887,0.012396,0.898207,0.000503,0.132227,0.001816
1,classwise,7.078095,0.039873,35.619076,3.372181,284.592466,2.449225,0.915932,0.000515,0.026382,0.001843
2,exact_coverage_classwise,5.486583,0.057472,34.433235,1.219452,127.024548,1.521159,0.899561,0.000730,0.093365,0.004218
3,cluster_random,4.842092,0.067478,57.594475,0.361308,5.197881,0.063193,0.893716,0.001334,0.123855,0.004385

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.004017,0.021326,57.397348,0.214557,5.131887,0.012396,0.898207,0.000503,0.132227,0.001816
1,classwise,7.078095,0.039873,35.619076,3.372181,284.592466,2.449225,0.915932,0.000515,0.026382,0.001843
2,exact_coverage_classwise,5.486583,0.057472,34.433235,1.219452,127.024548,1.521159,0.899561,0.000730,0.093365,0.004218
3,cluster_random,4.842092,0.067478,57.594475,0.361308,5.197881,0.063193,0.893716,0.001334,0.123855,0.004385

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=30/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.004017,0.021326,57.397348,0.214557,5.131887,0.012396,0.898207,0.000503,0.132227,0.001816
1,classwise,7.078095,0.039873,35.619076,3.372181,284.592466,2.449225,0.915932,0.000515,0.026382,0.001843
2,exact_coverage_classwise,5.486583,0.057472,34.433235,1.219452,127.024548,1.521159,0.899561,0.000730,0.093365,0.004218
3,cluster_random,4.842092,0.067478,57.594475,0.361308,5.197881,0.063193,0.893716,0.001334,0.123855,0.004385

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.258290,0.014821,38.656047,0.190886,1.915009,0.009318,0.899214,0.000465,0.0836,0.001976
1,classwise,3.791575,0.027566,18.732763,0.638869,5.948960,0.125204,0.912146,0.000350,0.0194,0.001930
2,exact_coverage_classwise,3.664357,0.023699,20.775072,0.625587,4.691255,0.073394,0.899513,0.000253,0.0340,0.002289
3,cluster_random,3.314030,0.039050,21.226210,1.490841,2.663093,0.044583,0.901066,0.001041,0.0214,0.001409

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.258290,0.014821,38.656047,0.190886,1.915009,0.009318,0.899214,0.000465,0.0836,0.001976
1,classwise,3.791575,0.027566,18.732763,0.638869,5.948960,0.125204,0.912146,0.000350,0.0194,0.001930
2,exact_coverage_classwise,3.664357,0.023699,20.775072,0.625587,4.691255,0.073394,0.899513,0.000253,0.0340,0.002289
3,cluster_random,3.314030,0.039050,21.226210,1.490841,2.663093,0.044583,0.901066,0.001041,0.0214,0.001409

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.258290,0.014821,38.656047,0.190886,1.915009,0.009318,0.899214,0.000465,0.0836,0.001976
1,classwise,3.791575,0.027566,18.732763,0.638869,5.948960,0.125204,0.912146,0.000350,0.0194,0.001930
2,exact_coverage_classwise,3.664357,0.023699,20.775072,0.625587,4.691255,0.073394,0.899513,0.000253,0.0340,0.002289
3,cluster_random,3.314030,0.039050,21.226210,1.490841,2.663093,0.044583,0.901066,0.001041,0.0214,0.001409

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.258290,0.014821,38.656047,0.190886,1.915009,0.009318,0.899214,0.000465,0.0836,0.001976
1,classwise,3.791575,0.027566,18.732763,0.638869,5.948960,0.125204,0.912146,0.000350,0.0194,0.001930
2,exact_coverage_classwise,3.664357,0.023699,20.775072,0.625587,4.691255,0.073394,0.899513,0.000253,0.0340,0.002289
3,cluster_random,3.314030,0.039050,21.226210,1.490841,2.663093,0.044583,0.901066,0.001041,0.0214,0.001409

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.546450,0.006233,22.121934,0.166835,25.822342,0.145462,0.900227,0.000448,0.0210,1.097135e-18
1,classwise,3.823421,0.020037,20.276829,0.984961,43.505247,0.187530,0.913166,0.000312,0.0192,1.567163e-03
2,exact_coverage_classwise,3.694803,0.021347,21.716357,1.067438,36.395062,0.210832,0.899784,0.000346,0.0328,9.252027e-04
3,cluster_random,2.321190,0.022552,15.250539,0.935030,28.641679,0.311478,0.904305,0.000771,0.0061,2.983287e-04

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.546450,0.006233,22.121934,0.166835,25.822342,0.145462,0.900227,0.000448,0.0210,1.097135e-18
1,classwise,3.823421,0.020037,20.276829,0.984961,43.505247,0.187530,0.913166,0.000312,0.0192,1.567163e-03
2,exact_coverage_classwise,3.694803,0.021347,21.716357,1.067438,36.395062,0.210832,0.899784,0.000346,0.0328,9.252027e-04
3,cluster_random,2.321190,0.022552,15.250539,0.935030,28.641679,0.311478,0.904305,0.000771,0.0061,2.983287e-04

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.546450,0.006233,22.121934,0.166835,25.822342,0.145462,0.900227,0.000448,0.0210,1.097135e-18
1,classwise,3.823421,0.020037,20.276829,0.984961,43.505247,0.187530,0.913166,0.000312,0.0192,1.567163e-03
2,exact_coverage_classwise,3.694803,0.021347,21.716357,1.067438,36.395062,0.210832,0.899784,0.000346,0.0328,9.252027e-04
3,cluster_random,2.321190,0.022552,15.250539,0.935030,28.641679,0.311478,0.904305,0.000771,0.0061,2.983287e-04

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.546450,0.006233,22.121934,0.166835,25.822342,0.145462,0.900227,0.000448,0.0210,1.097135e-18
1,classwise,3.823421,0.020037,20.276829,0.984961,43.505247,0.187530,0.913166,0.000312,0.0192,1.567163e-03
2,exact_coverage_classwise,3.694803,0.021347,21.716357,1.067438,36.395062,0.210832,0.899784,0.000346,0.0328,9.252027e-04
3,cluster_random,2.321190,0.022552,15.250539,0.935030,28.641679,0.311478,0.904305,0.000771,0.0061,2.983287e-04

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.004357,0.003155,25.095660,0.078664,5.123832,0.009656,0.899745,0.000388,0.0268,0.000341
1,classwise,3.866390,0.028691,20.286465,1.184300,10.504359,0.278904,0.914038,0.000329,0.0193,0.000960
2,exact_coverage_classwise,3.688143,0.032760,20.130567,1.075885,8.116619,0.209401,0.899163,0.000370,0.0353,0.002324
3,cluster_random,2.618694,0.024630,16.860949,0.711625,6.245129,0.270663,0.903649,0.000795,0.0094,0.001079

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.004357,0.003155,25.095660,0.078664,5.123832,0.009656,0.899745,0.000388,0.0268,0.000341
1,classwise,3.866390,0.028691,20.286465,1.184300,10.504359,0.278904,0.914038,0.000329,0.0193,0.000960
2,exact_coverage_classwise,3.688143,0.032760,20.130567,1.075885,8.116619,0.209401,0.899163,0.000370,0.0353,0.002324
3,cluster_random,2.618694,0.024630,16.860949,0.711625,6.245129,0.270663,0.903649,0.000795,0.0094,0.001079

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.004357,0.003155,25.095660,0.078664,5.123832,0.009656,0.899745,0.000388,0.0268,0.000341
1,classwise,3.866390,0.028691,20.286465,1.184300,10.504359,0.278904,0.914038,0.000329,0.0193,0.000960
2,exact_coverage_classwise,3.688143,0.032760,20.130567,1.075885,8.116619,0.209401,0.899163,0.000370,0.0353,0.002324
3,cluster_random,2.618694,0.024630,16.860949,0.711625,6.245129,0.270663,0.903649,0.000795,0.0094,0.001079

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.004357,0.003155,25.095660,0.078664,5.123832,0.009656,0.899745,0.000388,0.0268,0.000341
1,classwise,3.866390,0.028691,20.286465,1.184300,10.504359,0.278904,0.914038,0.000329,0.0193,0.000960
2,exact_coverage_classwise,3.688143,0.032760,20.130567,1.075885,8.116619,0.209401,0.899163,0.000370,0.0353,0.002324
3,cluster_random,2.618694,0.024630,16.860949,0.711625,6.245129,0.270663,0.903649,0.000795,0.0094,0.001079

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.063270,0.048297,12.738698,0.508700,7.906615,0.165169,0.899073,0.002031,0.051,0.007804
1,classwise,4.223034,0.068021,15.145298,1.279120,12.725996,0.185746,0.910492,0.001071,0.023,0.004012
2,exact_coverage_classwise,4.084449,0.065180,16.447673,1.237929,11.032058,0.191538,0.898419,0.001150,0.036,0.005514
3,cluster_random,3.048439,0.079985,13.889436,1.473664,8.873481,0.334178,0.900415,0.003319,0.016,0.004290

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.063270,0.048297,12.738698,0.508700,7.906615,0.165169,0.899073,0.002031,0.051,0.007804
1,classwise,4.223034,0.068021,15.145298,1.279120,12.725996,0.185746,0.910492,0.001071,0.023,0.004012
2,exact_coverage_classwise,4.084449,0.065180,16.447673,1.237929,11.032058,0.191538,0.898419,0.001150,0.036,0.005514
3,cluster_random,3.048439,0.079985,13.889436,1.473664,8.873481,0.334178,0.900415,0.003319,0.016,0.004290

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.063270,0.048297,12.738698,0.508700,7.906615,0.165169,0.899073,0.002031,0.051,0.007804
1,classwise,4.223034,0.068021,15.145298,1.279120,12.725996,0.185746,0.910492,0.001071,0.023,0.004012
2,exact_coverage_classwise,4.084449,0.065180,16.447673,1.237929,11.032058,0.191538,0.898419,0.001150,0.036,0.005514
3,cluster_random,3.048439,0.079985,13.889436,1.473664,8.873481,0.334178,0.900415,0.003319,0.016,0.004290

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.063270,0.048297,12.738698,0.508700,7.906615,0.165169,0.899073,0.002031,0.051,0.007804
1,classwise,4.223034,0.068021,15.145298,1.279120,12.725996,0.185746,0.910492,0.001071,0.023,0.004012
2,exact_coverage_classwise,4.084449,0.065180,16.447673,1.237929,11.032058,0.191538,0.898419,0.001150,0.036,0.005514
3,cluster_random,3.048439,0.079985,13.889436,1.473664,8.873481,0.334178,0.900415,0.003319,0.016,0.004290

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.795800,0.061621,14.186172,0.589853,10.969319,0.188100,0.898750,0.001671,0.040,0.004899
1,classwise,4.124254,0.079112,14.153630,1.259512,16.104242,0.250364,0.911946,0.001248,0.025,0.004528
2,exact_coverage_classwise,4.054923,0.074526,17.703914,1.639845,14.035454,0.220216,0.898677,0.001039,0.041,0.003860
3,cluster_random,3.283903,0.087060,12.958270,0.926431,11.979781,0.364548,0.901304,0.002530,0.024,0.005138

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.795800,0.061621,14.186172,0.589853,10.969319,0.188100,0.898750,0.001671,0.040,0.004899
1,classwise,4.124254,0.079112,14.153630,1.259512,16.104242,0.250364,0.911946,0.001248,0.025,0.004528
2,exact_coverage_classwise,4.054923,0.074526,17.703914,1.639845,14.035454,0.220216,0.898677,0.001039,0.041,0.003860
3,cluster_random,3.283903,0.087060,12.958270,0.926431,11.979781,0.364548,0.901304,0.002530,0.024,0.005138

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.795800,0.061621,14.186172,0.589853,10.969319,0.188100,0.898750,0.001671,0.040,0.004899
1,classwise,4.124254,0.079112,14.153630,1.259512,16.104242,0.250364,0.911946,0.001248,0.025,0.004528
2,exact_coverage_classwise,4.054923,0.074526,17.703914,1.639845,14.035454,0.220216,0.898677,0.001039,0.041,0.003860
3,cluster_random,3.283903,0.087060,12.958270,0.926431,11.979781,0.364548,0.901304,0.002530,0.024,0.005138

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.795800,0.061621,14.186172,0.589853,10.969319,0.188100,0.898750,0.001671,0.040,0.004899
1,classwise,4.124254,0.079112,14.153630,1.259512,16.104242,0.250364,0.911946,0.001248,0.025,0.004528
2,exact_coverage_classwise,4.054923,0.074526,17.703914,1.639845,14.035454,0.220216,0.898677,0.001039,0.041,0.003860
3,cluster_random,3.283903,0.087060,12.958270,0.926431,11.979781,0.364548,0.901304,0.002530,0.024,0.005138

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.849828,0.070299,15.339337,0.452292,8.229881,0.172723,0.900492,0.001928,0.078,0.010276
1,classwise,4.171695,0.065392,13.882955,0.656069,14.398377,0.321984,0.914738,0.001361,0.029,0.003860
2,exact_coverage_classwise,4.066670,0.080065,17.959180,1.342978,12.233158,0.288003,0.899946,0.001445,0.048,0.007043
3,cluster_random,3.789477,0.067072,15.535687,1.126709,9.748958,0.332453,0.905904,0.002361,0.027,0.005486

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.849828,0.070299,15.339337,0.452292,8.229881,0.172723,0.900492,0.001928,0.078,0.010276
1,classwise,4.171695,0.065392,13.882955,0.656069,14.398377,0.321984,0.914738,0.001361,0.029,0.003860
2,exact_coverage_classwise,4.066670,0.080065,17.959180,1.342978,12.233158,0.288003,0.899946,0.001445,0.048,0.007043
3,cluster_random,3.789477,0.067072,15.535687,1.126709,9.748958,0.332453,0.905904,0.002361,0.027,0.005486

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.849828,0.070299,15.339337,0.452292,8.229881,0.172723,0.900492,0.001928,0.078,0.010276
1,classwise,4.171695,0.065392,13.882955,0.656069,14.398377,0.321984,0.914738,0.001361,0.029,0.003860
2,exact_coverage_classwise,4.066670,0.080065,17.959180,1.342978,12.233158,0.288003,0.899946,0.001445,0.048,0.007043
3,cluster_random,3.789477,0.067072,15.535687,1.126709,9.748958,0.332453,0.905904,0.002361,0.027,0.005486

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.849828,0.070299,15.339337,0.452292,8.229881,0.172723,0.900492,0.001928,0.078,0.010276
1,classwise,4.171695,0.065392,13.882955,0.656069,14.398377,0.321984,0.914738,0.001361,0.029,0.003860
2,exact_coverage_classwise,4.066670,0.080065,17.959180,1.342978,12.233158,0.288003,0.899946,0.001445,0.048,0.007043
3,cluster_random,3.789477,0.067072,15.535687,1.126709,9.748958,0.332453,0.905904,0.002361,0.027,0.005486

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.561124,0.020325,21.970630,0.226396,6.884628,0.040181,0.899853,0.000700,0.069041,0.002413
1,classwise,3.920565,0.036367,17.969552,0.973179,10.836030,0.127296,0.912399,0.000796,0.020548,0.002200
2,exact_coverage_classwise,3.811060,0.033366,19.539473,0.856525,9.538870,0.110076,0.899751,0.000845,0.033699,0.003002
3,cluster_random,3.180917,0.045348,15.917992,2.010017,7.766199,0.073690,0.903729,0.001270,0.014247,0.002475

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.561124,0.020325,21.970630,0.226396,6.884628,0.040181,0.899853,0.000700,0.069041,0.002413
1,classwise,3.920565,0.036367,17.969552,0.973179,10.836030,0.127296,0.912399,0.000796,0.020548,0.002200
2,exact_coverage_classwise,3.811060,0.033366,19.539473,0.856525,9.538870,0.110076,0.899751,0.000845,0.033699,0.003002
3,cluster_random,3.180917,0.045348,15.917992,2.010017,7.766199,0.073690,0.903729,0.001270,0.014247,0.002475

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.561124,0.020325,21.970630,0.226396,6.884628,0.040181,0.899853,0.000700,0.069041,0.002413
1,classwise,3.920565,0.036367,17.969552,0.973179,10.836030,0.127296,0.912399,0.000796,0.020548,0.002200
2,exact_coverage_classwise,3.811060,0.033366,19.539473,0.856525,9.538870,0.110076,0.899751,0.000845,0.033699,0.003002
3,cluster_random,3.180917,0.045348,15.917992,2.010017,7.766199,0.073690,0.903729,0.001270,0.014247,0.002475

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.561124,0.020325,21.970630,0.226396,6.884628,0.040181,0.899853,0.000700,0.069041,0.002413
1,classwise,3.920565,0.036367,17.969552,0.973179,10.836030,0.127296,0.912399,0.000796,0.020548,0.002200
2,exact_coverage_classwise,3.811060,0.033366,19.539473,0.856525,9.538870,0.110076,0.899751,0.000845,0.033699,0.003002
3,cluster_random,3.180917,0.045348,15.917992,2.010017,7.766199,0.073690,0.903729,0.001270,0.014247,0.002475

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.275011,0.015170,17.516758,0.170246,10.803968,0.078182,0.900130,0.000846,0.029589,0.002043
1,classwise,3.842363,0.066613,16.084064,1.162446,15.259814,0.193334,0.912935,0.000786,0.016986,0.003070
2,exact_coverage_classwise,3.769032,0.043181,17.963263,0.900317,13.554262,0.164548,0.899513,0.000947,0.033699,0.002294
3,cluster_random,2.760611,0.036612,11.939055,0.727053,11.536480,0.104248,0.903261,0.001112,0.005753,0.001664

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.275011,0.015170,17.516758,0.170246,10.803968,0.078182,0.900130,0.000846,0.029589,0.002043
1,classwise,3.842363,0.066613,16.084064,1.162446,15.259814,0.193334,0.912935,0.000786,0.016986,0.003070
2,exact_coverage_classwise,3.769032,0.043181,17.963263,0.900317,13.554262,0.164548,0.899513,0.000947,0.033699,0.002294
3,cluster_random,2.760611,0.036612,11.939055,0.727053,11.536480,0.104248,0.903261,0.001112,0.005753,0.001664

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.275011,0.015170,17.516758,0.170246,10.803968,0.078182,0.900130,0.000846,0.029589,0.002043
1,classwise,3.842363,0.066613,16.084064,1.162446,15.259814,0.193334,0.912935,0.000786,0.016986,0.003070
2,exact_coverage_classwise,3.769032,0.043181,17.963263,0.900317,13.554262,0.164548,0.899513,0.000947,0.033699,0.002294
3,cluster_random,2.760611,0.036612,11.939055,0.727053,11.536480,0.104248,0.903261,0.001112,0.005753,0.001664

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.275011,0.015170,17.516758,0.170246,10.803968,0.078182,0.900130,0.000846,0.029589,0.002043
1,classwise,3.842363,0.066613,16.084064,1.162446,15.259814,0.193334,0.912935,0.000786,0.016986,0.003070
2,exact_coverage_classwise,3.769032,0.043181,17.963263,0.900317,13.554262,0.164548,0.899513,0.000947,0.033699,0.002294
3,cluster_random,2.760611,0.036612,11.939055,0.727053,11.536480,0.104248,0.903261,0.001112,0.005753,0.001664

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.846054,0.004830,20.251678,0.276967,7.929106,0.033674,0.900032,0.000733,0.039178,0.001691
1,classwise,3.924449,0.057265,16.376019,1.095217,12.501897,0.165400,0.914092,0.000644,0.017534,0.002232
2,exact_coverage_classwise,3.811294,0.037221,18.137482,0.917456,10.849171,0.127118,0.899625,0.000743,0.037534,0.002326
3,cluster_random,3.073843,0.043719,12.645739,0.478902,8.738936,0.110275,0.904122,0.001149,0.007671,0.001213

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.846054,0.004830,20.251678,0.276967,7.929106,0.033674,0.900032,0.000733,0.039178,0.001691
1,classwise,3.924449,0.057265,16.376019,1.095217,12.501897,0.165400,0.914092,0.000644,0.017534,0.002232
2,exact_coverage_classwise,3.811294,0.037221,18.137482,0.917456,10.849171,0.127118,0.899625,0.000743,0.037534,0.002326
3,cluster_random,3.073843,0.043719,12.645739,0.478902,8.738936,0.110275,0.904122,0.001149,0.007671,0.001213

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.846054,0.004830,20.251678,0.276967,7.929106,0.033674,0.900032,0.000733,0.039178,0.001691
1,classwise,3.924449,0.057265,16.376019,1.095217,12.501897,0.165400,0.914092,0.000644,0.017534,0.002232
2,exact_coverage_classwise,3.811294,0.037221,18.137482,0.917456,10.849171,0.127118,0.899625,0.000743,0.037534,0.002326
3,cluster_random,3.073843,0.043719,12.645739,0.478902,8.738936,0.110275,0.904122,0.001149,0.007671,0.001213

.cache/paper/varying_n/places365/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.846054,0.004830,20.251678,0.276967,7.929106,0.033674,0.900032,0.000733,0.039178,0.001691
1,classwise,3.924449,0.057265,16.376019,1.095217,12.501897,0.165400,0.914092,0.000644,0.017534,0.002232
2,exact_coverage_classwise,3.811294,0.037221,18.137482,0.917456,10.849171,0.127118,0.899625,0.000743,0.037534,0.002326
3,cluster_random,3.073843,0.043719,12.645739,0.478902,8.738936,0.110275,0.904122,0.001149,0.007671,0.001213

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.959695,0.048425,46.354514,0.463137,3.169636,0.021521,0.899951,0.000674,0.198420,0.002923
1,classwise,6.391079,0.031048,26.945017,1.927109,208.517931,2.425456,0.912004,0.000422,0.029700,0.002243
2,exact_coverage_classwise,5.216634,0.053412,32.685907,1.318405,79.082939,1.379090,0.899561,0.000378,0.088310,0.003187
3,cluster_random,6.030897,0.113955,48.211667,1.167375,3.622327,0.049171,0.895043,0.001456,0.153397,0.006022

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.959695,0.048425,46.354514,0.463137,3.169636,0.021521,0.899951,0.000674,0.198420,0.002923
1,classwise,6.391079,0.031048,26.945017,1.927109,208.517931,2.425456,0.912004,0.000422,0.029700,0.002243
2,exact_coverage_classwise,5.216634,0.053412,32.685907,1.318405,79.082939,1.379090,0.899561,0.000378,0.088310,0.003187
3,cluster_random,6.030897,0.113955,48.211667,1.167375,3.622327,0.049171,0.895043,0.001456,0.153397,0.006022

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.959695,0.048425,46.354514,0.463137,3.169636,0.021521,0.899951,0.000674,0.198420,0.002923
1,classwise,6.391079,0.031048,26.945017,1.927109,208.517931,2.425456,0.912004,0.000422,0.029700,0.002243
2,exact_coverage_classwise,5.216634,0.053412,32.685907,1.318405,79.082939,1.379090,0.899561,0.000378,0.088310,0.003187
3,cluster_random,6.030897,0.113955,48.211667,1.167375,3.622327,0.049171,0.895043,0.001456,0.153397,0.006022

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.959695,0.048425,46.354514,0.463137,3.169636,0.021521,0.899951,0.000674,0.198420,0.002923
1,classwise,6.391079,0.031048,26.945017,1.927109,208.517931,2.425456,0.912004,0.000422,0.029700,0.002243
2,exact_coverage_classwise,5.216634,0.053412,32.685907,1.318405,79.082939,1.379090,0.899561,0.000378,0.088310,0.003187
3,cluster_random,6.030897,0.113955,48.211667,1.167375,3.622327,0.049171,0.895043,0.001456,0.153397,0.006022

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.189134,0.030924,59.830661,0.423151,8.263820,0.041520,0.898509,0.000674,0.098894,0.001502
1,classwise,6.362059,0.028187,29.836028,2.995721,213.676163,2.405917,0.912249,0.000695,0.029068,0.001675
2,exact_coverage_classwise,5.207732,0.057867,37.977742,2.212862,84.138064,1.350164,0.899219,0.000735,0.090047,0.004568
3,cluster_random,3.974309,0.092292,60.500992,0.807304,8.369749,0.119097,0.896053,0.001717,0.082938,0.004322

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.189134,0.030924,59.830661,0.423151,8.263820,0.041520,0.898509,0.000674,0.098894,0.001502
1,classwise,6.362059,0.028187,29.836028,2.995721,213.676163,2.405917,0.912249,0.000695,0.029068,0.001675
2,exact_coverage_classwise,5.207732,0.057867,37.977742,2.212862,84.138064,1.350164,0.899219,0.000735,0.090047,0.004568
3,cluster_random,3.974309,0.092292,60.500992,0.807304,8.369749,0.119097,0.896053,0.001717,0.082938,0.004322

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.189134,0.030924,59.830661,0.423151,8.263820,0.041520,0.898509,0.000674,0.098894,0.001502
1,classwise,6.362059,0.028187,29.836028,2.995721,213.676163,2.405917,0.912249,0.000695,0.029068,0.001675
2,exact_coverage_classwise,5.207732,0.057867,37.977742,2.212862,84.138064,1.350164,0.899219,0.000735,0.090047,0.004568
3,cluster_random,3.974309,0.092292,60.500992,0.807304,8.369749,0.119097,0.896053,0.001717,0.082938,0.004322

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.189134,0.030924,59.830661,0.423151,8.263820,0.041520,0.898509,0.000674,0.098894,0.001502
1,classwise,6.362059,0.028187,29.836028,2.995721,213.676163,2.405917,0.912249,0.000695,0.029068,0.001675
2,exact_coverage_classwise,5.207732,0.057867,37.977742,2.212862,84.138064,1.350164,0.899219,0.000735,0.090047,0.004568
3,cluster_random,3.974309,0.092292,60.500992,0.807304,8.369749,0.119097,0.896053,0.001717,0.082938,0.004322

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.974791,0.032124,57.221771,0.228036,5.137711,0.017886,0.898534,0.000741,0.132543,0.002882
1,classwise,6.379136,0.031538,29.028712,3.119770,214.811299,2.477350,0.912178,0.000622,0.028752,0.002021
2,exact_coverage_classwise,5.051563,0.030127,34.639697,1.987774,85.224100,1.465551,0.899657,0.000661,0.080411,0.003987
3,cluster_random,4.655838,0.089087,58.866599,0.492077,5.326741,0.099555,0.895813,0.001752,0.112638,0.005899

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.974791,0.032124,57.221771,0.228036,5.137711,0.017886,0.898534,0.000741,0.132543,0.002882
1,classwise,6.379136,0.031538,29.028712,3.119770,214.811299,2.477350,0.912178,0.000622,0.028752,0.002021
2,exact_coverage_classwise,5.051563,0.030127,34.639697,1.987774,85.224100,1.465551,0.899657,0.000661,0.080411,0.003987
3,cluster_random,4.655838,0.089087,58.866599,0.492077,5.326741,0.099555,0.895813,0.001752,0.112638,0.005899

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.974791,0.032124,57.221771,0.228036,5.137711,0.017886,0.898534,0.000741,0.132543,0.002882
1,classwise,6.379136,0.031538,29.028712,3.119770,214.811299,2.477350,0.912178,0.000622,0.028752,0.002021
2,exact_coverage_classwise,5.051563,0.030127,34.639697,1.987774,85.224100,1.465551,0.899657,0.000661,0.080411,0.003987
3,cluster_random,4.655838,0.089087,58.866599,0.492077,5.326741,0.099555,0.895813,0.001752,0.112638,0.005899

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=40/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.974791,0.032124,57.221771,0.228036,5.137711,0.017886,0.898534,0.000741,0.132543,0.002882
1,classwise,6.379136,0.031538,29.028712,3.119770,214.811299,2.477350,0.912178,0.000622,0.028752,0.002021
2,exact_coverage_classwise,5.051563,0.030127,34.639697,1.987774,85.224100,1.465551,0.899657,0.000661,0.080411,0.003987
3,cluster_random,4.655838,0.089087,58.866599,0.492077,5.326741,0.099555,0.895813,0.001752,0.112638,0.005899

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.255063,0.016347,38.674388,0.190910,1.916796,0.009820,0.899290,0.000494,0.0824,0.001877
1,classwise,3.440016,0.022349,17.048546,0.766009,5.075701,0.078923,0.909475,0.000273,0.0123,0.001297
2,exact_coverage_classwise,3.343005,0.016696,18.053520,0.796698,4.264715,0.063422,0.899211,0.000292,0.0223,0.001371
3,cluster_random,3.107672,0.028055,18.334423,0.794606,2.590801,0.057287,0.899607,0.000705,0.0178,0.001777

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.255063,0.016347,38.674388,0.190910,1.916796,0.009820,0.899290,0.000494,0.0824,0.001877
1,classwise,3.440016,0.022349,17.048546,0.766009,5.075701,0.078923,0.909475,0.000273,0.0123,0.001297
2,exact_coverage_classwise,3.343005,0.016696,18.053520,0.796698,4.264715,0.063422,0.899211,0.000292,0.0223,0.001371
3,cluster_random,3.107672,0.028055,18.334423,0.794606,2.590801,0.057287,0.899607,0.000705,0.0178,0.001777

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.255063,0.016347,38.674388,0.190910,1.916796,0.009820,0.899290,0.000494,0.0824,0.001877
1,classwise,3.440016,0.022349,17.048546,0.766009,5.075701,0.078923,0.909475,0.000273,0.0123,0.001297
2,exact_coverage_classwise,3.343005,0.016696,18.053520,0.796698,4.264715,0.063422,0.899211,0.000292,0.0223,0.001371
3,cluster_random,3.107672,0.028055,18.334423,0.794606,2.590801,0.057287,0.899607,0.000705,0.0178,0.001777

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.255063,0.016347,38.674388,0.190910,1.916796,0.009820,0.899290,0.000494,0.0824,0.001877
1,classwise,3.440016,0.022349,17.048546,0.766009,5.075701,0.078923,0.909475,0.000273,0.0123,0.001297
2,exact_coverage_classwise,3.343005,0.016696,18.053520,0.796698,4.264715,0.063422,0.899211,0.000292,0.0223,0.001371
3,cluster_random,3.107672,0.028055,18.334423,0.794606,2.590801,0.057287,0.899607,0.000705,0.0178,0.001777

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.544407,0.003633,21.277486,0.067242,25.622265,0.111304,0.899361,0.000346,0.0215,0.000292
1,classwise,3.493231,0.018846,16.905574,1.215922,39.705516,0.233704,0.910155,0.000351,0.0137,0.000917
2,exact_coverage_classwise,3.489934,0.032452,19.198864,0.797116,34.166055,0.162857,0.898186,0.000441,0.0268,0.001586
3,cluster_random,2.258431,0.042054,13.594943,0.753901,27.183637,0.534300,0.900078,0.001213,0.0050,0.001114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.544407,0.003633,21.277486,0.067242,25.622265,0.111304,0.899361,0.000346,0.0215,0.000292
1,classwise,3.493231,0.018846,16.905574,1.215922,39.705516,0.233704,0.910155,0.000351,0.0137,0.000917
2,exact_coverage_classwise,3.489934,0.032452,19.198864,0.797116,34.166055,0.162857,0.898186,0.000441,0.0268,0.001586
3,cluster_random,2.258431,0.042054,13.594943,0.753901,27.183637,0.534300,0.900078,0.001213,0.0050,0.001114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.544407,0.003633,21.277486,0.067242,25.622265,0.111304,0.899361,0.000346,0.0215,0.000292
1,classwise,3.493231,0.018846,16.905574,1.215922,39.705516,0.233704,0.910155,0.000351,0.0137,0.000917
2,exact_coverage_classwise,3.489934,0.032452,19.198864,0.797116,34.166055,0.162857,0.898186,0.000441,0.0268,0.001586
3,cluster_random,2.258431,0.042054,13.594943,0.753901,27.183637,0.534300,0.900078,0.001213,0.0050,0.001114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.544407,0.003633,21.277486,0.067242,25.622265,0.111304,0.899361,0.000346,0.0215,0.000292
1,classwise,3.493231,0.018846,16.905574,1.215922,39.705516,0.233704,0.910155,0.000351,0.0137,0.000917
2,exact_coverage_classwise,3.489934,0.032452,19.198864,0.797116,34.166055,0.162857,0.898186,0.000441,0.0268,0.001586
3,cluster_random,2.258431,0.042054,13.594943,0.753901,27.183637,0.534300,0.900078,0.001213,0.0050,0.001114

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.012505,0.003235,24.986092,0.103738,5.130823,0.008090,0.899594,0.000336,0.0288,0.000310
1,classwise,3.445554,0.018924,15.925437,0.488810,8.845279,0.296235,0.910559,0.000297,0.0136,0.000982
2,exact_coverage_classwise,3.479847,0.030276,19.459452,0.892685,7.518156,0.214756,0.897980,0.000435,0.0276,0.000839
3,cluster_random,2.596498,0.038149,16.365052,1.178874,6.469633,0.340526,0.901659,0.001300,0.0103,0.001543

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.012505,0.003235,24.986092,0.103738,5.130823,0.008090,0.899594,0.000336,0.0288,0.000310
1,classwise,3.445554,0.018924,15.925437,0.488810,8.845279,0.296235,0.910559,0.000297,0.0136,0.000982
2,exact_coverage_classwise,3.479847,0.030276,19.459452,0.892685,7.518156,0.214756,0.897980,0.000435,0.0276,0.000839
3,cluster_random,2.596498,0.038149,16.365052,1.178874,6.469633,0.340526,0.901659,0.001300,0.0103,0.001543

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.012505,0.003235,24.986092,0.103738,5.130823,0.008090,0.899594,0.000336,0.0288,0.000310
1,classwise,3.445554,0.018924,15.925437,0.488810,8.845279,0.296235,0.910559,0.000297,0.0136,0.000982
2,exact_coverage_classwise,3.479847,0.030276,19.459452,0.892685,7.518156,0.214756,0.897980,0.000435,0.0276,0.000839
3,cluster_random,2.596498,0.038149,16.365052,1.178874,6.469633,0.340526,0.901659,0.001300,0.0103,0.001543

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.012505,0.003235,24.986092,0.103738,5.130823,0.008090,0.899594,0.000336,0.0288,0.000310
1,classwise,3.445554,0.018924,15.925437,0.488810,8.845279,0.296235,0.910559,0.000297,0.0136,0.000982
2,exact_coverage_classwise,3.479847,0.030276,19.459452,0.892685,7.518156,0.214756,0.897980,0.000435,0.0276,0.000839
3,cluster_random,2.596498,0.038149,16.365052,1.178874,6.469633,0.340526,0.901659,0.001300,0.0103,0.001543

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.060920,0.029904,12.731093,0.246655,7.944268,0.092258,0.899816,0.001174,0.053,0.006008
1,classwise,3.765921,0.049761,13.545768,1.012115,11.862752,0.202562,0.909124,0.000953,0.014,0.002098
2,exact_coverage_classwise,3.791604,0.060123,14.434829,1.086233,10.528324,0.163679,0.898244,0.001042,0.027,0.003178
3,cluster_random,2.910073,0.059641,11.881200,0.841146,9.315084,0.339112,0.903892,0.002606,0.011,0.002983

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.060920,0.029904,12.731093,0.246655,7.944268,0.092258,0.899816,0.001174,0.053,0.006008
1,classwise,3.765921,0.049761,13.545768,1.012115,11.862752,0.202562,0.909124,0.000953,0.014,0.002098
2,exact_coverage_classwise,3.791604,0.060123,14.434829,1.086233,10.528324,0.163679,0.898244,0.001042,0.027,0.003178
3,cluster_random,2.910073,0.059641,11.881200,0.841146,9.315084,0.339112,0.903892,0.002606,0.011,0.002983

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.060920,0.029904,12.731093,0.246655,7.944268,0.092258,0.899816,0.001174,0.053,0.006008
1,classwise,3.765921,0.049761,13.545768,1.012115,11.862752,0.202562,0.909124,0.000953,0.014,0.002098
2,exact_coverage_classwise,3.791604,0.060123,14.434829,1.086233,10.528324,0.163679,0.898244,0.001042,0.027,0.003178
3,cluster_random,2.910073,0.059641,11.881200,0.841146,9.315084,0.339112,0.903892,0.002606,0.011,0.002983

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.060920,0.029904,12.731093,0.246655,7.944268,0.092258,0.899816,0.001174,0.053,0.006008
1,classwise,3.765921,0.049761,13.545768,1.012115,11.862752,0.202562,0.909124,0.000953,0.014,0.002098
2,exact_coverage_classwise,3.791604,0.060123,14.434829,1.086233,10.528324,0.163679,0.898244,0.001042,0.027,0.003178
3,cluster_random,2.910073,0.059641,11.881200,0.841146,9.315084,0.339112,0.903892,0.002606,0.011,0.002983

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.794926,0.040595,13.969376,0.300137,11.015248,0.132524,0.899576,0.001049,0.040,0.004000
1,classwise,3.838417,0.055273,13.676308,0.758143,15.000924,0.232260,0.908252,0.001134,0.025,0.003536
2,exact_coverage_classwise,3.730261,0.049873,15.637185,0.968835,13.514544,0.198452,0.899048,0.001162,0.023,0.004012
3,cluster_random,3.124563,0.089137,12.263758,0.862369,12.172664,0.358775,0.902916,0.002286,0.015,0.004062

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.794926,0.040595,13.969376,0.300137,11.015248,0.132524,0.899576,0.001049,0.040,0.004000
1,classwise,3.838417,0.055273,13.676308,0.758143,15.000924,0.232260,0.908252,0.001134,0.025,0.003536
2,exact_coverage_classwise,3.730261,0.049873,15.637185,0.968835,13.514544,0.198452,0.899048,0.001162,0.023,0.004012
3,cluster_random,3.124563,0.089137,12.263758,0.862369,12.172664,0.358775,0.902916,0.002286,0.015,0.004062

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.794926,0.040595,13.969376,0.300137,11.015248,0.132524,0.899576,0.001049,0.040,0.004000
1,classwise,3.838417,0.055273,13.676308,0.758143,15.000924,0.232260,0.908252,0.001134,0.025,0.003536
2,exact_coverage_classwise,3.730261,0.049873,15.637185,0.968835,13.514544,0.198452,0.899048,0.001162,0.023,0.004012
3,cluster_random,3.124563,0.089137,12.263758,0.862369,12.172664,0.358775,0.902916,0.002286,0.015,0.004062

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.794926,0.040595,13.969376,0.300137,11.015248,0.132524,0.899576,0.001049,0.040,0.004000
1,classwise,3.838417,0.055273,13.676308,0.758143,15.000924,0.232260,0.908252,0.001134,0.025,0.003536
2,exact_coverage_classwise,3.730261,0.049873,15.637185,0.968835,13.514544,0.198452,0.899048,0.001162,0.023,0.004012
3,cluster_random,3.124563,0.089137,12.263758,0.862369,12.172664,0.358775,0.902916,0.002286,0.015,0.004062

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.818078,0.044583,15.632404,0.500775,8.282496,0.117101,0.900956,0.001256,0.071,0.005559
1,classwise,3.760621,0.058908,13.194248,0.715879,13.321652,0.209580,0.911844,0.001280,0.021,0.004111
2,exact_coverage_classwise,3.592576,0.073408,14.147541,0.535758,11.575912,0.149643,0.900752,0.000850,0.024,0.004290
3,cluster_random,3.653425,0.096456,14.782338,1.163044,9.532576,0.342673,0.902620,0.002749,0.028,0.005621

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.818078,0.044583,15.632404,0.500775,8.282496,0.117101,0.900956,0.001256,0.071,0.005559
1,classwise,3.760621,0.058908,13.194248,0.715879,13.321652,0.209580,0.911844,0.001280,0.021,0.004111
2,exact_coverage_classwise,3.592576,0.073408,14.147541,0.535758,11.575912,0.149643,0.900752,0.000850,0.024,0.004290
3,cluster_random,3.653425,0.096456,14.782338,1.163044,9.532576,0.342673,0.902620,0.002749,0.028,0.005621

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.818078,0.044583,15.632404,0.500775,8.282496,0.117101,0.900956,0.001256,0.071,0.005559
1,classwise,3.760621,0.058908,13.194248,0.715879,13.321652,0.209580,0.911844,0.001280,0.021,0.004111
2,exact_coverage_classwise,3.592576,0.073408,14.147541,0.535758,11.575912,0.149643,0.900752,0.000850,0.024,0.004290
3,cluster_random,3.653425,0.096456,14.782338,1.163044,9.532576,0.342673,0.902620,0.002749,0.028,0.005621

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.818078,0.044583,15.632404,0.500775,8.282496,0.117101,0.900956,0.001256,0.071,0.005559
1,classwise,3.760621,0.058908,13.194248,0.715879,13.321652,0.209580,0.911844,0.001280,0.021,0.004111
2,exact_coverage_classwise,3.592576,0.073408,14.147541,0.535758,11.575912,0.149643,0.900752,0.000850,0.024,0.004290
3,cluster_random,3.653425,0.096456,14.782338,1.163044,9.532576,0.342673,0.902620,0.002749,0.028,0.005621

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.557883,0.017559,22.226534,0.318183,6.894202,0.029251,0.900052,0.000528,0.066849,0.001826
1,classwise,3.529299,0.039731,14.194968,0.597971,10.119469,0.080556,0.910324,0.000498,0.013425,0.001473
2,exact_coverage_classwise,3.423322,0.036223,15.564736,0.537136,9.165539,0.063187,0.900046,0.000498,0.022192,0.002464
3,cluster_random,3.014302,0.048158,14.360796,0.904853,7.800403,0.093450,0.902192,0.001467,0.012329,0.002518

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.557883,0.017559,22.226534,0.318183,6.894202,0.029251,0.900052,0.000528,0.066849,0.001826
1,classwise,3.529299,0.039731,14.194968,0.597971,10.119469,0.080556,0.910324,0.000498,0.013425,0.001473
2,exact_coverage_classwise,3.423322,0.036223,15.564736,0.537136,9.165539,0.063187,0.900046,0.000498,0.022192,0.002464
3,cluster_random,3.014302,0.048158,14.360796,0.904853,7.800403,0.093450,0.902192,0.001467,0.012329,0.002518

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.557883,0.017559,22.226534,0.318183,6.894202,0.029251,0.900052,0.000528,0.066849,0.001826
1,classwise,3.529299,0.039731,14.194968,0.597971,10.119469,0.080556,0.910324,0.000498,0.013425,0.001473
2,exact_coverage_classwise,3.423322,0.036223,15.564736,0.537136,9.165539,0.063187,0.900046,0.000498,0.022192,0.002464
3,cluster_random,3.014302,0.048158,14.360796,0.904853,7.800403,0.093450,0.902192,0.001467,0.012329,0.002518

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.557883,0.017559,22.226534,0.318183,6.894202,0.029251,0.900052,0.000528,0.066849,0.001826
1,classwise,3.529299,0.039731,14.194968,0.597971,10.119469,0.080556,0.910324,0.000498,0.013425,0.001473
2,exact_coverage_classwise,3.423322,0.036223,15.564736,0.537136,9.165539,0.063187,0.900046,0.000498,0.022192,0.002464
3,cluster_random,3.014302,0.048158,14.360796,0.904853,7.800403,0.093450,0.902192,0.001467,0.012329,0.002518

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.266891,0.013101,17.715231,0.274245,10.810746,0.075307,0.900370,0.000887,0.029041,0.002363
1,classwise,3.540893,0.046500,14.109071,0.759182,14.420730,0.139286,0.910420,0.000669,0.014795,0.002605
2,exact_coverage_classwise,3.403042,0.046622,16.957535,0.958374,13.113461,0.105501,0.900157,0.000585,0.020274,0.001460
3,cluster_random,2.644636,0.042808,12.087248,0.636751,11.759405,0.140879,0.904021,0.001782,0.005479,0.001501

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.266891,0.013101,17.715231,0.274245,10.810746,0.075307,0.900370,0.000887,0.029041,0.002363
1,classwise,3.540893,0.046500,14.109071,0.759182,14.420730,0.139286,0.910420,0.000669,0.014795,0.002605
2,exact_coverage_classwise,3.403042,0.046622,16.957535,0.958374,13.113461,0.105501,0.900157,0.000585,0.020274,0.001460
3,cluster_random,2.644636,0.042808,12.087248,0.636751,11.759405,0.140879,0.904021,0.001782,0.005479,0.001501

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.266891,0.013101,17.715231,0.274245,10.810746,0.075307,0.900370,0.000887,0.029041,0.002363
1,classwise,3.540893,0.046500,14.109071,0.759182,14.420730,0.139286,0.910420,0.000669,0.014795,0.002605
2,exact_coverage_classwise,3.403042,0.046622,16.957535,0.958374,13.113461,0.105501,0.900157,0.000585,0.020274,0.001460
3,cluster_random,2.644636,0.042808,12.087248,0.636751,11.759405,0.140879,0.904021,0.001782,0.005479,0.001501

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.266891,0.013101,17.715231,0.274245,10.810746,0.075307,0.900370,0.000887,0.029041,0.002363
1,classwise,3.540893,0.046500,14.109071,0.759182,14.420730,0.139286,0.910420,0.000669,0.014795,0.002605
2,exact_coverage_classwise,3.403042,0.046622,16.957535,0.958374,13.113461,0.105501,0.900157,0.000585,0.020274,0.001460
3,cluster_random,2.644636,0.042808,12.087248,0.636751,11.759405,0.140879,0.904021,0.001782,0.005479,0.001501

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.829433,0.004131,20.486255,0.310308,7.913165,0.030951,0.899760,0.000710,0.044932,0.001945
1,classwise,3.557721,0.049719,14.685682,0.727140,11.415326,0.103420,0.910827,0.000494,0.014521,0.001860
2,exact_coverage_classwise,3.391069,0.059333,17.419136,0.997834,10.276352,0.075582,0.899894,0.000581,0.022740,0.002159
3,cluster_random,2.971410,0.037041,12.163625,0.724442,8.769927,0.091061,0.902991,0.001307,0.006575,0.001460

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.829433,0.004131,20.486255,0.310308,7.913165,0.030951,0.899760,0.000710,0.044932,0.001945
1,classwise,3.557721,0.049719,14.685682,0.727140,11.415326,0.103420,0.910827,0.000494,0.014521,0.001860
2,exact_coverage_classwise,3.391069,0.059333,17.419136,0.997834,10.276352,0.075582,0.899894,0.000581,0.022740,0.002159
3,cluster_random,2.971410,0.037041,12.163625,0.724442,8.769927,0.091061,0.902991,0.001307,0.006575,0.001460

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.829433,0.004131,20.486255,0.310308,7.913165,0.030951,0.899760,0.000710,0.044932,0.001945
1,classwise,3.557721,0.049719,14.685682,0.727140,11.415326,0.103420,0.910827,0.000494,0.014521,0.001860
2,exact_coverage_classwise,3.391069,0.059333,17.419136,0.997834,10.276352,0.075582,0.899894,0.000581,0.022740,0.002159
3,cluster_random,2.971410,0.037041,12.163625,0.724442,8.769927,0.091061,0.902991,0.001307,0.006575,0.001460

.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.829433,0.004131,20.486255,0.310308,7.913165,0.030951,0.899760,0.000710,0.044932,0.001945
1,classwise,3.557721,0.049719,14.685682,0.727140,11.415326,0.103420,0.910827,0.000494,0.014521,0.001860
2,exact_coverage_classwise,3.391069,0.059333,17.419136,0.997834,10.276352,0.075582,0.899894,0.000581,0.022740,0.002159
3,cluster_random,2.971410,0.037041,12.163625,0.724442,8.769927,0.091061,0.902991,0.001307,0.006575,0.001460

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.986350,0.051192,46.357924,0.486381,3.158427,0.022346,0.899590,0.000714,0.200000,0.003081
1,classwise,5.790269,0.025053,27.994279,1.754111,148.701598,2.213135,0.909733,0.000525,0.032701,0.002257
2,exact_coverage_classwise,4.985189,0.070685,36.700970,3.104787,56.711679,4.678566,0.899387,0.000488,0.080095,0.003322
3,cluster_random,5.714272,0.079176,46.128941,0.582503,3.719296,0.039736,0.896847,0.001393,0.141864,0.004853

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.986350,0.051192,46.357924,0.486381,3.158427,0.022346,0.899590,0.000714,0.200000,0.003081
1,classwise,5.790269,0.025053,27.994279,1.754111,148.701598,2.213135,0.909733,0.000525,0.032701,0.002257
2,exact_coverage_classwise,4.985189,0.070685,36.700970,3.104787,56.711679,4.678566,0.899387,0.000488,0.080095,0.003322
3,cluster_random,5.714272,0.079176,46.128941,0.582503,3.719296,0.039736,0.896847,0.001393,0.141864,0.004853

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.986350,0.051192,46.357924,0.486381,3.158427,0.022346,0.899590,0.000714,0.200000,0.003081
1,classwise,5.790269,0.025053,27.994279,1.754111,148.701598,2.213135,0.909733,0.000525,0.032701,0.002257
2,exact_coverage_classwise,4.985189,0.070685,36.700970,3.104787,56.711679,4.678566,0.899387,0.000488,0.080095,0.003322
3,cluster_random,5.714272,0.079176,46.128941,0.582503,3.719296,0.039736,0.896847,0.001393,0.141864,0.004853

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.986350,0.051192,46.357924,0.486381,3.158427,0.022346,0.899590,0.000714,0.200000,0.003081
1,classwise,5.790269,0.025053,27.994279,1.754111,148.701598,2.213135,0.909733,0.000525,0.032701,0.002257
2,exact_coverage_classwise,4.985189,0.070685,36.700970,3.104787,56.711679,4.678566,0.899387,0.000488,0.080095,0.003322
3,cluster_random,5.714272,0.079176,46.128941,0.582503,3.719296,0.039736,0.896847,0.001393,0.141864,0.004853

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.124665,0.029993,59.696853,0.310326,8.326705,0.044617,0.899428,0.000702,0.094787,0.001431
1,classwise,5.749162,0.031729,30.743042,2.630208,153.895984,2.169553,0.909410,0.000690,0.030964,0.002377
2,exact_coverage_classwise,5.598341,0.058992,50.867387,3.099753,107.921062,1.538270,0.899002,0.000686,0.096367,0.003940
3,cluster_random,3.920263,0.049843,60.151538,0.406266,8.459967,0.058875,0.896829,0.000934,0.079463,0.002246

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.124665,0.029993,59.696853,0.310326,8.326705,0.044617,0.899428,0.000702,0.094787,0.001431
1,classwise,5.749162,0.031729,30.743042,2.630208,153.895984,2.169553,0.909410,0.000690,0.030964,0.002377
2,exact_coverage_classwise,5.598341,0.058992,50.867387,3.099753,107.921062,1.538270,0.899002,0.000686,0.096367,0.003940
3,cluster_random,3.920263,0.049843,60.151538,0.406266,8.459967,0.058875,0.896829,0.000934,0.079463,0.002246

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.124665,0.029993,59.696853,0.310326,8.326705,0.044617,0.899428,0.000702,0.094787,0.001431
1,classwise,5.749162,0.031729,30.743042,2.630208,153.895984,2.169553,0.909410,0.000690,0.030964,0.002377
2,exact_coverage_classwise,5.598341,0.058992,50.867387,3.099753,107.921062,1.538270,0.899002,0.000686,0.096367,0.003940
3,cluster_random,3.920263,0.049843,60.151538,0.406266,8.459967,0.058875,0.896829,0.000934,0.079463,0.002246

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.124665,0.029993,59.696853,0.310326,8.326705,0.044617,0.899428,0.000702,0.094787,0.001431
1,classwise,5.749162,0.031729,30.743042,2.630208,153.895984,2.169553,0.909410,0.000690,0.030964,0.002377
2,exact_coverage_classwise,5.598341,0.058992,50.867387,3.099753,107.921062,1.538270,0.899002,0.000686,0.096367,0.003940
3,cluster_random,3.920263,0.049843,60.151538,0.406266,8.459967,0.058875,0.896829,0.000934,0.079463,0.002246

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.008053,0.022852,57.473321,0.189640,5.141045,0.013047,0.898621,0.000530,0.126540,0.002041
1,classwise,5.769286,0.034619,31.210096,2.576995,155.268758,2.308431,0.909784,0.000640,0.029068,0.002038
2,exact_coverage_classwise,5.642026,0.057736,50.973868,3.064480,107.988329,1.646475,0.898590,0.000668,0.096682,0.003166
3,cluster_random,4.548881,0.052214,57.647726,0.303686,5.379246,0.096459,0.895893,0.001107,0.105055,0.002991

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.008053,0.022852,57.473321,0.189640,5.141045,0.013047,0.898621,0.000530,0.126540,0.002041
1,classwise,5.769286,0.034619,31.210096,2.576995,155.268758,2.308431,0.909784,0.000640,0.029068,0.002038
2,exact_coverage_classwise,5.642026,0.057736,50.973868,3.064480,107.988329,1.646475,0.898590,0.000668,0.096682,0.003166
3,cluster_random,4.548881,0.052214,57.647726,0.303686,5.379246,0.096459,0.895893,0.001107,0.105055,0.002991

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.008053,0.022852,57.473321,0.189640,5.141045,0.013047,0.898621,0.000530,0.126540,0.002041
1,classwise,5.769286,0.034619,31.210096,2.576995,155.268758,2.308431,0.909784,0.000640,0.029068,0.002038
2,exact_coverage_classwise,5.642026,0.057736,50.973868,3.064480,107.988329,1.646475,0.898590,0.000668,0.096682,0.003166
3,cluster_random,4.548881,0.052214,57.647726,0.303686,5.379246,0.096459,0.895893,0.001107,0.105055,0.002991

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.008053,0.022852,57.473321,0.189640,5.141045,0.013047,0.898621,0.000530,0.126540,0.002041
1,classwise,5.769286,0.034619,31.210096,2.576995,155.268758,2.308431,0.909784,0.000640,0.029068,0.002038
2,exact_coverage_classwise,5.642026,0.057736,50.973868,3.064480,107.988329,1.646475,0.898590,0.000668,0.096682,0.003166
3,cluster_random,4.548881,0.052214,57.647726,0.303686,5.379246,0.096459,0.895893,0.001107,0.105055,0.002991

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.249914,0.015911,38.509857,0.159223,1.920399,0.009198,0.899465,0.000475,0.0825,0.001961
1,classwise,2.805084,0.020637,13.439692,0.591760,4.152084,0.054713,0.906443,0.000328,0.0058,0.000759
2,exact_coverage_classwise,2.762625,0.022787,14.487793,0.489791,3.720705,0.039989,0.899423,0.000343,0.0092,0.000903
3,cluster_random,2.763149,0.015632,14.988452,0.583557,2.712350,0.035263,0.900915,0.000556,0.0087,0.000722

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.249914,0.015911,38.509857,0.159223,1.920399,0.009198,0.899465,0.000475,0.0825,0.001961
1,classwise,2.805084,0.020637,13.439692,0.591760,4.152084,0.054713,0.906443,0.000328,0.0058,0.000759
2,exact_coverage_classwise,2.762625,0.022787,14.487793,0.489791,3.720705,0.039989,0.899423,0.000343,0.0092,0.000903
3,cluster_random,2.763149,0.015632,14.988452,0.583557,2.712350,0.035263,0.900915,0.000556,0.0087,0.000722

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.249914,0.015911,38.509857,0.159223,1.920399,0.009198,0.899465,0.000475,0.0825,0.001961
1,classwise,2.805084,0.020637,13.439692,0.591760,4.152084,0.054713,0.906443,0.000328,0.0058,0.000759
2,exact_coverage_classwise,2.762625,0.022787,14.487793,0.489791,3.720705,0.039989,0.899423,0.000343,0.0092,0.000903
3,cluster_random,2.763149,0.015632,14.988452,0.583557,2.712350,0.035263,0.900915,0.000556,0.0087,0.000722

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.249914,0.015911,38.509857,0.159223,1.920399,0.009198,0.899465,0.000475,0.0825,0.001961
1,classwise,2.805084,0.020637,13.439692,0.591760,4.152084,0.054713,0.906443,0.000328,0.0058,0.000759
2,exact_coverage_classwise,2.762625,0.022787,14.487793,0.489791,3.720705,0.039989,0.899423,0.000343,0.0092,0.000903
3,cluster_random,2.763149,0.015632,14.988452,0.583557,2.712350,0.035263,0.900915,0.000556,0.0087,0.000722

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.581067,0.003474,21.538192,0.124123,25.678643,0.084803,0.899664,0.000265,0.0214,0.000155
1,classwise,2.851441,0.018811,13.603989,0.508577,34.983663,0.171415,0.906735,0.000316,0.0056,0.000636
2,exact_coverage_classwise,2.795890,0.016251,14.776884,0.771453,31.684195,0.191259,0.899575,0.000346,0.0089,0.000974
3,cluster_random,2.202699,0.028626,13.803442,0.464076,27.309433,0.409062,0.900550,0.001175,0.0037,0.000584

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.581067,0.003474,21.538192,0.124123,25.678643,0.084803,0.899664,0.000265,0.0214,0.000155
1,classwise,2.851441,0.018811,13.603989,0.508577,34.983663,0.171415,0.906735,0.000316,0.0056,0.000636
2,exact_coverage_classwise,2.795890,0.016251,14.776884,0.771453,31.684195,0.191259,0.899575,0.000346,0.0089,0.000974
3,cluster_random,2.202699,0.028626,13.803442,0.464076,27.309433,0.409062,0.900550,0.001175,0.0037,0.000584

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.581067,0.003474,21.538192,0.124123,25.678643,0.084803,0.899664,0.000265,0.0214,0.000155
1,classwise,2.851441,0.018811,13.603989,0.508577,34.983663,0.171415,0.906735,0.000316,0.0056,0.000636
2,exact_coverage_classwise,2.795890,0.016251,14.776884,0.771453,31.684195,0.191259,0.899575,0.000346,0.0089,0.000974
3,cluster_random,2.202699,0.028626,13.803442,0.464076,27.309433,0.409062,0.900550,0.001175,0.0037,0.000584

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.581067,0.003474,21.538192,0.124123,25.678643,0.084803,0.899664,0.000265,0.0214,0.000155
1,classwise,2.851441,0.018811,13.603989,0.508577,34.983663,0.171415,0.906735,0.000316,0.0056,0.000636
2,exact_coverage_classwise,2.795890,0.016251,14.776884,0.771453,31.684195,0.191259,0.899575,0.000346,0.0089,0.000974
3,cluster_random,2.202699,0.028626,13.803442,0.464076,27.309433,0.409062,0.900550,0.001175,0.0037,0.000584

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.017877,0.001368,25.147991,0.113629,5.121456,0.006868,0.899513,0.000285,0.0294,0.000352
1,classwise,2.848706,0.023445,14.113776,0.622130,7.283570,0.105987,0.906942,0.000318,0.0058,0.000465
2,exact_coverage_classwise,2.766135,0.022122,15.318488,0.765670,6.641782,0.072250,0.899642,0.000424,0.0096,0.001321
3,cluster_random,2.399224,0.041172,13.596154,0.360776,6.813776,0.310162,0.900248,0.001033,0.0052,0.000525

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.017877,0.001368,25.147991,0.113629,5.121456,0.006868,0.899513,0.000285,0.0294,0.000352
1,classwise,2.848706,0.023445,14.113776,0.622130,7.283570,0.105987,0.906942,0.000318,0.0058,0.000465
2,exact_coverage_classwise,2.766135,0.022122,15.318488,0.765670,6.641782,0.072250,0.899642,0.000424,0.0096,0.001321
3,cluster_random,2.399224,0.041172,13.596154,0.360776,6.813776,0.310162,0.900248,0.001033,0.0052,0.000525

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.017877,0.001368,25.147991,0.113629,5.121456,0.006868,0.899513,0.000285,0.0294,0.000352
1,classwise,2.848706,0.023445,14.113776,0.622130,7.283570,0.105987,0.906942,0.000318,0.0058,0.000465
2,exact_coverage_classwise,2.766135,0.022122,15.318488,0.765670,6.641782,0.072250,0.899642,0.000424,0.0096,0.001321
3,cluster_random,2.399224,0.041172,13.596154,0.360776,6.813776,0.310162,0.900248,0.001033,0.0052,0.000525

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.017877,0.001368,25.147991,0.113629,5.121456,0.006868,0.899513,0.000285,0.0294,0.000352
1,classwise,2.848706,0.023445,14.113776,0.622130,7.283570,0.105987,0.906942,0.000318,0.0058,0.000465
2,exact_coverage_classwise,2.766135,0.022122,15.318488,0.765670,6.641782,0.072250,0.899642,0.000424,0.0096,0.001321
3,cluster_random,2.399224,0.041172,13.596154,0.360776,6.813776,0.310162,0.900248,0.001033,0.0052,0.000525

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.111595,0.031117,13.208247,0.387584,7.960422,0.086798,0.900089,0.001275,0.052,0.006293
1,classwise,3.230817,0.079223,11.833915,1.292336,10.767978,0.134374,0.906644,0.001146,0.007,0.002470
2,exact_coverage_classwise,3.225997,0.074284,12.371497,1.234871,9.991520,0.122216,0.899764,0.001137,0.011,0.003860
3,cluster_random,2.819645,0.024655,10.683185,1.004404,9.128711,0.154848,0.902351,0.001733,0.005,0.002121

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.111595,0.031117,13.208247,0.387584,7.960422,0.086798,0.900089,0.001275,0.052,0.006293
1,classwise,3.230817,0.079223,11.833915,1.292336,10.767978,0.134374,0.906644,0.001146,0.007,0.002470
2,exact_coverage_classwise,3.225997,0.074284,12.371497,1.234871,9.991520,0.122216,0.899764,0.001137,0.011,0.003860
3,cluster_random,2.819645,0.024655,10.683185,1.004404,9.128711,0.154848,0.902351,0.001733,0.005,0.002121

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.111595,0.031117,13.208247,0.387584,7.960422,0.086798,0.900089,0.001275,0.052,0.006293
1,classwise,3.230817,0.079223,11.833915,1.292336,10.767978,0.134374,0.906644,0.001146,0.007,0.002470
2,exact_coverage_classwise,3.225997,0.074284,12.371497,1.234871,9.991520,0.122216,0.899764,0.001137,0.011,0.003860
3,cluster_random,2.819645,0.024655,10.683185,1.004404,9.128711,0.154848,0.902351,0.001733,0.005,0.002121

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.111595,0.031117,13.208247,0.387584,7.960422,0.086798,0.900089,0.001275,0.052,0.006293
1,classwise,3.230817,0.079223,11.833915,1.292336,10.767978,0.134374,0.906644,0.001146,0.007,0.002470
2,exact_coverage_classwise,3.225997,0.074284,12.371497,1.234871,9.991520,0.122216,0.899764,0.001137,0.011,0.003860
3,cluster_random,2.819645,0.024655,10.683185,1.004404,9.128711,0.154848,0.902351,0.001733,0.005,0.002121

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.813230,0.044349,14.326751,0.488346,11.027729,0.103392,0.899978,0.000952,0.037,0.004701
1,classwise,3.172777,0.076518,12.509021,0.897185,13.689400,0.131919,0.906347,0.001031,0.009,0.001703
2,exact_coverage_classwise,3.117574,0.076255,11.140635,0.646733,12.759093,0.121567,0.899196,0.001065,0.016,0.003521
3,cluster_random,2.845385,0.073895,12.065695,0.530006,12.191720,0.244148,0.903587,0.001631,0.013,0.003178

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.813230,0.044349,14.326751,0.488346,11.027729,0.103392,0.899978,0.000952,0.037,0.004701
1,classwise,3.172777,0.076518,12.509021,0.897185,13.689400,0.131919,0.906347,0.001031,0.009,0.001703
2,exact_coverage_classwise,3.117574,0.076255,11.140635,0.646733,12.759093,0.121567,0.899196,0.001065,0.016,0.003521
3,cluster_random,2.845385,0.073895,12.065695,0.530006,12.191720,0.244148,0.903587,0.001631,0.013,0.003178

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.813230,0.044349,14.326751,0.488346,11.027729,0.103392,0.899978,0.000952,0.037,0.004701
1,classwise,3.172777,0.076518,12.509021,0.897185,13.689400,0.131919,0.906347,0.001031,0.009,0.001703
2,exact_coverage_classwise,3.117574,0.076255,11.140635,0.646733,12.759093,0.121567,0.899196,0.001065,0.016,0.003521
3,cluster_random,2.845385,0.073895,12.065695,0.530006,12.191720,0.244148,0.903587,0.001631,0.013,0.003178

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.813230,0.044349,14.326751,0.488346,11.027729,0.103392,0.899978,0.000952,0.037,0.004701
1,classwise,3.172777,0.076518,12.509021,0.897185,13.689400,0.131919,0.906347,0.001031,0.009,0.001703
2,exact_coverage_classwise,3.117574,0.076255,11.140635,0.646733,12.759093,0.121567,0.899196,0.001065,0.016,0.003521
3,cluster_random,2.845385,0.073895,12.065695,0.530006,12.191720,0.244148,0.903587,0.001631,0.013,0.003178

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.856711,0.050029,15.903742,0.566875,8.143880,0.122721,0.900653,0.001293,0.073,0.006790
1,classwise,3.290470,0.058563,12.776595,1.058569,12.066396,0.104426,0.908782,0.001077,0.009,0.002214
2,exact_coverage_classwise,3.237262,0.063672,12.042861,0.727317,10.950582,0.103904,0.900182,0.001128,0.013,0.003755
3,cluster_random,3.393141,0.078233,15.795460,0.803086,9.866116,0.124130,0.904022,0.001319,0.021,0.003302

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.856711,0.050029,15.903742,0.566875,8.143880,0.122721,0.900653,0.001293,0.073,0.006790
1,classwise,3.290470,0.058563,12.776595,1.058569,12.066396,0.104426,0.908782,0.001077,0.009,0.002214
2,exact_coverage_classwise,3.237262,0.063672,12.042861,0.727317,10.950582,0.103904,0.900182,0.001128,0.013,0.003755
3,cluster_random,3.393141,0.078233,15.795460,0.803086,9.866116,0.124130,0.904022,0.001319,0.021,0.003302

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.856711,0.050029,15.903742,0.566875,8.143880,0.122721,0.900653,0.001293,0.073,0.006790
1,classwise,3.290470,0.058563,12.776595,1.058569,12.066396,0.104426,0.908782,0.001077,0.009,0.002214
2,exact_coverage_classwise,3.237262,0.063672,12.042861,0.727317,10.950582,0.103904,0.900182,0.001128,0.013,0.003755
3,cluster_random,3.393141,0.078233,15.795460,0.803086,9.866116,0.124130,0.904022,0.001319,0.021,0.003302

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.856711,0.050029,15.903742,0.566875,8.143880,0.122721,0.900653,0.001293,0.073,0.006790
1,classwise,3.290470,0.058563,12.776595,1.058569,12.066396,0.104426,0.908782,0.001077,0.009,0.002214
2,exact_coverage_classwise,3.237262,0.063672,12.042861,0.727317,10.950582,0.103904,0.900182,0.001128,0.013,0.003755
3,cluster_random,3.393141,0.078233,15.795460,0.803086,9.866116,0.124130,0.904022,0.001319,0.021,0.003302

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.560404,0.017632,22.233482,0.302304,6.912210,0.023928,0.900348,0.000449,0.065205,0.001010
1,classwise,2.970193,0.021675,12.025111,0.539365,9.335470,0.064083,0.907208,0.000550,0.005479,0.001225
2,exact_coverage_classwise,2.930316,0.031854,13.227910,0.507832,8.736621,0.055953,0.900126,0.000583,0.010685,0.001752
3,cluster_random,2.861739,0.056389,13.270487,0.630777,7.876492,0.100794,0.901326,0.001121,0.010137,0.001503

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.560404,0.017632,22.233482,0.302304,6.912210,0.023928,0.900348,0.000449,0.065205,0.001010
1,classwise,2.970193,0.021675,12.025111,0.539365,9.335470,0.064083,0.907208,0.000550,0.005479,0.001225
2,exact_coverage_classwise,2.930316,0.031854,13.227910,0.507832,8.736621,0.055953,0.900126,0.000583,0.010685,0.001752
3,cluster_random,2.861739,0.056389,13.270487,0.630777,7.876492,0.100794,0.901326,0.001121,0.010137,0.001503

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.560404,0.017632,22.233482,0.302304,6.912210,0.023928,0.900348,0.000449,0.065205,0.001010
1,classwise,2.970193,0.021675,12.025111,0.539365,9.335470,0.064083,0.907208,0.000550,0.005479,0.001225
2,exact_coverage_classwise,2.930316,0.031854,13.227910,0.507832,8.736621,0.055953,0.900126,0.000583,0.010685,0.001752
3,cluster_random,2.861739,0.056389,13.270487,0.630777,7.876492,0.100794,0.901326,0.001121,0.010137,0.001503

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.560404,0.017632,22.233482,0.302304,6.912210,0.023928,0.900348,0.000449,0.065205,0.001010
1,classwise,2.970193,0.021675,12.025111,0.539365,9.335470,0.064083,0.907208,0.000550,0.005479,0.001225
2,exact_coverage_classwise,2.930316,0.031854,13.227910,0.507832,8.736621,0.055953,0.900126,0.000583,0.010685,0.001752
3,cluster_random,2.861739,0.056389,13.270487,0.630777,7.876492,0.100794,0.901326,0.001121,0.010137,0.001503

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.272919,0.009931,18.288718,0.277755,10.784092,0.051382,0.899891,0.000638,0.030959,0.001452
1,classwise,2.964360,0.024100,13.839720,0.734918,13.403690,0.080439,0.907011,0.000541,0.006301,0.000780
2,exact_coverage_classwise,2.945132,0.034288,14.356121,0.626955,12.592965,0.076103,0.899723,0.000588,0.010137,0.001552
3,cluster_random,2.697650,0.058367,12.206661,0.666917,11.632419,0.232729,0.899610,0.001844,0.008767,0.002842

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.272919,0.009931,18.288718,0.277755,10.784092,0.051382,0.899891,0.000638,0.030959,0.001452
1,classwise,2.964360,0.024100,13.839720,0.734918,13.403690,0.080439,0.907011,0.000541,0.006301,0.000780
2,exact_coverage_classwise,2.945132,0.034288,14.356121,0.626955,12.592965,0.076103,0.899723,0.000588,0.010137,0.001552
3,cluster_random,2.697650,0.058367,12.206661,0.666917,11.632419,0.232729,0.899610,0.001844,0.008767,0.002842

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.272919,0.009931,18.288718,0.277755,10.784092,0.051382,0.899891,0.000638,0.030959,0.001452
1,classwise,2.964360,0.024100,13.839720,0.734918,13.403690,0.080439,0.907011,0.000541,0.006301,0.000780
2,exact_coverage_classwise,2.945132,0.034288,14.356121,0.626955,12.592965,0.076103,0.899723,0.000588,0.010137,0.001552
3,cluster_random,2.697650,0.058367,12.206661,0.666917,11.632419,0.232729,0.899610,0.001844,0.008767,0.002842

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.272919,0.009931,18.288718,0.277755,10.784092,0.051382,0.899891,0.000638,0.030959,0.001452
1,classwise,2.964360,0.024100,13.839720,0.734918,13.403690,0.080439,0.907011,0.000541,0.006301,0.000780
2,exact_coverage_classwise,2.945132,0.034288,14.356121,0.626955,12.592965,0.076103,0.899723,0.000588,0.010137,0.001552
3,cluster_random,2.697650,0.058367,12.206661,0.666917,11.632419,0.232729,0.899610,0.001844,0.008767,0.002842

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.833976,0.005698,19.891162,0.267609,7.942699,0.019807,0.900272,0.000474,0.043562,0.001571
1,classwise,2.969699,0.031512,13.817297,0.808982,10.471721,0.083128,0.907536,0.000438,0.006301,0.001029
2,exact_coverage_classwise,2.935162,0.029303,14.493753,0.724531,9.824741,0.069656,0.900107,0.000553,0.010137,0.001345
3,cluster_random,2.924348,0.032836,12.648759,0.339402,8.962038,0.156656,0.899649,0.001555,0.007945,0.001523

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.833976,0.005698,19.891162,0.267609,7.942699,0.019807,0.900272,0.000474,0.043562,0.001571
1,classwise,2.969699,0.031512,13.817297,0.808982,10.471721,0.083128,0.907536,0.000438,0.006301,0.001029
2,exact_coverage_classwise,2.935162,0.029303,14.493753,0.724531,9.824741,0.069656,0.900107,0.000553,0.010137,0.001345
3,cluster_random,2.924348,0.032836,12.648759,0.339402,8.962038,0.156656,0.899649,0.001555,0.007945,0.001523

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.833976,0.005698,19.891162,0.267609,7.942699,0.019807,0.900272,0.000474,0.043562,0.001571
1,classwise,2.969699,0.031512,13.817297,0.808982,10.471721,0.083128,0.907536,0.000438,0.006301,0.001029
2,exact_coverage_classwise,2.935162,0.029303,14.493753,0.724531,9.824741,0.069656,0.900107,0.000553,0.010137,0.001345
3,cluster_random,2.924348,0.032836,12.648759,0.339402,8.962038,0.156656,0.899649,0.001555,0.007945,0.001523

.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.833976,0.005698,19.891162,0.267609,7.942699,0.019807,0.900272,0.000474,0.043562,0.001571
1,classwise,2.969699,0.031512,13.817297,0.808982,10.471721,0.083128,0.907536,0.000438,0.006301,0.001029
2,exact_coverage_classwise,2.935162,0.029303,14.493753,0.724531,9.824741,0.069656,0.900107,0.000553,0.010137,0.001345
3,cluster_random,2.924348,0.032836,12.648759,0.339402,8.962038,0.156656,0.899649,0.001555,0.007945,0.001523

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.972572,0.039347,46.215629,0.478789,3.162420,0.016724,0.899730,0.000538,0.198894,0.002029
1,classwise,4.838617,0.031674,30.939660,2.667140,55.312337,1.572485,0.906084,0.000583,0.034597,0.001253
2,exact_coverage_classwise,4.359521,0.035743,32.709788,2.316281,17.866577,0.516115,0.899499,0.000588,0.063665,0.002072
3,cluster_random,5.314805,0.075520,46.777539,0.480995,3.751900,0.028016,0.897918,0.000636,0.130490,0.004234

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.972572,0.039347,46.215629,0.478789,3.162420,0.016724,0.899730,0.000538,0.198894,0.002029
1,classwise,4.838617,0.031674,30.939660,2.667140,55.312337,1.572485,0.906084,0.000583,0.034597,0.001253
2,exact_coverage_classwise,4.359521,0.035743,32.709788,2.316281,17.866577,0.516115,0.899499,0.000588,0.063665,0.002072
3,cluster_random,5.314805,0.075520,46.777539,0.480995,3.751900,0.028016,0.897918,0.000636,0.130490,0.004234

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.972572,0.039347,46.215629,0.478789,3.162420,0.016724,0.899730,0.000538,0.198894,0.002029
1,classwise,4.838617,0.031674,30.939660,2.667140,55.312337,1.572485,0.906084,0.000583,0.034597,0.001253
2,exact_coverage_classwise,4.359521,0.035743,32.709788,2.316281,17.866577,0.516115,0.899499,0.000588,0.063665,0.002072
3,cluster_random,5.314805,0.075520,46.777539,0.480995,3.751900,0.028016,0.897918,0.000636,0.130490,0.004234

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.972572,0.039347,46.215629,0.478789,3.162420,0.016724,0.899730,0.000538,0.198894,0.002029
1,classwise,4.838617,0.031674,30.939660,2.667140,55.312337,1.572485,0.906084,0.000583,0.034597,0.001253
2,exact_coverage_classwise,4.359521,0.035743,32.709788,2.316281,17.866577,0.516115,0.899499,0.000588,0.063665,0.002072
3,cluster_random,5.314805,0.075520,46.777539,0.480995,3.751900,0.028016,0.897918,0.000636,0.130490,0.004234

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.166114,0.022271,59.660843,0.213661,8.332199,0.030000,0.899429,0.000475,0.099210,0.001240
1,classwise,4.759949,0.039305,28.125582,1.349976,60.695288,1.541884,0.906200,0.000415,0.032859,0.002093
2,exact_coverage_classwise,4.917963,0.043731,44.254840,2.616720,47.467763,1.116878,0.897854,0.000530,0.082938,0.002881
3,cluster_random,3.523028,0.042416,59.532954,0.556044,8.668709,0.072714,0.897923,0.000913,0.058136,0.001113

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.166114,0.022271,59.660843,0.213661,8.332199,0.030000,0.899429,0.000475,0.099210,0.001240
1,classwise,4.759949,0.039305,28.125582,1.349976,60.695288,1.541884,0.906200,0.000415,0.032859,0.002093
2,exact_coverage_classwise,4.917963,0.043731,44.254840,2.616720,47.467763,1.116878,0.897854,0.000530,0.082938,0.002881
3,cluster_random,3.523028,0.042416,59.532954,0.556044,8.668709,0.072714,0.897923,0.000913,0.058136,0.001113

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.166114,0.022271,59.660843,0.213661,8.332199,0.030000,0.899429,0.000475,0.099210,0.001240
1,classwise,4.759949,0.039305,28.125582,1.349976,60.695288,1.541884,0.906200,0.000415,0.032859,0.002093
2,exact_coverage_classwise,4.917963,0.043731,44.254840,2.616720,47.467763,1.116878,0.897854,0.000530,0.082938,0.002881
3,cluster_random,3.523028,0.042416,59.532954,0.556044,8.668709,0.072714,0.897923,0.000913,0.058136,0.001113

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.166114,0.022271,59.660843,0.213661,8.332199,0.030000,0.899429,0.000475,0.099210,0.001240
1,classwise,4.759949,0.039305,28.125582,1.349976,60.695288,1.541884,0.906200,0.000415,0.032859,0.002093
2,exact_coverage_classwise,4.917963,0.043731,44.254840,2.616720,47.467763,1.116878,0.897854,0.000530,0.082938,0.002881
3,cluster_random,3.523028,0.042416,59.532954,0.556044,8.668709,0.072714,0.897923,0.000913,0.058136,0.001113

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.962075,0.018908,56.892585,0.233436,5.158425,0.011148,0.899221,0.000467,0.127488,0.001323
1,classwise,4.856312,0.043951,27.448262,1.082188,63.111438,1.672252,0.906876,0.000483,0.032385,0.002134
2,exact_coverage_classwise,4.935755,0.038724,44.206906,2.670780,47.553624,1.161345,0.897997,0.000563,0.083728,0.003321
3,cluster_random,4.104375,0.054755,57.146218,0.295667,5.424337,0.057444,0.897728,0.000859,0.082780,0.002819

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.962075,0.018908,56.892585,0.233436,5.158425,0.011148,0.899221,0.000467,0.127488,0.001323
1,classwise,4.856312,0.043951,27.448262,1.082188,63.111438,1.672252,0.906876,0.000483,0.032385,0.002134
2,exact_coverage_classwise,4.935755,0.038724,44.206906,2.670780,47.553624,1.161345,0.897997,0.000563,0.083728,0.003321
3,cluster_random,4.104375,0.054755,57.146218,0.295667,5.424337,0.057444,0.897728,0.000859,0.082780,0.002819

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.962075,0.018908,56.892585,0.233436,5.158425,0.011148,0.899221,0.000467,0.127488,0.001323
1,classwise,4.856312,0.043951,27.448262,1.082188,63.111438,1.672252,0.906876,0.000483,0.032385,0.002134
2,exact_coverage_classwise,4.935755,0.038724,44.206906,2.670780,47.553624,1.161345,0.897997,0.000563,0.083728,0.003321
3,cluster_random,4.104375,0.054755,57.146218,0.295667,5.424337,0.057444,0.897728,0.000859,0.082780,0.002819

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.962075,0.018908,56.892585,0.233436,5.158425,0.011148,0.899221,0.000467,0.127488,0.001323
1,classwise,4.856312,0.043951,27.448262,1.082188,63.111438,1.672252,0.906876,0.000483,0.032385,0.002134
2,exact_coverage_classwise,4.935755,0.038724,44.206906,2.670780,47.553624,1.161345,0.897997,0.000563,0.083728,0.003321
3,cluster_random,4.104375,0.054755,57.146218,0.295667,5.424337,0.057444,0.897728,0.000859,0.082780,0.002819

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242778,0.012538,38.537079,0.157907,1.924413,0.006665,0.899658,0.000349,0.0811,0.001438
1,classwise,2.465621,0.015974,11.209694,0.278355,3.797044,0.044281,0.904970,0.000286,0.0017,0.000285
2,exact_coverage_classwise,2.443997,0.013280,11.661292,0.394241,3.520642,0.033815,0.899689,0.000278,0.0025,0.000381
3,cluster_random,2.681849,0.028519,13.867107,0.833045,2.817181,0.046017,0.901719,0.000706,0.0047,0.000549

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242778,0.012538,38.537079,0.157907,1.924413,0.006665,0.899658,0.000349,0.0811,0.001438
1,classwise,2.465621,0.015974,11.209694,0.278355,3.797044,0.044281,0.904970,0.000286,0.0017,0.000285
2,exact_coverage_classwise,2.443997,0.013280,11.661292,0.394241,3.520642,0.033815,0.899689,0.000278,0.0025,0.000381
3,cluster_random,2.681849,0.028519,13.867107,0.833045,2.817181,0.046017,0.901719,0.000706,0.0047,0.000549

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242778,0.012538,38.537079,0.157907,1.924413,0.006665,0.899658,0.000349,0.0811,0.001438
1,classwise,2.465621,0.015974,11.209694,0.278355,3.797044,0.044281,0.904970,0.000286,0.0017,0.000285
2,exact_coverage_classwise,2.443997,0.013280,11.661292,0.394241,3.520642,0.033815,0.899689,0.000278,0.0025,0.000381
3,cluster_random,2.681849,0.028519,13.867107,0.833045,2.817181,0.046017,0.901719,0.000706,0.0047,0.000549

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242778,0.012538,38.537079,0.157907,1.924413,0.006665,0.899658,0.000349,0.0811,0.001438
1,classwise,2.465621,0.015974,11.209694,0.278355,3.797044,0.044281,0.904970,0.000286,0.0017,0.000285
2,exact_coverage_classwise,2.443997,0.013280,11.661292,0.394241,3.520642,0.033815,0.899689,0.000278,0.0025,0.000381
3,cluster_random,2.681849,0.028519,13.867107,0.833045,2.817181,0.046017,0.901719,0.000706,0.0047,0.000549

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.614190,0.005127,20.780348,0.156898,25.779347,0.089519,0.900182,0.000277,0.0214,0.000290
1,classwise,2.480902,0.012071,11.552075,0.590565,32.667352,0.158516,0.905115,0.000402,0.0018,0.000395
2,exact_coverage_classwise,2.472559,0.016993,12.257048,0.280491,30.673702,0.158500,0.899855,0.000251,0.0042,0.000660
3,cluster_random,2.157972,0.034725,11.703002,0.617397,28.328017,0.397642,0.901459,0.000992,0.0016,0.000352

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.614190,0.005127,20.780348,0.156898,25.779347,0.089519,0.900182,0.000277,0.0214,0.000290
1,classwise,2.480902,0.012071,11.552075,0.590565,32.667352,0.158516,0.905115,0.000402,0.0018,0.000395
2,exact_coverage_classwise,2.472559,0.016993,12.257048,0.280491,30.673702,0.158500,0.899855,0.000251,0.0042,0.000660
3,cluster_random,2.157972,0.034725,11.703002,0.617397,28.328017,0.397642,0.901459,0.000992,0.0016,0.000352

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.614190,0.005127,20.780348,0.156898,25.779347,0.089519,0.900182,0.000277,0.0214,0.000290
1,classwise,2.480902,0.012071,11.552075,0.590565,32.667352,0.158516,0.905115,0.000402,0.0018,0.000395
2,exact_coverage_classwise,2.472559,0.016993,12.257048,0.280491,30.673702,0.158500,0.899855,0.000251,0.0042,0.000660
3,cluster_random,2.157972,0.034725,11.703002,0.617397,28.328017,0.397642,0.901459,0.000992,0.0016,0.000352

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.614190,0.005127,20.780348,0.156898,25.779347,0.089519,0.900182,0.000277,0.0214,0.000290
1,classwise,2.480902,0.012071,11.552075,0.590565,32.667352,0.158516,0.905115,0.000402,0.0018,0.000395
2,exact_coverage_classwise,2.472559,0.016993,12.257048,0.280491,30.673702,0.158500,0.899855,0.000251,0.0042,0.000660
3,cluster_random,2.157972,0.034725,11.703002,0.617397,28.328017,0.397642,0.901459,0.000992,0.0016,0.000352

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.040469,0.003320,24.997044,0.111289,5.119820,0.007813,0.899816,0.000315,0.0289,0.000435
1,classwise,2.477937,0.014758,11.191192,0.560871,6.701842,0.059410,0.905289,0.000337,0.0015,0.000381
2,exact_coverage_classwise,2.430355,0.016188,11.963652,0.421001,6.312464,0.055022,0.899375,0.000446,0.0037,0.000448
3,cluster_random,2.283788,0.028863,15.576640,1.588829,6.789395,0.330868,0.902029,0.000677,0.0031,0.000263

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.040469,0.003320,24.997044,0.111289,5.119820,0.007813,0.899816,0.000315,0.0289,0.000435
1,classwise,2.477937,0.014758,11.191192,0.560871,6.701842,0.059410,0.905289,0.000337,0.0015,0.000381
2,exact_coverage_classwise,2.430355,0.016188,11.963652,0.421001,6.312464,0.055022,0.899375,0.000446,0.0037,0.000448
3,cluster_random,2.283788,0.028863,15.576640,1.588829,6.789395,0.330868,0.902029,0.000677,0.0031,0.000263

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.040469,0.003320,24.997044,0.111289,5.119820,0.007813,0.899816,0.000315,0.0289,0.000435
1,classwise,2.477937,0.014758,11.191192,0.560871,6.701842,0.059410,0.905289,0.000337,0.0015,0.000381
2,exact_coverage_classwise,2.430355,0.016188,11.963652,0.421001,6.312464,0.055022,0.899375,0.000446,0.0037,0.000448
3,cluster_random,2.283788,0.028863,15.576640,1.588829,6.789395,0.330868,0.902029,0.000677,0.0031,0.000263

.cache/paper/varying_n/imagenet/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.040469,0.003320,24.997044,0.111289,5.119820,0.007813,0.899816,0.000315,0.0289,0.000435
1,classwise,2.477937,0.014758,11.191192,0.560871,6.701842,0.059410,0.905289,0.000337,0.0015,0.000381
2,exact_coverage_classwise,2.430355,0.016188,11.963652,0.421001,6.312464,0.055022,0.899375,0.000446,0.0037,0.000448
3,cluster_random,2.283788,0.028863,15.576640,1.588829,6.789395,0.330868,0.902029,0.000677,0.0031,0.000263

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.119572,0.034184,13.387283,0.427891,7.966615,0.069460,0.900275,0.001180,0.052,0.004858
1,classwise,3.094629,0.053170,10.518702,0.385617,10.342665,0.097396,0.905600,0.001079,0.008,0.002366
2,exact_coverage_classwise,3.015251,0.071099,10.967288,0.429058,9.695905,0.087418,0.899655,0.001138,0.011,0.002214
3,cluster_random,2.763099,0.083642,10.543952,0.577034,9.030770,0.147186,0.900080,0.001674,0.008,0.002366

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.119572,0.034184,13.387283,0.427891,7.966615,0.069460,0.900275,0.001180,0.052,0.004858
1,classwise,3.094629,0.053170,10.518702,0.385617,10.342665,0.097396,0.905600,0.001079,0.008,0.002366
2,exact_coverage_classwise,3.015251,0.071099,10.967288,0.429058,9.695905,0.087418,0.899655,0.001138,0.011,0.002214
3,cluster_random,2.763099,0.083642,10.543952,0.577034,9.030770,0.147186,0.900080,0.001674,0.008,0.002366

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.119572,0.034184,13.387283,0.427891,7.966615,0.069460,0.900275,0.001180,0.052,0.004858
1,classwise,3.094629,0.053170,10.518702,0.385617,10.342665,0.097396,0.905600,0.001079,0.008,0.002366
2,exact_coverage_classwise,3.015251,0.071099,10.967288,0.429058,9.695905,0.087418,0.899655,0.001138,0.011,0.002214
3,cluster_random,2.763099,0.083642,10.543952,0.577034,9.030770,0.147186,0.900080,0.001674,0.008,0.002366

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.119572,0.034184,13.387283,0.427891,7.966615,0.069460,0.900275,0.001180,0.052,0.004858
1,classwise,3.094629,0.053170,10.518702,0.385617,10.342665,0.097396,0.905600,0.001079,0.008,0.002366
2,exact_coverage_classwise,3.015251,0.071099,10.967288,0.429058,9.695905,0.087418,0.899655,0.001138,0.011,0.002214
3,cluster_random,2.763099,0.083642,10.543952,0.577034,9.030770,0.147186,0.900080,0.001674,0.008,0.002366

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.812391,0.042193,15.117395,0.401028,10.946145,0.093817,0.899830,0.001022,0.040,0.006325
1,classwise,2.978894,0.056977,10.154125,0.560990,13.143000,0.101819,0.904840,0.000788,0.007,0.002025
2,exact_coverage_classwise,3.038475,0.065312,11.409277,0.557182,12.485800,0.097469,0.899190,0.000870,0.013,0.002846
3,cluster_random,2.930715,0.063727,10.657047,0.551630,11.920490,0.178853,0.901305,0.001239,0.007,0.002025

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.812391,0.042193,15.117395,0.401028,10.946145,0.093817,0.899830,0.001022,0.040,0.006325
1,classwise,2.978894,0.056977,10.154125,0.560990,13.143000,0.101819,0.904840,0.000788,0.007,0.002025
2,exact_coverage_classwise,3.038475,0.065312,11.409277,0.557182,12.485800,0.097469,0.899190,0.000870,0.013,0.002846
3,cluster_random,2.930715,0.063727,10.657047,0.551630,11.920490,0.178853,0.901305,0.001239,0.007,0.002025

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.812391,0.042193,15.117395,0.401028,10.946145,0.093817,0.899830,0.001022,0.040,0.006325
1,classwise,2.978894,0.056977,10.154125,0.560990,13.143000,0.101819,0.904840,0.000788,0.007,0.002025
2,exact_coverage_classwise,3.038475,0.065312,11.409277,0.557182,12.485800,0.097469,0.899190,0.000870,0.013,0.002846
3,cluster_random,2.930715,0.063727,10.657047,0.551630,11.920490,0.178853,0.901305,0.001239,0.007,0.002025

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.812391,0.042193,15.117395,0.401028,10.946145,0.093817,0.899830,0.001022,0.040,0.006325
1,classwise,2.978894,0.056977,10.154125,0.560990,13.143000,0.101819,0.904840,0.000788,0.007,0.002025
2,exact_coverage_classwise,3.038475,0.065312,11.409277,0.557182,12.485800,0.097469,0.899190,0.000870,0.013,0.002846
3,cluster_random,2.930715,0.063727,10.657047,0.551630,11.920490,0.178853,0.901305,0.001239,0.007,0.002025

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.863804,0.054550,16.379331,0.597220,8.104390,0.096634,0.900350,0.000989,0.082,0.006450
1,classwise,2.948013,0.065618,10.081555,0.500922,11.506280,0.073277,0.907125,0.000822,0.005,0.002121
2,exact_coverage_classwise,2.980446,0.067934,11.112055,0.583004,10.707510,0.069505,0.900260,0.000873,0.012,0.003406
3,cluster_random,3.330569,0.075442,13.019999,0.834952,9.679685,0.155517,0.902045,0.001010,0.016,0.003795

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.863804,0.054550,16.379331,0.597220,8.104390,0.096634,0.900350,0.000989,0.082,0.006450
1,classwise,2.948013,0.065618,10.081555,0.500922,11.506280,0.073277,0.907125,0.000822,0.005,0.002121
2,exact_coverage_classwise,2.980446,0.067934,11.112055,0.583004,10.707510,0.069505,0.900260,0.000873,0.012,0.003406
3,cluster_random,3.330569,0.075442,13.019999,0.834952,9.679685,0.155517,0.902045,0.001010,0.016,0.003795

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.863804,0.054550,16.379331,0.597220,8.104390,0.096634,0.900350,0.000989,0.082,0.006450
1,classwise,2.948013,0.065618,10.081555,0.500922,11.506280,0.073277,0.907125,0.000822,0.005,0.002121
2,exact_coverage_classwise,2.980446,0.067934,11.112055,0.583004,10.707510,0.069505,0.900260,0.000873,0.012,0.003406
3,cluster_random,3.330569,0.075442,13.019999,0.834952,9.679685,0.155517,0.902045,0.001010,0.016,0.003795

.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.863804,0.054550,16.379331,0.597220,8.104390,0.096634,0.900350,0.000989,0.082,0.006450
1,classwise,2.948013,0.065618,10.081555,0.500922,11.506280,0.073277,0.907125,0.000822,0.005,0.002121
2,exact_coverage_classwise,2.980446,0.067934,11.112055,0.583004,10.707510,0.069505,0.900260,0.000873,0.012,0.003406
3,cluster_random,3.330569,0.075442,13.019999,0.834952,9.679685,0.155517,0.902045,0.001010,0.016,0.003795

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.572543,0.020716,22.306765,0.351514,6.900628,0.021776,0.900165,0.000441,0.067397,0.001945
1,classwise,2.652156,0.014817,10.943113,0.530231,8.935379,0.034499,0.905277,0.000429,0.003014,0.000817
2,exact_coverage_classwise,2.629220,0.024192,11.655405,0.535149,8.500896,0.027548,0.899984,0.000425,0.004658,0.001228
3,cluster_random,2.775579,0.037611,12.307948,0.560455,7.887547,0.064034,0.901519,0.000830,0.008493,0.001794

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.572543,0.020716,22.306765,0.351514,6.900628,0.021776,0.900165,0.000441,0.067397,0.001945
1,classwise,2.652156,0.014817,10.943113,0.530231,8.935379,0.034499,0.905277,0.000429,0.003014,0.000817
2,exact_coverage_classwise,2.629220,0.024192,11.655405,0.535149,8.500896,0.027548,0.899984,0.000425,0.004658,0.001228
3,cluster_random,2.775579,0.037611,12.307948,0.560455,7.887547,0.064034,0.901519,0.000830,0.008493,0.001794

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.572543,0.020716,22.306765,0.351514,6.900628,0.021776,0.900165,0.000441,0.067397,0.001945
1,classwise,2.652156,0.014817,10.943113,0.530231,8.935379,0.034499,0.905277,0.000429,0.003014,0.000817
2,exact_coverage_classwise,2.629220,0.024192,11.655405,0.535149,8.500896,0.027548,0.899984,0.000425,0.004658,0.001228
3,cluster_random,2.775579,0.037611,12.307948,0.560455,7.887547,0.064034,0.901519,0.000830,0.008493,0.001794

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.572543,0.020716,22.306765,0.351514,6.900628,0.021776,0.900165,0.000441,0.067397,0.001945
1,classwise,2.652156,0.014817,10.943113,0.530231,8.935379,0.034499,0.905277,0.000429,0.003014,0.000817
2,exact_coverage_classwise,2.629220,0.024192,11.655405,0.535149,8.500896,0.027548,0.899984,0.000425,0.004658,0.001228
3,cluster_random,2.775579,0.037611,12.307948,0.560455,7.887547,0.064034,0.901519,0.000830,0.008493,0.001794

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.303463,0.009064,17.754645,0.400080,10.793352,0.033523,0.899977,0.000408,0.029863,0.001058
1,classwise,2.690646,0.025009,11.179192,0.477443,12.903510,0.063268,0.904865,0.000511,0.004110,0.001240
2,exact_coverage_classwise,2.629972,0.027662,12.144940,0.556743,12.355778,0.056476,0.900081,0.000588,0.007945,0.001473
3,cluster_random,2.489284,0.026029,11.787469,0.621645,11.774565,0.083308,0.902581,0.000897,0.003562,0.000871

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.303463,0.009064,17.754645,0.400080,10.793352,0.033523,0.899977,0.000408,0.029863,0.001058
1,classwise,2.690646,0.025009,11.179192,0.477443,12.903510,0.063268,0.904865,0.000511,0.004110,0.001240
2,exact_coverage_classwise,2.629972,0.027662,12.144940,0.556743,12.355778,0.056476,0.900081,0.000588,0.007945,0.001473
3,cluster_random,2.489284,0.026029,11.787469,0.621645,11.774565,0.083308,0.902581,0.000897,0.003562,0.000871

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.303463,0.009064,17.754645,0.400080,10.793352,0.033523,0.899977,0.000408,0.029863,0.001058
1,classwise,2.690646,0.025009,11.179192,0.477443,12.903510,0.063268,0.904865,0.000511,0.004110,0.001240
2,exact_coverage_classwise,2.629972,0.027662,12.144940,0.556743,12.355778,0.056476,0.900081,0.000588,0.007945,0.001473
3,cluster_random,2.489284,0.026029,11.787469,0.621645,11.774565,0.083308,0.902581,0.000897,0.003562,0.000871

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.303463,0.009064,17.754645,0.400080,10.793352,0.033523,0.899977,0.000408,0.029863,0.001058
1,classwise,2.690646,0.025009,11.179192,0.477443,12.903510,0.063268,0.904865,0.000511,0.004110,0.001240
2,exact_coverage_classwise,2.629972,0.027662,12.144940,0.556743,12.355778,0.056476,0.900081,0.000588,0.007945,0.001473
3,cluster_random,2.489284,0.026029,11.787469,0.621645,11.774565,0.083308,0.902581,0.000897,0.003562,0.000871

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.869336,0.012955,20.065445,0.365164,7.926725,0.012907,0.900077,0.000335,0.044384,0.001273
1,classwise,2.692525,0.034933,11.087893,0.502067,10.004633,0.044644,0.905136,0.000392,0.004110,0.000888
2,exact_coverage_classwise,2.638237,0.028719,12.439342,0.609643,9.547110,0.039759,0.899790,0.000451,0.006849,0.001700
3,cluster_random,2.659262,0.034814,12.172531,0.878118,9.206979,0.131179,0.903605,0.000713,0.004110,0.001356

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.869336,0.012955,20.065445,0.365164,7.926725,0.012907,0.900077,0.000335,0.044384,0.001273
1,classwise,2.692525,0.034933,11.087893,0.502067,10.004633,0.044644,0.905136,0.000392,0.004110,0.000888
2,exact_coverage_classwise,2.638237,0.028719,12.439342,0.609643,9.547110,0.039759,0.899790,0.000451,0.006849,0.001700
3,cluster_random,2.659262,0.034814,12.172531,0.878118,9.206979,0.131179,0.903605,0.000713,0.004110,0.001356

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.869336,0.012955,20.065445,0.365164,7.926725,0.012907,0.900077,0.000335,0.044384,0.001273
1,classwise,2.692525,0.034933,11.087893,0.502067,10.004633,0.044644,0.905136,0.000392,0.004110,0.000888
2,exact_coverage_classwise,2.638237,0.028719,12.439342,0.609643,9.547110,0.039759,0.899790,0.000451,0.006849,0.001700
3,cluster_random,2.659262,0.034814,12.172531,0.878118,9.206979,0.131179,0.903605,0.000713,0.004110,0.001356

.cache/paper/varying_n/places365/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.869336,0.012955,20.065445,0.365164,7.926725,0.012907,0.900077,0.000335,0.044384,0.001273
1,classwise,2.692525,0.034933,11.087893,0.502067,10.004633,0.044644,0.905136,0.000392,0.004110,0.000888
2,exact_coverage_classwise,2.638237,0.028719,12.439342,0.609643,9.547110,0.039759,0.899790,0.000451,0.006849,0.001700
3,cluster_random,2.659262,0.034814,12.172531,0.878118,9.206979,0.131179,0.903605,0.000713,0.004110,0.001356

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.940603,0.031913,45.893375,0.366965,3.176720,0.014032,0.900198,0.000450,0.197788,0.001561
1,classwise,4.183294,0.028249,26.520752,1.553154,18.384405,0.856141,0.904913,0.000524,0.027330,0.001581
2,exact_coverage_classwise,3.902134,0.041868,29.200923,1.488039,8.224688,0.215610,0.899862,0.000500,0.049921,0.002038
3,cluster_random,4.434192,0.034756,37.565468,2.412766,4.064241,0.052368,0.899649,0.000805,0.087204,0.001220

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.940603,0.031913,45.893375,0.366965,3.176720,0.014032,0.900198,0.000450,0.197788,0.001561
1,classwise,4.183294,0.028249,26.520752,1.553154,18.384405,0.856141,0.904913,0.000524,0.027330,0.001581
2,exact_coverage_classwise,3.902134,0.041868,29.200923,1.488039,8.224688,0.215610,0.899862,0.000500,0.049921,0.002038
3,cluster_random,4.434192,0.034756,37.565468,2.412766,4.064241,0.052368,0.899649,0.000805,0.087204,0.001220

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.940603,0.031913,45.893375,0.366965,3.176720,0.014032,0.900198,0.000450,0.197788,0.001561
1,classwise,4.183294,0.028249,26.520752,1.553154,18.384405,0.856141,0.904913,0.000524,0.027330,0.001581
2,exact_coverage_classwise,3.902134,0.041868,29.200923,1.488039,8.224688,0.215610,0.899862,0.000500,0.049921,0.002038
3,cluster_random,4.434192,0.034756,37.565468,2.412766,4.064241,0.052368,0.899649,0.000805,0.087204,0.001220

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=softmax/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.940603,0.031913,45.893375,0.366965,3.176720,0.014032,0.900198,0.000450,0.197788,0.001561
1,classwise,4.183294,0.028249,26.520752,1.553154,18.384405,0.856141,0.904913,0.000524,0.027330,0.001581
2,exact_coverage_classwise,3.902134,0.041868,29.200923,1.488039,8.224688,0.215610,0.899862,0.000500,0.049921,0.002038
3,cluster_random,4.434192,0.034756,37.565468,2.412766,4.064241,0.052368,0.899649,0.000805,0.087204,0.001220

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.213930,0.023629,58.030344,0.262887,8.324444,0.035928,0.899412,0.000576,0.094945,0.001105
1,classwise,4.114650,0.033201,26.852969,1.686095,23.862054,0.859265,0.904764,0.000473,0.026382,0.002672
2,exact_coverage_classwise,3.819427,0.062352,32.342359,1.911328,13.345779,0.218138,0.899735,0.000413,0.048815,0.002925
3,cluster_random,3.050733,0.051273,46.170372,3.937213,8.924488,0.044187,0.898896,0.000658,0.036967,0.002225

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.213930,0.023629,58.030344,0.262887,8.324444,0.035928,0.899412,0.000576,0.094945,0.001105
1,classwise,4.114650,0.033201,26.852969,1.686095,23.862054,0.859265,0.904764,0.000473,0.026382,0.002672
2,exact_coverage_classwise,3.819427,0.062352,32.342359,1.911328,13.345779,0.218138,0.899735,0.000413,0.048815,0.002925
3,cluster_random,3.050733,0.051273,46.170372,3.937213,8.924488,0.044187,0.898896,0.000658,0.036967,0.002225

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.213930,0.023629,58.030344,0.262887,8.324444,0.035928,0.899412,0.000576,0.094945,0.001105
1,classwise,4.114650,0.033201,26.852969,1.686095,23.862054,0.859265,0.904764,0.000473,0.026382,0.002672
2,exact_coverage_classwise,3.819427,0.062352,32.342359,1.911328,13.345779,0.218138,0.899735,0.000413,0.048815,0.002925
3,cluster_random,3.050733,0.051273,46.170372,3.937213,8.924488,0.044187,0.898896,0.000658,0.036967,0.002225

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=APS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.213930,0.023629,58.030344,0.262887,8.324444,0.035928,0.899412,0.000576,0.094945,0.001105
1,classwise,4.114650,0.033201,26.852969,1.686095,23.862054,0.859265,0.904764,0.000473,0.026382,0.002672
2,exact_coverage_classwise,3.819427,0.062352,32.342359,1.911328,13.345779,0.218138,0.899735,0.000413,0.048815,0.002925
3,cluster_random,3.050733,0.051273,46.170372,3.937213,8.924488,0.044187,0.898896,0.000658,0.036967,0.002225

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.002332,0.017839,56.943571,0.209347,5.153157,0.010899,0.899232,0.000450,0.130964,0.001679
1,classwise,4.200443,0.037198,25.829769,1.420427,25.628248,0.872394,0.905091,0.000435,0.027014,0.002472
2,exact_coverage_classwise,3.821257,0.031617,29.744542,2.062498,13.068702,0.276602,0.900180,0.000447,0.044708,0.001788
3,cluster_random,3.588359,0.035667,42.859399,4.476638,5.712157,0.135797,0.899487,0.000693,0.056872,0.001948

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.002332,0.017839,56.943571,0.209347,5.153157,0.010899,0.899232,0.000450,0.130964,0.001679
1,classwise,4.200443,0.037198,25.829769,1.420427,25.628248,0.872394,0.905091,0.000435,0.027014,0.002472
2,exact_coverage_classwise,3.821257,0.031617,29.744542,2.062498,13.068702,0.276602,0.900180,0.000447,0.044708,0.001788
3,cluster_random,3.588359,0.035667,42.859399,4.476638,5.712157,0.135797,0.899487,0.000693,0.056872,0.001948

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.002332,0.017839,56.943571,0.209347,5.153157,0.010899,0.899232,0.000450,0.130964,0.001679
1,classwise,4.200443,0.037198,25.829769,1.420427,25.628248,0.872394,0.905091,0.000435,0.027014,0.002472
2,exact_coverage_classwise,3.821257,0.031617,29.744542,2.062498,13.068702,0.276602,0.900180,0.000447,0.044708,0.001788
3,cluster_random,3.588359,0.035667,42.859399,4.476638,5.712157,0.135797,0.899487,0.000693,0.056872,0.001948

.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=100/score=RAPS/
Number of seeds found: 10

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.002332,0.017839,56.943571,0.209347,5.153157,0.010899,0.899232,0.000450,0.130964,0.001679
1,classwise,4.200443,0.037198,25.829769,1.420427,25.628248,0.872394,0.905091,0.000435,0.027014,0.002472
2,exact_coverage_classwise,3.821257,0.031617,29.744542,2.062498,13.068702,0.276602,0.900180,0.000447,0.044708,0.001788
3,cluster_random,3.588359,0.035667,42.859399,4.476638,5.712157,0.135797,0.899487,0.000693,0.056872,0.001948

\begin{tabular}{llllllllll}
\toprule
            &         &              & $n_{\text{avg}}=10$ & $n_{\text{avg}}=20$ & $n_{\text{avg}}=30$ & $n_{\text{avg}}=40$ & $n_{\text{avg}}=50$ & $n_{\text{avg}}=75$ & $n_{\text{avg}}=100$ \\
            &         &              &             MargCov &             MargCov &             MargCov &             MargCov &             MargCov &             MargCov &              MargCov \\
Dataset & Score func. & Method &                     &                     &                     &                     &                     &                     &                      \\
\midrule
ImageNet & $\softmax$ & $\standard$ &          90.0 (0.1) &          90.0 (0.1) &          89.9 (0.0) &          89.9 (0.0) &          89.9 (0.0) &          89.9 (0.0) &           90.0 (0.0) \\
            &         & $\classwise$ &          94.6 (0.1) &          92.3 (0.0) &          91.6 (0.0) &          91.2 (0.0) &          90.9 (0.0) &          90.6 (0.0) &           90.5 (0.0) \\
            &         & ExactCov-$\classwise$ &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.0) &          90.0 (0.0) &          89.9 (0.0) &          89.9 (0.0) &           90.0 (0.0) \\
            &         & $\clustered$ &          90.3 (0.3) &          90.3 (0.2) &          90.2 (0.2) &          90.1 (0.1) &          90.0 (0.1) &          90.1 (0.1) &           90.2 (0.1) \\
            & $\APS$ & $\standard$ &          90.0 (0.1) &          90.0 (0.0) &          89.9 (0.0) &          90.0 (0.0) &          89.9 (0.0) &          90.0 (0.0) &           90.0 (0.0) \\
            &         & $\classwise$ &          94.7 (0.1) &          92.3 (0.0) &          91.6 (0.1) &          91.3 (0.0) &          91.0 (0.0) &          90.7 (0.0) &           90.5 (0.0) \\
            &         & ExactCov-$\classwise$ &          90.1 (0.1) &          90.0 (0.0) &          90.0 (0.1) &          90.0 (0.0) &          89.8 (0.0) &          90.0 (0.0) &           90.0 (0.0) \\
            &         & $\clustered$ &          90.4 (0.3) &          90.0 (0.2) &          90.1 (0.2) &          90.4 (0.1) &          90.0 (0.1) &          90.1 (0.1) &           90.1 (0.1) \\
            & $\RAPS$ & $\standard$ &          90.1 (0.1) &          89.9 (0.1) &          90.0 (0.1) &          90.0 (0.0) &          90.0 (0.0) &          90.0 (0.0) &           90.0 (0.0) \\
            &         & $\classwise$ &          94.6 (0.1) &          92.6 (0.1) &          91.9 (0.1) &          91.4 (0.0) &          91.1 (0.0) &          90.7 (0.0) &           90.5 (0.0) \\
            &         & ExactCov-$\classwise$ &          90.1 (0.1) &          90.0 (0.0) &          89.9 (0.0) &          89.9 (0.0) &          89.8 (0.0) &          90.0 (0.0) &           89.9 (0.0) \\
            &         & $\clustered$ &          90.3 (0.2) &          90.1 (0.2) &          90.0 (0.1) &          90.4 (0.1) &          90.2 (0.1) &          90.0 (0.1) &           90.2 (0.1) \\
\midrule
CIFAR-100 & $\softmax$ & $\standard$ &          90.1 (0.3) &          89.9 (0.2) &          89.7 (0.2) &          89.9 (0.2) &          90.0 (0.1) &          90.0 (0.1) &           90.0 (0.1) \\
            &         & $\classwise$ &          94.5 (0.2) &          92.2 (0.1) &          91.3 (0.1) &          91.0 (0.1) &          90.9 (0.1) &          90.7 (0.1) &           90.6 (0.1) \\
            &         & ExactCov-$\classwise$ &          90.1 (0.2) &          89.9 (0.1) &          89.8 (0.1) &          89.8 (0.1) &          89.8 (0.1) &          90.0 (0.1) &           90.0 (0.1) \\
            &         & $\clustered$ &          89.9 (0.3) &          90.3 (0.3) &          90.1 (0.2) &          90.0 (0.3) &          90.4 (0.3) &          90.2 (0.2) &           90.0 (0.2) \\
            & $\APS$ & $\standard$ &          90.1 (0.2) &          89.8 (0.1) &          89.6 (0.1) &          89.9 (0.2) &          90.0 (0.1) &          90.0 (0.1) &           90.0 (0.1) \\
            &         & $\classwise$ &          94.7 (0.2) &          92.2 (0.1) &          91.4 (0.1) &          91.2 (0.1) &          90.8 (0.1) &          90.6 (0.1) &           90.5 (0.1) \\
            &         & ExactCov-$\classwise$ &          90.0 (0.2) &          89.9 (0.2) &          89.7 (0.1) &          89.9 (0.1) &          89.9 (0.1) &          89.9 (0.1) &           89.9 (0.1) \\
            &         & $\clustered$ &          89.8 (0.3) &          90.4 (0.3) &          90.1 (0.3) &          90.1 (0.3) &          90.3 (0.2) &          90.4 (0.2) &           90.1 (0.1) \\
            & $\RAPS$ & $\standard$ &          90.4 (0.2) &          90.1 (0.2) &          90.0 (0.2) &          90.0 (0.2) &          90.1 (0.1) &          90.1 (0.1) &           90.0 (0.1) \\
            &         & $\classwise$ &          94.6 (0.2) &          92.7 (0.2) &          92.0 (0.2) &          91.5 (0.1) &          91.2 (0.1) &          90.9 (0.1) &           90.7 (0.1) \\
            &         & ExactCov-$\classwise$ &          90.0 (0.3) &          90.0 (0.2) &          90.0 (0.2) &          90.0 (0.1) &          90.1 (0.1) &          90.0 (0.1) &           90.0 (0.1) \\
            &         & $\clustered$ &          90.4 (0.3) &          90.0 (0.4) &          90.4 (0.3) &          90.6 (0.2) &          90.3 (0.3) &          90.4 (0.1) &           90.2 (0.1) \\
\midrule
Places365 & $\softmax$ & $\standard$ &          90.1 (0.1) &          90.0 (0.1) &          90.1 (0.1) &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.0) &           90.0 (0.0) \\
            &         & $\classwise$ &          94.5 (0.1) &          92.3 (0.1) &          91.7 (0.1) &          91.2 (0.1) &          91.0 (0.0) &          90.7 (0.1) &           90.5 (0.0) \\
            &         & ExactCov-$\classwise$ &          89.9 (0.1) &          90.0 (0.1) &          90.1 (0.1) &          90.0 (0.1) &          90.0 (0.0) &          90.0 (0.1) &           90.0 (0.0) \\
            &         & $\clustered$ &          90.1 (0.2) &          89.5 (0.2) &          90.0 (0.2) &          90.4 (0.1) &          90.2 (0.1) &          90.1 (0.1) &           90.2 (0.1) \\
            & $\APS$ & $\standard$ &          90.1 (0.1) &          90.1 (0.1) &          90.1 (0.1) &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.1) &           90.0 (0.0) \\
            &         & $\classwise$ &          94.5 (0.1) &          92.4 (0.1) &          91.6 (0.1) &          91.3 (0.1) &          91.0 (0.1) &          90.7 (0.1) &           90.5 (0.1) \\
            &         & ExactCov-$\classwise$ &          90.0 (0.2) &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.1) &           90.0 (0.1) \\
            &         & $\clustered$ &          89.8 (0.3) &          89.7 (0.2) &          90.2 (0.2) &          90.3 (0.1) &          90.4 (0.2) &          90.0 (0.2) &           90.3 (0.1) \\
            & $\RAPS$ & $\standard$ &          89.9 (0.1) &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.0) &           90.0 (0.0) \\
            &         & $\classwise$ &          94.5 (0.1) &          92.5 (0.1) &          91.8 (0.1) &          91.4 (0.1) &          91.1 (0.0) &          90.8 (0.0) &           90.5 (0.0) \\
            &         & ExactCov-$\classwise$ &          90.0 (0.2) &          90.0 (0.1) &          90.1 (0.1) &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.1) &           90.0 (0.0) \\
            &         & $\clustered$ &          89.8 (0.2) &          89.7 (0.2) &          90.1 (0.2) &          90.4 (0.1) &          90.3 (0.1) &          90.0 (0.2) &           90.4 (0.1) \\
\midrule
iNaturalist & $\softmax$ & $\standard$ &          89.9 (0.1) &          89.9 (0.1) &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.1) &          90.0 (0.1) &           90.0 (0.0) \\
            &         & $\classwise$ &          93.2 (0.1) &          92.0 (0.1) &          91.6 (0.0) &          91.2 (0.0) &          91.0 (0.1) &          90.6 (0.1) &           90.5 (0.1) \\
            &         & ExactCov-$\classwise$ &          89.9 (0.1) &          89.8 (0.1) &          90.0 (0.1) &          90.0 (0.0) &          89.9 (0.0) &          89.9 (0.1) &           90.0 (0.1) \\
            &         & $\clustered$ &          88.6 (0.2) &          89.3 (0.2) &          89.4 (0.1) &          89.5 (0.1) &          89.7 (0.1) &          89.8 (0.1) &           90.0 (0.1) \\
            & $\APS$ & $\standard$ &          89.9 (0.2) &          90.0 (0.1) &          89.9 (0.1) &          89.9 (0.1) &          89.9 (0.1) &          89.9 (0.0) &           89.9 (0.1) \\
            &         & $\classwise$ &          93.4 (0.1) &          92.1 (0.1) &          91.5 (0.1) &          91.2 (0.1) &          90.9 (0.1) &          90.6 (0.0) &           90.5 (0.0) \\
            &         & ExactCov-$\classwise$ &          90.1 (0.1) &          90.0 (0.1) &          89.9 (0.1) &          89.9 (0.1) &          89.9 (0.1) &          89.8 (0.1) &           90.0 (0.0) \\
            &         & $\clustered$ &          89.3 (0.2) &          89.6 (0.2) &          89.4 (0.1) &          89.6 (0.2) &          89.7 (0.1) &          89.8 (0.1) &           89.9 (0.1) \\
            & $\RAPS$ & $\standard$ &          89.8 (0.2) &          89.9 (0.1) &          89.8 (0.1) &          89.9 (0.1) &          89.9 (0.1) &          89.9 (0.0) &           89.9 (0.0) \\
            &         & $\classwise$ &          93.4 (0.1) &          92.1 (0.1) &          91.6 (0.1) &          91.2 (0.1) &          91.0 (0.1) &          90.7 (0.0) &           90.5 (0.0) \\
            &         & ExactCov-$\classwise$ &          90.1 (0.1) &          89.9 (0.1) &          90.0 (0.1) &          90.0 (0.1) &          89.9 (0.1) &          89.8 (0.1) &           90.0 (0.0) \\
            &         & $\clustered$ &          89.0 (0.1) &          89.6 (0.2) &          89.4 (0.1) &          89.6 (0.2) &          89.6 (0.1) &          89.8 (0.1) &           89.9 (0.1) \\
\bottomrule
\end{tabular}

/tmp/ipykernel_2212899/3605695589.py:41: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  df_str = df.to_latex(multicolumn_format='c', # To center multilevel column headers

In [33]:
df

                                              $n_{\text{avg}}=10$  \
                                                          MargCov
Dataset     Score func. Method
ImageNet    $\softmax$  $\standard$                    90.0 (0.1)
                        $\classwise$                   94.6 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.3 (0.3)
            $\APS$      $\standard$                    90.0 (0.1)
                        $\classwise$                   94.7 (0.1)
                        ExactCov-$\classwise$          90.1 (0.1)
                        $\clustered$                   90.4 (0.3)
            $\RAPS$     $\standard$                    90.1 (0.1)
                        $\classwise$                   94.6 (0.1)
                        ExactCov-$\classwise$          90.1 (0.1)
                        $\clustered$                   90.3 (0.2)
CIFAR-100   $\softmax$  $\standard$                    90.1 (0.3)
                        $\classwise$                   94.5 (0.2)
                        ExactCov-$\classwise$          90.1 (0.2)
                        $\clustered$                   89.9 (0.3)
            $\APS$      $\standard$                    90.1 (0.2)
                        $\classwise$                   94.7 (0.2)
                        ExactCov-$\classwise$          90.0 (0.2)
                        $\clustered$                   89.8 (0.3)
            $\RAPS$     $\standard$                    90.4 (0.2)
                        $\classwise$                   94.6 (0.2)
                        ExactCov-$\classwise$          90.0 (0.3)
                        $\clustered$                   90.4 (0.3)
Places365   $\softmax$  $\standard$                    90.1 (0.1)
                        $\classwise$                   94.5 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   90.1 (0.2)
            $\APS$      $\standard$                    90.1 (0.1)
                        $\classwise$                   94.5 (0.1)
                        ExactCov-$\classwise$          90.0 (0.2)
                        $\clustered$                   89.8 (0.3)
            $\RAPS$     $\standard$                    89.9 (0.1)
                        $\classwise$                   94.5 (0.1)
                        ExactCov-$\classwise$          90.0 (0.2)
                        $\clustered$                   89.8 (0.2)
iNaturalist $\softmax$  $\standard$                    89.9 (0.1)
                        $\classwise$                   93.2 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   88.6 (0.2)
            $\APS$      $\standard$                    89.9 (0.2)
                        $\classwise$                   93.4 (0.1)
                        ExactCov-$\classwise$          90.1 (0.1)
                        $\clustered$                   89.3 (0.2)
            $\RAPS$     $\standard$                    89.8 (0.2)
                        $\classwise$                   93.4 (0.1)
                        ExactCov-$\classwise$          90.1 (0.1)
                        $\clustered$                   89.0 (0.1)

                                              $n_{\text{avg}}=20$  \
                                                          MargCov
Dataset     Score func. Method
ImageNet    $\softmax$  $\standard$                    90.0 (0.1)
                        $\classwise$                   92.3 (0.0)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.3 (0.2)
            $\APS$      $\standard$                    90.0 (0.0)
                        $\classwise$                   92.3 (0.0)
                        ExactCov-$\classwise$          90.0 (0.0)
                        $\clustered$                   90.0 (0.2)
            $\RAPS$     $\standard$                    89.9 (0.1)
                        $\classwise$                   92.6 (0.1)
                        ExactCov-$\classwise$          90.0 (0.0)
                        $\clustered$                   90.1 (0.2)
CIFAR-100   $\softmax$  $\standard$                    89.9 (0.2)
                        $\classwise$                   92.2 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   90.3 (0.3)
            $\APS$      $\standard$                    89.8 (0.1)
                        $\classwise$                   92.2 (0.1)
                        ExactCov-$\classwise$          89.9 (0.2)
                        $\clustered$                   90.4 (0.3)
            $\RAPS$     $\standard$                    90.1 (0.2)
                        $\classwise$                   92.7 (0.2)
                        ExactCov-$\classwise$          90.0 (0.2)
                        $\clustered$                   90.0 (0.4)
Places365   $\softmax$  $\standard$                    90.0 (0.1)
                        $\classwise$                   92.3 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   89.5 (0.2)
            $\APS$      $\standard$                    90.1 (0.1)
                        $\classwise$                   92.4 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   89.7 (0.2)
            $\RAPS$     $\standard$                    90.0 (0.1)
                        $\classwise$                   92.5 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   89.7 (0.2)
iNaturalist $\softmax$  $\standard$                    89.9 (0.1)
                        $\classwise$                   92.0 (0.1)
                        ExactCov-$\classwise$          89.8 (0.1)
                        $\clustered$                   89.3 (0.2)
            $\APS$      $\standard$                    90.0 (0.1)
                        $\classwise$                   92.1 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   89.6 (0.2)
            $\RAPS$     $\standard$                    89.9 (0.1)
                        $\classwise$                   92.1 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   89.6 (0.2)

                                              $n_{\text{avg}}=30$  \
                                                          MargCov
Dataset     Score func. Method
ImageNet    $\softmax$  $\standard$                    89.9 (0.0)
                        $\classwise$                   91.6 (0.0)
                        ExactCov-$\classwise$          90.0 (0.0)
                        $\clustered$                   90.2 (0.2)
            $\APS$      $\standard$                    89.9 (0.0)
                        $\classwise$                   91.6 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.1 (0.2)
            $\RAPS$     $\standard$                    90.0 (0.1)
                        $\classwise$                   91.9 (0.1)
                        ExactCov-$\classwise$          89.9 (0.0)
                        $\clustered$                   90.0 (0.1)
CIFAR-100   $\softmax$  $\standard$                    89.7 (0.2)
                        $\classwise$                   91.3 (0.1)
                        ExactCov-$\classwise$          89.8 (0.1)
                        $\clustered$                   90.1 (0.2)
            $\APS$      $\standard$                    89.6 (0.1)
                        $\classwise$                   91.4 (0.1)
                        ExactCov-$\classwise$          89.7 (0.1)
                        $\clustered$                   90.1 (0.3)
            $\RAPS$     $\standard$                    90.0 (0.2)
                        $\classwise$                   92.0 (0.2)
                        ExactCov-$\classwise$          90.0 (0.2)
                        $\clustered$                   90.4 (0.3)
Places365   $\softmax$  $\standard$                    90.1 (0.1)
                        $\classwise$                   91.7 (0.1)
                        ExactCov-$\classwise$          90.1 (0.1)
                        $\clustered$                   90.0 (0.2)
            $\APS$      $\standard$                    90.1 (0.1)
                        $\classwise$                   91.6 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.2 (0.2)
            $\RAPS$     $\standard$                    90.0 (0.1)
                        $\classwise$                   91.8 (0.1)
                        ExactCov-$\classwise$          90.1 (0.1)
                        $\clustered$                   90.1 (0.2)
iNaturalist $\softmax$  $\standard$                    90.0 (0.1)
                        $\classwise$                   91.6 (0.0)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   89.4 (0.1)
            $\APS$      $\standard$                    89.9 (0.1)
                        $\classwise$                   91.5 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   89.4 (0.1)
            $\RAPS$     $\standard$                    89.8 (0.1)
                        $\classwise$                   91.6 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   89.4 (0.1)

                                              $n_{\text{avg}}=40$  \
                                                          MargCov
Dataset     Score func. Method
ImageNet    $\softmax$  $\standard$                    89.9 (0.0)
                        $\classwise$                   91.2 (0.0)
                        ExactCov-$\classwise$          90.0 (0.0)
                        $\clustered$                   90.1 (0.1)
            $\APS$      $\standard$                    90.0 (0.0)
                        $\classwise$                   91.3 (0.0)
                        ExactCov-$\classwise$          90.0 (0.0)
                        $\clustered$                   90.4 (0.1)
            $\RAPS$     $\standard$                    90.0 (0.0)
                        $\classwise$                   91.4 (0.0)
                        ExactCov-$\classwise$          89.9 (0.0)
                        $\clustered$                   90.4 (0.1)
CIFAR-100   $\softmax$  $\standard$                    89.9 (0.2)
                        $\classwise$                   91.0 (0.1)
                        ExactCov-$\classwise$          89.8 (0.1)
                        $\clustered$                   90.0 (0.3)
            $\APS$      $\standard$                    89.9 (0.2)
                        $\classwise$                   91.2 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   90.1 (0.3)
            $\RAPS$     $\standard$                    90.0 (0.2)
                        $\classwise$                   91.5 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.6 (0.2)
Places365   $\softmax$  $\standard$                    90.0 (0.1)
                        $\classwise$                   91.2 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.4 (0.1)
            $\APS$      $\standard$                    90.0 (0.1)
                        $\classwise$                   91.3 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.3 (0.1)
            $\RAPS$     $\standard$                    90.0 (0.1)
                        $\classwise$                   91.4 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.4 (0.1)
iNaturalist $\softmax$  $\standard$                    90.0 (0.1)
                        $\classwise$                   91.2 (0.0)
                        ExactCov-$\classwise$          90.0 (0.0)
                        $\clustered$                   89.5 (0.1)
            $\APS$      $\standard$                    89.9 (0.1)
                        $\classwise$                   91.2 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   89.6 (0.2)
            $\RAPS$     $\standard$                    89.9 (0.1)
                        $\classwise$                   91.2 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   89.6 (0.2)

                                              $n_{\text{avg}}=50$  \
                                                          MargCov
Dataset     Score func. Method
ImageNet    $\softmax$  $\standard$                    89.9 (0.0)
                        $\classwise$                   90.9 (0.0)
                        ExactCov-$\classwise$          89.9 (0.0)
                        $\clustered$                   90.0 (0.1)
            $\APS$      $\standard$                    89.9 (0.0)
                        $\classwise$                   91.0 (0.0)
                        ExactCov-$\classwise$          89.8 (0.0)
                        $\clustered$                   90.0 (0.1)
            $\RAPS$     $\standard$                    90.0 (0.0)
                        $\classwise$                   91.1 (0.0)
                        ExactCov-$\classwise$          89.8 (0.0)
                        $\clustered$                   90.2 (0.1)
CIFAR-100   $\softmax$  $\standard$                    90.0 (0.1)
                        $\classwise$                   90.9 (0.1)
                        ExactCov-$\classwise$          89.8 (0.1)
                        $\clustered$                   90.4 (0.3)
            $\APS$      $\standard$                    90.0 (0.1)
                        $\classwise$                   90.8 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   90.3 (0.2)
            $\RAPS$     $\standard$                    90.1 (0.1)
                        $\classwise$                   91.2 (0.1)
                        ExactCov-$\classwise$          90.1 (0.1)
                        $\clustered$                   90.3 (0.3)
Places365   $\softmax$  $\standard$                    90.0 (0.1)
                        $\classwise$                   91.0 (0.0)
                        ExactCov-$\classwise$          90.0 (0.0)
                        $\clustered$                   90.2 (0.1)
            $\APS$      $\standard$                    90.0 (0.1)
                        $\classwise$                   91.0 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.4 (0.2)
            $\RAPS$     $\standard$                    90.0 (0.1)
                        $\classwise$                   91.1 (0.0)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.3 (0.1)
iNaturalist $\softmax$  $\standard$                    90.0 (0.1)
                        $\classwise$                   91.0 (0.1)
                        ExactCov-$\classwise$          89.9 (0.0)
                        $\clustered$                   89.7 (0.1)
            $\APS$      $\standard$                    89.9 (0.1)
                        $\classwise$                   90.9 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   89.7 (0.1)
            $\RAPS$     $\standard$                    89.9 (0.1)
                        $\classwise$                   91.0 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   89.6 (0.1)

                                              $n_{\text{avg}}=75$  \
                                                          MargCov
Dataset     Score func. Method
ImageNet    $\softmax$  $\standard$                    89.9 (0.0)
                        $\classwise$                   90.6 (0.0)
                        ExactCov-$\classwise$          89.9 (0.0)
                        $\clustered$                   90.1 (0.1)
            $\APS$      $\standard$                    90.0 (0.0)
                        $\classwise$                   90.7 (0.0)
                        ExactCov-$\classwise$          90.0 (0.0)
                        $\clustered$                   90.1 (0.1)
            $\RAPS$     $\standard$                    90.0 (0.0)
                        $\classwise$                   90.7 (0.0)
                        ExactCov-$\classwise$          90.0 (0.0)
                        $\clustered$                   90.0 (0.1)
CIFAR-100   $\softmax$  $\standard$                    90.0 (0.1)
                        $\classwise$                   90.7 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.2 (0.2)
            $\APS$      $\standard$                    90.0 (0.1)
                        $\classwise$                   90.6 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   90.4 (0.2)
            $\RAPS$     $\standard$                    90.1 (0.1)
                        $\classwise$                   90.9 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.4 (0.1)
Places365   $\softmax$  $\standard$                    90.0 (0.0)
                        $\classwise$                   90.7 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.1 (0.1)
            $\APS$      $\standard$                    90.0 (0.1)
                        $\classwise$                   90.7 (0.1)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.0 (0.2)
            $\RAPS$     $\standard$                    90.0 (0.0)
                        $\classwise$                   90.8 (0.0)
                        ExactCov-$\classwise$          90.0 (0.1)
                        $\clustered$                   90.0 (0.2)
iNaturalist $\softmax$  $\standard$                    90.0 (0.1)
                        $\classwise$                   90.6 (0.1)
                        ExactCov-$\classwise$          89.9 (0.1)
                        $\clustered$                   89.8 (0.1)
            $\APS$      $\standard$                    89.9 (0.0)
                        $\classwise$                   90.6 (0.0)
                        ExactCov-$\classwise$          89.8 (0.1)
                        $\clustered$                   89.8 (0.1)
            $\RAPS$     $\standard$                    89.9 (0.0)
                        $\classwise$                   90.7 (0.0)
                        ExactCov-$\classwise$          89.8 (0.1)