In [1]:
import sys; sys.path.append("../") # For relative imports

from utils.experiment_utils import *

%load_ext autoreload
%autoreload 2

Read in all saved results and make Latex table

**Note**: Before running this notebook, run `sh run_experiment.sh`.

Formatting notes: To get multiple row levels, set a multi-index. To get multiple column levels, concatenate dataframes along axis=1.

In [2]:
datasets = {'ImageNet': '../.cache/paper/varying_n/imagenet',
            'CIFAR-100': '../.cache/paper/varying_n/cifar-100',
            'Places365': '../.cache/paper/varying_n/places365',
            'iNaturalist': '../.cache/paper/varying_n/inaturalist'}

score_functions = {'softmax': '$\softmax$',
                  'APS': '$\APS$',
                  'RAPS': '$\RAPS$'}

methods = {'standard': '$\standard$', 
            'classwise': '$\classwise$',
            'cluster_random': '$\clustered$'} 

calibration_sampling = 'random' # 'random' or 'balanced'

## Main table
This is Table 1 of the paper.

In [3]:
# GENERATE TABLE - three n's and excluding marginal coverage
n_totalcals = {10: '$n_{\text{avg}}=10$', 20: '$n_{\text{avg}}=20$', 
               50: '$n_{\text{avg}}=50$', 75: '$n_{\text{avg}}=75$'}

horizontal_dict = {}
for n_totalcal, n_name in n_totalcals.items():
    vertical_list = []
    for dataset, save_folder in datasets.items():
        for score, score_name in score_functions.items():
            for method, method_name in methods.items(): 

                folder = f'{save_folder}/{calibration_sampling}_calset/n_totalcal={n_totalcal}/score={score}/'
                print(folder)
                df = average_results_across_seeds(folder, print_results=False, methods=methods.keys()) # df = results DataFrame
                s = pd.Series({'Dataset': dataset, 'Score func.': score_name, 'Method': method_name, 
                               'CovGap': f"{df[df['method'] == method]['class_cov_gap_mean'].values[0]:.1f}" 
                                       f" ({df[df['method'] == method]['class_cov_gap_se'].values[0]:.1f})",
                               'AvgSize': f"{df[df['method'] == method]['avg_set_size_mean'].values[0]:.1f}" 
                                               f" ({df[df['method'] == method]['avg_set_size_se'].values[0]:.1f})"})
#                                'MargCov': f"{df[df['method'] == method]['marginal_cov_mean'].values[0]*100:.1f}" 
#                                                    f" ({df[df['method'] == method]['marginal_cov_se'].values[0]*100:.1f})"})
                vertical_list.append(pd.DataFrame(s).transpose())                                        

    df = pd.concat(vertical_list, ignore_index=True)                                                     
    df = df.set_index(['Dataset', 'Score func.', 'Method'])
    horizontal_dict[n_name] = df

df = pd.concat(horizontal_dict, axis=1)
df_str = df.to_latex(multicolumn_format='c', # To center multilevel column headers
    escape=False) # So that backslashes are printed as `\' rather than '\textbackslash'
                 
# Post-process
df_str = df_str.replace('lllllllllll', 'lllcrcrcrcr')
df_str = df_str.replace('\\multicolumn{2}{c}{$n_{\\text{avg}}=75$} \\\\',
               '\\multicolumn{2}{c}{$n_{\\text{avg}}=75$} \\\\ \cmidrule(lr){4-5}\cmidrule(lr){6-7} \cmidrule(lr){8-9} \cmidrule(lr){10-11}\\')
df_str = df_str.replace('CIFAR-100', '\midrule\nCIFAR-100')
df_str = df_str.replace('Places365', '\midrule\nPlaces365')
df_str = df_str.replace('iNaturalist', '\midrule\niNaturalist')
# Add horizontal lines between methods
df_str = df_str.replace('& $\APS$', '\cline{3-11} & $\APS$')
df_str = df_str.replace('& $\RAPS$', '\cline{3-11} & $\RAPS$')
print(df_str)

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.223595,0.027075,38.294309,0.320930,1.940126,0.017181,0.900375,0.000852,0.0786,0.003089
1,classwise,7.667505,0.045954,38.259073,1.171264,354.399585,2.023335,0.946046,0.000516,0.0549,0.001717
2,cluster_random,4.826233,0.069894,35.020759,1.038594,2.364602,0.091241,0.902750,0.002621,0.0683,0.006326

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.223595,0.027075,38.294309,0.320930,1.940126,0.017181,0.900375,0.000852,0.0786,0.003089
1,classwise,7.667505,0.045954,38.259073,1.171264,354.399585,2.023335,0.946046,0.000516,0.0549,0.001717
2,cluster_random,4.826233,0.069894,35.020759,1.038594,2.364602,0.091241,0.902750,0.002621,0.0683,0.006326

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.223595,0.027075,38.294309,0.320930,1.940126,0.017181,0.900375,0.000852,0.0786,0.003089
1,classwise,7.667505,0.045954,38.259073,1.171264,354.399585,2.023335,0.946046,0.000516,0.0549,0.001717
2,cluster_random,4.826233,0.069894,35.020759,1.038594,2.364602,0.091241,0.902750,0.002621,0.0683,0.006326

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.560513,0.015340,21.132209,0.125715,25.925433,0.334314,0.900207,0.000965,0.0213,0.000401
1,classwise,7.634544,0.022949,37.179353,1.942818,394.178026,1.908782,0.946538,0.000866,0.0548,0.002440
2,cluster_random,2.796587,0.065851,21.171140,0.675242,27.650016,0.691750,0.902455,0.001592,0.0205,0.001219

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.560513,0.015340,21.132209,0.125715,25.925433,0.334314,0.900207,0.000965,0.0213,0.000401
1,classwise,7.634544,0.022949,37.179353,1.942818,394.178026,1.908782,0.946538,0.000866,0.0548,0.002440
2,cluster_random,2.796587,0.065851,21.171140,0.675242,27.650016,0.691750,0.902455,0.001592,0.0205,0.001219

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.560513,0.015340,21.132209,0.125715,25.925433,0.334314,0.900207,0.000965,0.0213,0.000401
1,classwise,7.634544,0.022949,37.179353,1.942818,394.178026,1.908782,0.946538,0.000866,0.0548,0.002440
2,cluster_random,2.796587,0.065851,21.171140,0.675242,27.650016,0.691750,0.902455,0.001592,0.0205,0.001219

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.987546,0.008992,24.879529,0.098567,5.145962,0.022957,0.900437,0.000868,0.0268,0.000465
1,classwise,7.640983,0.031834,37.531237,1.954949,361.866033,1.911416,0.946475,0.000970,0.0543,0.002642
2,cluster_random,3.239841,0.049563,22.165461,0.637380,8.036755,0.858319,0.906371,0.002433,0.0226,0.002677

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.987546,0.008992,24.879529,0.098567,5.145962,0.022957,0.900437,0.000868,0.0268,0.000465
1,classwise,7.640983,0.031834,37.531237,1.954949,361.866033,1.911416,0.946475,0.000970,0.0543,0.002642
2,cluster_random,3.239841,0.049563,22.165461,0.637380,8.036755,0.858319,0.906371,0.002433,0.0226,0.002677

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.987546,0.008992,24.879529,0.098567,5.145962,0.022957,0.900437,0.000868,0.0268,0.000465
1,classwise,7.640983,0.031834,37.531237,1.954949,361.866033,1.911416,0.946475,0.000970,0.0543,0.002642
2,cluster_random,3.239841,0.049563,22.165461,0.637380,8.036755,0.858319,0.906371,0.002433,0.0226,0.002677

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.995571,0.061380,12.098017,0.661933,8.059493,0.242276,0.900624,0.002577,0.041,0.009945
1,classwise,7.558791,0.131608,20.308118,1.912127,47.158297,0.566220,0.945038,0.001993,0.054,0.008025
2,cluster_random,4.143155,0.096261,13.011911,1.028603,9.389255,0.417457,0.901483,0.003210,0.047,0.010493

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.995571,0.061380,12.098017,0.661933,8.059493,0.242276,0.900624,0.002577,0.041,0.009945
1,classwise,7.558791,0.131608,20.308118,1.912127,47.158297,0.566220,0.945038,0.001993,0.054,0.008025
2,cluster_random,4.143155,0.096261,13.011911,1.028603,9.389255,0.417457,0.901483,0.003210,0.047,0.010493

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.995571,0.061380,12.098017,0.661933,8.059493,0.242276,0.900624,0.002577,0.041,0.009945
1,classwise,7.558791,0.131608,20.308118,1.912127,47.158297,0.566220,0.945038,0.001993,0.054,0.008025
2,cluster_random,4.143155,0.096261,13.011911,1.028603,9.389255,0.417457,0.901483,0.003210,0.047,0.010493

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.730077,0.058707,13.343152,0.487188,11.261917,0.291297,0.900931,0.002248,0.030,0.005292
1,classwise,7.533149,0.110252,22.498449,1.694710,49.338679,0.501465,0.946093,0.001731,0.055,0.006364
2,cluster_random,3.846879,0.078579,13.789855,0.730335,12.123372,0.368247,0.902466,0.002586,0.034,0.006033

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.730077,0.058707,13.343152,0.487188,11.261917,0.291297,0.900931,0.002248,0.030,0.005292
1,classwise,7.533149,0.110252,22.498449,1.694710,49.338679,0.501465,0.946093,0.001731,0.055,0.006364
2,cluster_random,3.846879,0.078579,13.789855,0.730335,12.123372,0.368247,0.902466,0.002586,0.034,0.006033

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.730077,0.058707,13.343152,0.487188,11.261917,0.291297,0.900931,0.002248,0.030,0.005292
1,classwise,7.533149,0.110252,22.498449,1.694710,49.338679,0.501465,0.946093,0.001731,0.055,0.006364
2,cluster_random,3.846879,0.078579,13.789855,0.730335,12.123372,0.368247,0.902466,0.002586,0.034,0.006033

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.742625,0.072939,13.966079,0.584843,8.593745,0.259895,0.903483,0.002327,0.060,0.010770
1,classwise,7.576817,0.082653,22.650330,1.722107,47.505969,0.691232,0.945359,0.001779,0.053,0.006488
2,cluster_random,4.823612,0.107116,14.556249,0.851182,9.367534,0.409225,0.903683,0.002862,0.069,0.013073

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.742625,0.072939,13.966079,0.584843,8.593745,0.259895,0.903483,0.002327,0.060,0.010770
1,classwise,7.576817,0.082653,22.650330,1.722107,47.505969,0.691232,0.945359,0.001779,0.053,0.006488
2,cluster_random,4.823612,0.107116,14.556249,0.851182,9.367534,0.409225,0.903683,0.002862,0.069,0.013073

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.742625,0.072939,13.966079,0.584843,8.593745,0.259895,0.903483,0.002327,0.060,0.010770
1,classwise,7.576817,0.082653,22.650330,1.722107,47.505969,0.691232,0.945359,0.001779,0.053,0.006488
2,cluster_random,4.823612,0.107116,14.556249,0.851182,9.367534,0.409225,0.903683,0.002862,0.069,0.013073

../.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.540453,0.040803,21.593402,0.293917,6.936377,0.077167,0.900629,0.001260,0.066575,0.004083
1,classwise,7.618150,0.054653,34.904122,2.151995,136.461242,1.650991,0.944855,0.001325,0.054521,0.003561
2,cluster_random,4.510357,0.093143,21.462474,1.066270,7.361601,0.262097,0.904015,0.003769,0.057534,0.011156

../.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.540453,0.040803,21.593402,0.293917,6.936377,0.077167,0.900629,0.001260,0.066575,0.004083
1,classwise,7.618150,0.054653,34.904122,2.151995,136.461242,1.650991,0.944855,0.001325,0.054521,0.003561
2,cluster_random,4.510357,0.093143,21.462474,1.066270,7.361601,0.262097,0.904015,0.003769,0.057534,0.011156

../.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.540453,0.040803,21.593402,0.293917,6.936377,0.077167,0.900629,0.001260,0.066575,0.004083
1,classwise,7.618150,0.054653,34.904122,2.151995,136.461242,1.650991,0.944855,0.001325,0.054521,0.003561
2,cluster_random,4.510357,0.093143,21.462474,1.066270,7.361601,0.262097,0.904015,0.003769,0.057534,0.011156

../.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.264521,0.020940,18.073719,0.262568,10.864227,0.142262,0.900526,0.001545,0.028767,0.003081
1,classwise,7.652626,0.048571,32.090591,0.880225,140.489404,1.650049,0.945292,0.001118,0.056712,0.002849
2,cluster_random,3.424908,0.075915,17.376177,0.558536,11.435561,0.429229,0.903401,0.004223,0.025753,0.006998

../.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.264521,0.020940,18.073719,0.262568,10.864227,0.142262,0.900526,0.001545,0.028767,0.003081
1,classwise,7.652626,0.048571,32.090591,0.880225,140.489404,1.650049,0.945292,0.001118,0.056712,0.002849
2,cluster_random,3.424908,0.075915,17.376177,0.558536,11.435561,0.429229,0.903401,0.004223,0.025753,0.006998

../.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.264521,0.020940,18.073719,0.262568,10.864227,0.142262,0.900526,0.001545,0.028767,0.003081
1,classwise,7.652626,0.048571,32.090591,0.880225,140.489404,1.650049,0.945292,0.001118,0.056712,0.002849
2,cluster_random,3.424908,0.075915,17.376177,0.558536,11.435561,0.429229,0.903401,0.004223,0.025753,0.006998

../.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.857596,0.003317,19.995418,0.290523,7.952185,0.052576,0.900211,0.001096,0.041096,0.002511
1,classwise,7.614368,0.028373,31.889525,0.815452,138.861464,1.671919,0.944530,0.001233,0.056438,0.002852
2,cluster_random,3.968090,0.052900,19.268978,1.011492,8.297851,0.220790,0.902923,0.003893,0.038630,0.007508

../.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.857596,0.003317,19.995418,0.290523,7.952185,0.052576,0.900211,0.001096,0.041096,0.002511
1,classwise,7.614368,0.028373,31.889525,0.815452,138.861464,1.671919,0.944530,0.001233,0.056438,0.002852
2,cluster_random,3.968090,0.052900,19.268978,1.011492,8.297851,0.220790,0.902923,0.003893,0.038630,0.007508

../.cache/paper/varying_n/places365/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.857596,0.003317,19.995418,0.290523,7.952185,0.052576,0.900211,0.001096,0.041096,0.002511
1,classwise,7.614368,0.028373,31.889525,0.815452,138.861464,1.671919,0.944530,0.001233,0.056438,0.002852
2,cluster_random,3.968090,0.052900,19.268978,1.011492,8.297851,0.220790,0.902923,0.003893,0.038630,0.007508

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.016797,0.087454,46.844151,0.670852,3.146115,0.038824,0.899121,0.001213,0.200948,0.005059
1,classwise,8.734859,0.023685,23.591669,2.328507,469.412571,1.801008,0.930820,0.000762,0.014218,0.001973
2,cluster_random,6.872682,0.121990,46.983198,0.874448,3.085749,0.051209,0.885254,0.001274,0.196524,0.005154

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.016797,0.087454,46.844151,0.670852,3.146115,0.038824,0.899121,0.001213,0.200948,0.005059
1,classwise,8.734859,0.023685,23.591669,2.328507,469.412571,1.801008,0.930820,0.000762,0.014218,0.001973
2,cluster_random,6.872682,0.121990,46.983198,0.874448,3.085749,0.051209,0.885254,0.001274,0.196524,0.005154

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.016797,0.087454,46.844151,0.670852,3.146115,0.038824,0.899121,0.001213,0.200948,0.005059
1,classwise,8.734859,0.023685,23.591669,2.328507,469.412571,1.801008,0.930820,0.000762,0.014218,0.001973
2,cluster_random,6.872682,0.121990,46.983198,0.874448,3.085749,0.051209,0.885254,0.001274,0.196524,0.005154

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.247655,0.058489,59.391987,0.351141,8.286632,0.074132,0.898652,0.001159,0.100000,0.002791
1,classwise,8.725389,0.018687,28.232815,1.963512,472.829190,1.761470,0.931829,0.000781,0.013586,0.000899
2,cluster_random,4.363945,0.105258,59.826338,0.514817,8.053583,0.114767,0.893180,0.001890,0.101738,0.004514

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.247655,0.058489,59.391987,0.351141,8.286632,0.074132,0.898652,0.001159,0.100000,0.002791
1,classwise,8.725389,0.018687,28.232815,1.963512,472.829190,1.761470,0.931829,0.000781,0.013586,0.000899
2,cluster_random,4.363945,0.105258,59.826338,0.514817,8.053583,0.114767,0.893180,0.001890,0.101738,0.004514

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.247655,0.058489,59.391987,0.351141,8.286632,0.074132,0.898652,0.001159,0.100000,0.002791
1,classwise,8.725389,0.018687,28.232815,1.963512,472.829190,1.761470,0.931829,0.000781,0.013586,0.000899
2,cluster_random,4.363945,0.105258,59.826338,0.514817,8.053583,0.114767,0.893180,0.001890,0.101738,0.004514

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.992710,0.036970,56.656197,0.256540,5.131098,0.019905,0.898315,0.000814,0.133333,0.002460
1,classwise,8.737596,0.016213,27.894913,2.150123,473.635992,1.895351,0.932043,0.000757,0.013902,0.001318
2,cluster_random,5.106918,0.088846,57.456044,0.683963,5.080658,0.084447,0.889677,0.001654,0.138863,0.005845

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.992710,0.036970,56.656197,0.256540,5.131098,0.019905,0.898315,0.000814,0.133333,0.002460
1,classwise,8.737596,0.016213,27.894913,2.150123,473.635992,1.895351,0.932043,0.000757,0.013902,0.001318
2,cluster_random,5.106918,0.088846,57.456044,0.683963,5.080658,0.084447,0.889677,0.001654,0.138863,0.005845

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=10/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.992710,0.036970,56.656197,0.256540,5.131098,0.019905,0.898315,0.000814,0.133333,0.002460
1,classwise,8.737596,0.016213,27.894913,2.150123,473.635992,1.895351,0.932043,0.000757,0.013902,0.001318
2,cluster_random,5.106918,0.088846,57.456044,0.683963,5.080658,0.084447,0.889677,0.001654,0.138863,0.005845

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242221,0.019749,38.588681,0.253128,1.925365,0.012754,0.899719,0.000633,0.0809,0.002418
1,classwise,5.406511,0.037542,28.220449,1.499973,22.890092,0.865785,0.922111,0.000464,0.0494,0.002196
2,cluster_random,3.764599,0.030456,23.869773,1.279645,2.552876,0.041015,0.903419,0.001688,0.0354,0.003347

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242221,0.019749,38.588681,0.253128,1.925365,0.012754,0.899719,0.000633,0.0809,0.002418
1,classwise,5.406511,0.037542,28.220449,1.499973,22.890092,0.865785,0.922111,0.000464,0.0494,0.002196
2,cluster_random,3.764599,0.030456,23.869773,1.279645,2.552876,0.041015,0.903419,0.001688,0.0354,0.003347

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.242221,0.019749,38.588681,0.253128,1.925365,0.012754,0.899719,0.000633,0.0809,0.002418
1,classwise,5.406511,0.037542,28.220449,1.499973,22.890092,0.865785,0.922111,0.000464,0.0494,0.002196
2,cluster_random,3.764599,0.030456,23.869773,1.279645,2.552876,0.041015,0.903419,0.001688,0.0354,0.003347

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.541426,0.005319,21.338003,0.056475,25.675974,0.142213,0.899534,0.000427,0.0213,0.000202
1,classwise,5.410548,0.033165,30.012084,1.416565,76.485259,0.757705,0.923085,0.000544,0.0445,0.002312
2,cluster_random,2.576790,0.077268,18.649700,0.710139,26.253065,0.564560,0.899045,0.001874,0.0180,0.002126

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.541426,0.005319,21.338003,0.056475,25.675974,0.142213,0.899534,0.000427,0.0213,0.000202
1,classwise,5.410548,0.033165,30.012084,1.416565,76.485259,0.757705,0.923085,0.000544,0.0445,0.002312
2,cluster_random,2.576790,0.077268,18.649700,0.710139,26.253065,0.564560,0.899045,0.001874,0.0180,0.002126

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.541426,0.005319,21.338003,0.056475,25.675974,0.142213,0.899534,0.000427,0.0213,0.000202
1,classwise,5.410548,0.033165,30.012084,1.416565,76.485259,0.757705,0.923085,0.000544,0.0445,0.002312
2,cluster_random,2.576790,0.077268,18.649700,0.710139,26.253065,0.564560,0.899045,0.001874,0.0180,0.002126

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.977094,0.004125,24.904114,0.064136,5.125813,0.011143,0.899711,0.000440,0.0272,0.000310
1,classwise,5.405922,0.039988,30.008434,1.623460,32.993384,0.973853,0.922893,0.000565,0.0472,0.002284
2,cluster_random,2.927986,0.034173,20.529367,0.704678,6.149688,0.380122,0.900548,0.002106,0.0203,0.002832

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.977094,0.004125,24.904114,0.064136,5.125813,0.011143,0.899711,0.000440,0.0272,0.000310
1,classwise,5.405922,0.039988,30.008434,1.623460,32.993384,0.973853,0.922893,0.000565,0.0472,0.002284
2,cluster_random,2.927986,0.034173,20.529367,0.704678,6.149688,0.380122,0.900548,0.002106,0.0203,0.002832

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.977094,0.004125,24.904114,0.064136,5.125813,0.011143,0.899711,0.000440,0.0272,0.000310
1,classwise,5.405922,0.039988,30.008434,1.623460,32.993384,0.973853,0.922893,0.000565,0.0472,0.002284
2,cluster_random,2.927986,0.034173,20.529367,0.704678,6.149688,0.380122,0.900548,0.002106,0.0203,0.002832

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.037174,0.044152,13.052376,0.565527,7.853014,0.171320,0.898639,0.001843,0.046,0.008149
1,classwise,5.602547,0.081912,19.131714,1.223988,19.226636,0.491577,0.921521,0.001325,0.052,0.006603
2,cluster_random,3.728935,0.110062,13.412123,0.687937,8.289479,0.271982,0.897225,0.002557,0.037,0.008252

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.037174,0.044152,13.052376,0.565527,7.853014,0.171320,0.898639,0.001843,0.046,0.008149
1,classwise,5.602547,0.081912,19.131714,1.223988,19.226636,0.491577,0.921521,0.001325,0.052,0.006603
2,cluster_random,3.728935,0.110062,13.412123,0.687937,8.289479,0.271982,0.897225,0.002557,0.037,0.008252

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.037174,0.044152,13.052376,0.565527,7.853014,0.171320,0.898639,0.001843,0.046,0.008149
1,classwise,5.602547,0.081912,19.131714,1.223988,19.226636,0.491577,0.921521,0.001325,0.052,0.006603
2,cluster_random,3.728935,0.110062,13.412123,0.687937,8.289479,0.271982,0.897225,0.002557,0.037,0.008252

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.808568,0.045985,14.247403,0.340197,10.800775,0.135939,0.897575,0.001132,0.035,0.003808
1,classwise,5.592190,0.122057,20.086515,1.427237,22.516800,0.478654,0.922061,0.001566,0.058,0.007457
2,cluster_random,3.790935,0.121430,14.817812,0.673683,10.961079,0.356025,0.896500,0.003240,0.040,0.006782

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.808568,0.045985,14.247403,0.340197,10.800775,0.135939,0.897575,0.001132,0.035,0.003808
1,classwise,5.592190,0.122057,20.086515,1.427237,22.516800,0.478654,0.922061,0.001566,0.058,0.007457
2,cluster_random,3.790935,0.121430,14.817812,0.673683,10.961079,0.356025,0.896500,0.003240,0.040,0.006782

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.808568,0.045985,14.247403,0.340197,10.800775,0.135939,0.897575,0.001132,0.035,0.003808
1,classwise,5.592190,0.122057,20.086515,1.427237,22.516800,0.478654,0.922061,0.001566,0.058,0.007457
2,cluster_random,3.790935,0.121430,14.817812,0.673683,10.961079,0.356025,0.896500,0.003240,0.040,0.006782

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.811164,0.068780,14.839772,0.583853,8.276275,0.243907,0.901011,0.002215,0.077,0.010588
1,classwise,5.553262,0.121118,20.478259,1.420542,20.217111,0.647886,0.923293,0.001634,0.050,0.006000
2,cluster_random,4.531444,0.091597,17.750647,1.004487,8.514843,0.291337,0.898582,0.002061,0.070,0.009695

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.811164,0.068780,14.839772,0.583853,8.276275,0.243907,0.901011,0.002215,0.077,0.010588
1,classwise,5.553262,0.121118,20.478259,1.420542,20.217111,0.647886,0.923293,0.001634,0.050,0.006000
2,cluster_random,4.531444,0.091597,17.750647,1.004487,8.514843,0.291337,0.898582,0.002061,0.070,0.009695

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.811164,0.068780,14.839772,0.583853,8.276275,0.243907,0.901011,0.002215,0.077,0.010588
1,classwise,5.553262,0.121118,20.478259,1.420542,20.217111,0.647886,0.923293,0.001634,0.050,0.006000
2,cluster_random,4.531444,0.091597,17.750647,1.004487,8.514843,0.291337,0.898582,0.002061,0.070,0.009695

../.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.542529,0.025426,21.654752,0.262784,6.922552,0.048877,0.900471,0.000799,0.066849,0.002634
1,classwise,5.441257,0.033420,26.383191,1.376817,17.907696,0.235401,0.922499,0.000836,0.046301,0.002583
2,cluster_random,3.680052,0.053440,19.424923,1.939331,7.668336,0.181882,0.904220,0.002532,0.029315,0.003933

../.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.542529,0.025426,21.654752,0.262784,6.922552,0.048877,0.900471,0.000799,0.066849,0.002634
1,classwise,5.441257,0.033420,26.383191,1.376817,17.907696,0.235401,0.922499,0.000836,0.046301,0.002583
2,cluster_random,3.680052,0.053440,19.424923,1.939331,7.668336,0.181882,0.904220,0.002532,0.029315,0.003933

../.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.542529,0.025426,21.654752,0.262784,6.922552,0.048877,0.900471,0.000799,0.066849,0.002634
1,classwise,5.441257,0.033420,26.383191,1.376817,17.907696,0.235401,0.922499,0.000836,0.046301,0.002583
2,cluster_random,3.680052,0.053440,19.424923,1.939331,7.668336,0.181882,0.904220,0.002532,0.029315,0.003933

../.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.248577,0.011362,18.087224,0.105362,10.888257,0.092393,0.900866,0.000995,0.028493,0.002690
1,classwise,5.418272,0.063652,26.408758,1.418532,23.390888,0.241354,0.923023,0.000875,0.045205,0.003841
2,cluster_random,2.994063,0.052999,15.145853,0.721458,11.343861,0.264907,0.902977,0.002710,0.011781,0.002542

../.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.248577,0.011362,18.087224,0.105362,10.888257,0.092393,0.900866,0.000995,0.028493,0.002690
1,classwise,5.418272,0.063652,26.408758,1.418532,23.390888,0.241354,0.923023,0.000875,0.045205,0.003841
2,cluster_random,2.994063,0.052999,15.145853,0.721458,11.343861,0.264907,0.902977,0.002710,0.011781,0.002542

../.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.248577,0.011362,18.087224,0.105362,10.888257,0.092393,0.900866,0.000995,0.028493,0.002690
1,classwise,5.418272,0.063652,26.408758,1.418532,23.390888,0.241354,0.923023,0.000875,0.045205,0.003841
2,cluster_random,2.994063,0.052999,15.145853,0.721458,11.343861,0.264907,0.902977,0.002710,0.011781,0.002542

../.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.857928,0.003740,20.128991,0.163037,7.983602,0.047902,0.900875,0.001010,0.040000,0.001784
1,classwise,5.390774,0.039261,26.677741,1.335958,20.931460,0.329548,0.923197,0.000740,0.043288,0.002707
2,cluster_random,3.430852,0.041678,14.580761,0.986065,8.463754,0.150950,0.905064,0.002533,0.017534,0.003659

../.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.857928,0.003740,20.128991,0.163037,7.983602,0.047902,0.900875,0.001010,0.040000,0.001784
1,classwise,5.390774,0.039261,26.677741,1.335958,20.931460,0.329548,0.923197,0.000740,0.043288,0.002707
2,cluster_random,3.430852,0.041678,14.580761,0.986065,8.463754,0.150950,0.905064,0.002533,0.017534,0.003659

../.cache/paper/varying_n/places365/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.857928,0.003740,20.128991,0.163037,7.983602,0.047902,0.900875,0.001010,0.040000,0.001784
1,classwise,5.390774,0.039261,26.677741,1.335958,20.931460,0.329548,0.923197,0.000740,0.043288,0.002707
2,cluster_random,3.430852,0.041678,14.580761,0.986065,8.463754,0.150950,0.905064,0.002533,0.017534,0.003659

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.013434,0.054908,46.855327,0.592711,3.144623,0.024168,0.899152,0.000752,0.201896,0.003394
1,classwise,7.822710,0.021906,31.758727,2.106494,363.964253,1.449797,0.919448,0.000551,0.021485,0.002356
2,cluster_random,6.464916,0.094191,46.783222,0.944342,3.440893,0.049319,0.892334,0.001342,0.179779,0.004226

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.013434,0.054908,46.855327,0.592711,3.144623,0.024168,0.899152,0.000752,0.201896,0.003394
1,classwise,7.822710,0.021906,31.758727,2.106494,363.964253,1.449797,0.919448,0.000551,0.021485,0.002356
2,cluster_random,6.464916,0.094191,46.783222,0.944342,3.440893,0.049319,0.892334,0.001342,0.179779,0.004226

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,7.013434,0.054908,46.855327,0.592711,3.144623,0.024168,0.899152,0.000752,0.201896,0.003394
1,classwise,7.822710,0.021906,31.758727,2.106494,363.964253,1.449797,0.919448,0.000551,0.021485,0.002356
2,cluster_random,6.464916,0.094191,46.783222,0.944342,3.440893,0.049319,0.892334,0.001342,0.179779,0.004226

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.227184,0.035269,59.208370,0.264573,8.306900,0.042267,0.899012,0.000665,0.099368,0.001587
1,classwise,7.835852,0.032893,28.016963,2.398609,368.201092,1.393413,0.920146,0.000578,0.024013,0.001427
2,cluster_random,4.341079,0.100054,59.870802,0.475236,8.085900,0.103166,0.893047,0.001714,0.101106,0.004233

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.227184,0.035269,59.208370,0.264573,8.306900,0.042267,0.899012,0.000665,0.099368,0.001587
1,classwise,7.835852,0.032893,28.016963,2.398609,368.201092,1.393413,0.920146,0.000578,0.024013,0.001427
2,cluster_random,4.341079,0.100054,59.870802,0.475236,8.085900,0.103166,0.893047,0.001714,0.101106,0.004233

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.227184,0.035269,59.208370,0.264573,8.306900,0.042267,0.899012,0.000665,0.099368,0.001587
1,classwise,7.835852,0.032893,28.016963,2.398609,368.201092,1.393413,0.920146,0.000578,0.024013,0.001427
2,cluster_random,4.341079,0.100054,59.870802,0.475236,8.085900,0.103166,0.893047,0.001714,0.101106,0.004233

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.983544,0.028764,56.532848,0.205868,5.137464,0.015951,0.898557,0.000650,0.131438,0.002445
1,classwise,7.861056,0.028661,28.227198,2.517357,369.017846,1.453383,0.919932,0.000564,0.024803,0.001532
2,cluster_random,4.971846,0.069746,56.939389,0.576476,5.280942,0.180268,0.893438,0.001804,0.130332,0.004623

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.983544,0.028764,56.532848,0.205868,5.137464,0.015951,0.898557,0.000650,0.131438,0.002445
1,classwise,7.861056,0.028661,28.227198,2.517357,369.017846,1.453383,0.919932,0.000564,0.024803,0.001532
2,cluster_random,4.971846,0.069746,56.939389,0.576476,5.280942,0.180268,0.893438,0.001804,0.130332,0.004623

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=20/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.983544,0.028764,56.532848,0.205868,5.137464,0.015951,0.898557,0.000650,0.131438,0.002445
1,classwise,7.861056,0.028661,28.227198,2.517357,369.017846,1.453383,0.919932,0.000564,0.024803,0.001532
2,cluster_random,4.971846,0.069746,56.939389,0.576476,5.280942,0.180268,0.893438,0.001804,0.130332,0.004623

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.255101,0.016353,38.674388,0.190910,1.916781,0.009821,0.899289,0.000494,0.0824,0.001877
1,classwise,3.460003,0.022414,17.431880,0.749659,4.995291,0.077336,0.908189,0.000274,0.0142,0.001239
2,cluster_random,3.074562,0.030111,17.795730,0.532008,2.690719,0.076020,0.901178,0.001225,0.0156,0.001971

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.255101,0.016353,38.674388,0.190910,1.916781,0.009821,0.899289,0.000494,0.0824,0.001877
1,classwise,3.460003,0.022414,17.431880,0.749659,4.995291,0.077336,0.908189,0.000274,0.0142,0.001239
2,cluster_random,3.074562,0.030111,17.795730,0.532008,2.690719,0.076020,0.901178,0.001225,0.0156,0.001971

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.255101,0.016353,38.674388,0.190910,1.916781,0.009821,0.899289,0.000494,0.0824,0.001877
1,classwise,3.460003,0.022414,17.431880,0.749659,4.995291,0.077336,0.908189,0.000274,0.0142,0.001239
2,cluster_random,3.074562,0.030111,17.795730,0.532008,2.690719,0.076020,0.901178,0.001225,0.0156,0.001971

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.544371,0.003639,21.277486,0.067242,25.621846,0.111290,0.899360,0.000346,0.0215,0.000292
1,classwise,3.505090,0.018227,17.295112,1.267301,39.047805,0.234096,0.908719,0.000356,0.0153,0.000939
2,cluster_random,2.288863,0.042337,14.739135,0.722127,27.555525,0.381549,0.901242,0.000738,0.0056,0.000815

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.544371,0.003639,21.277486,0.067242,25.621846,0.111290,0.899360,0.000346,0.0215,0.000292
1,classwise,3.505090,0.018227,17.295112,1.267301,39.047805,0.234096,0.908719,0.000356,0.0153,0.000939
2,cluster_random,2.288863,0.042337,14.739135,0.722127,27.555525,0.381549,0.901242,0.000738,0.0056,0.000815

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.544371,0.003639,21.277486,0.067242,25.621846,0.111290,0.899360,0.000346,0.0215,0.000292
1,classwise,3.505090,0.018227,17.295112,1.267301,39.047805,0.234096,0.908719,0.000356,0.0153,0.000939
2,cluster_random,2.288863,0.042337,14.739135,0.722127,27.555525,0.381549,0.901242,0.000738,0.0056,0.000815

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.976121,0.003248,24.896790,0.105007,5.114308,0.008733,0.899238,0.000359,0.0274,0.000379
1,classwise,3.485797,0.023422,17.502511,1.254043,8.515900,0.281872,0.908591,0.000336,0.0149,0.000932
2,cluster_random,2.590800,0.038406,17.363941,1.680068,6.179076,0.420470,0.900075,0.000998,0.0090,0.001249

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.976121,0.003248,24.896790,0.105007,5.114308,0.008733,0.899238,0.000359,0.0274,0.000379
1,classwise,3.485797,0.023422,17.502511,1.254043,8.515900,0.281872,0.908591,0.000336,0.0149,0.000932
2,cluster_random,2.590800,0.038406,17.363941,1.680068,6.179076,0.420470,0.900075,0.000998,0.0090,0.001249

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.976121,0.003248,24.896790,0.105007,5.114308,0.008733,0.899238,0.000359,0.0274,0.000379
1,classwise,3.485797,0.023422,17.502511,1.254043,8.515900,0.281872,0.908591,0.000336,0.0149,0.000932
2,cluster_random,2.590800,0.038406,17.363941,1.680068,6.179076,0.420470,0.900075,0.000998,0.0090,0.001249

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.060791,0.029880,12.731093,0.246655,7.941668,0.092968,0.899800,0.001176,0.053,0.006008
1,classwise,3.771923,0.047471,13.670618,1.068629,11.754504,0.201934,0.908216,0.000978,0.014,0.002098
2,cluster_random,2.934429,0.055254,11.882068,0.572635,8.998524,0.196832,0.900464,0.001932,0.013,0.002025

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.060791,0.029880,12.731093,0.246655,7.941668,0.092968,0.899800,0.001176,0.053,0.006008
1,classwise,3.771923,0.047471,13.670618,1.068629,11.754504,0.201934,0.908216,0.000978,0.014,0.002098
2,cluster_random,2.934429,0.055254,11.882068,0.572635,8.998524,0.196832,0.900464,0.001932,0.013,0.002025

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.060791,0.029880,12.731093,0.246655,7.941668,0.092968,0.899800,0.001176,0.053,0.006008
1,classwise,3.771923,0.047471,13.670618,1.068629,11.754504,0.201934,0.908216,0.000978,0.014,0.002098
2,cluster_random,2.934429,0.055254,11.882068,0.572635,8.998524,0.196832,0.900464,0.001932,0.013,0.002025

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.778203,0.040482,13.673458,0.349646,11.069836,0.136890,0.899760,0.001096,0.036,0.003521
1,classwise,3.875294,0.047299,14.014907,1.295267,14.862152,0.247910,0.907316,0.001212,0.019,0.002214
2,cluster_random,3.165221,0.066722,12.088728,1.158269,11.697032,0.318651,0.900208,0.002311,0.020,0.006000

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.778203,0.040482,13.673458,0.349646,11.069836,0.136890,0.899760,0.001096,0.036,0.003521
1,classwise,3.875294,0.047299,14.014907,1.295267,14.862152,0.247910,0.907316,0.001212,0.019,0.002214
2,cluster_random,3.165221,0.066722,12.088728,1.158269,11.697032,0.318651,0.900208,0.002311,0.020,0.006000

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.778203,0.040482,13.673458,0.349646,11.069836,0.136890,0.899760,0.001096,0.036,0.003521
1,classwise,3.875294,0.047299,14.014907,1.295267,14.862152,0.247910,0.907316,0.001212,0.019,0.002214
2,cluster_random,3.165221,0.066722,12.088728,1.158269,11.697032,0.318651,0.900208,0.002311,0.020,0.006000

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.828124,0.045439,15.749210,0.497421,8.260052,0.115579,0.900780,0.001272,0.072,0.005060
1,classwise,3.700885,0.076279,12.367373,0.652037,12.906060,0.204599,0.909568,0.001209,0.021,0.003592
2,cluster_random,3.732289,0.091250,15.479732,1.072935,9.220552,0.181909,0.901048,0.001465,0.033,0.006332

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.828124,0.045439,15.749210,0.497421,8.260052,0.115579,0.900780,0.001272,0.072,0.005060
1,classwise,3.700885,0.076279,12.367373,0.652037,12.906060,0.204599,0.909568,0.001209,0.021,0.003592
2,cluster_random,3.732289,0.091250,15.479732,1.072935,9.220552,0.181909,0.901048,0.001465,0.033,0.006332

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.828124,0.045439,15.749210,0.497421,8.260052,0.115579,0.900780,0.001272,0.072,0.005060
1,classwise,3.700885,0.076279,12.367373,0.652037,12.906060,0.204599,0.909568,0.001209,0.021,0.003592
2,cluster_random,3.732289,0.091250,15.479732,1.072935,9.220552,0.181909,0.901048,0.001465,0.033,0.006332

../.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.558342,0.017570,22.226534,0.318183,6.893659,0.029264,0.900041,0.000527,0.066849,0.001826
1,classwise,3.537170,0.038829,14.568502,0.590090,10.008077,0.080628,0.909105,0.000513,0.014521,0.001600
2,cluster_random,3.028873,0.036021,13.049435,0.534491,7.847150,0.090765,0.903129,0.001235,0.010959,0.001733

../.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.558342,0.017570,22.226534,0.318183,6.893659,0.029264,0.900041,0.000527,0.066849,0.001826
1,classwise,3.537170,0.038829,14.568502,0.590090,10.008077,0.080628,0.909105,0.000513,0.014521,0.001600
2,cluster_random,3.028873,0.036021,13.049435,0.534491,7.847150,0.090765,0.903129,0.001235,0.010959,0.001733

../.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.558342,0.017570,22.226534,0.318183,6.893659,0.029264,0.900041,0.000527,0.066849,0.001826
1,classwise,3.537170,0.038829,14.568502,0.590090,10.008077,0.080628,0.909105,0.000513,0.014521,0.001600
2,cluster_random,3.028873,0.036021,13.049435,0.534491,7.847150,0.090765,0.903129,0.001235,0.010959,0.001733

../.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.260343,0.014592,18.300521,0.312991,10.819176,0.068107,0.900179,0.000795,0.027671,0.002464
1,classwise,3.563642,0.053961,15.997073,0.649524,14.268282,0.130363,0.908903,0.000509,0.017808,0.001609
2,cluster_random,2.581068,0.036344,11.269213,0.392801,11.750039,0.164256,0.903989,0.001590,0.004384,0.000965

../.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.260343,0.014592,18.300521,0.312991,10.819176,0.068107,0.900179,0.000795,0.027671,0.002464
1,classwise,3.563642,0.053961,15.997073,0.649524,14.268282,0.130363,0.908903,0.000509,0.017808,0.001609
2,cluster_random,2.581068,0.036344,11.269213,0.392801,11.750039,0.164256,0.903989,0.001590,0.004384,0.000965

../.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.260343,0.014592,18.300521,0.312991,10.819176,0.068107,0.900179,0.000795,0.027671,0.002464
1,classwise,3.563642,0.053961,15.997073,0.649524,14.268282,0.130363,0.908903,0.000509,0.017808,0.001609
2,cluster_random,2.581068,0.036344,11.269213,0.392801,11.750039,0.164256,0.903989,0.001590,0.004384,0.000965

../.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.866558,0.005477,20.374779,0.311264,7.948824,0.030618,0.900205,0.000693,0.041096,0.001501
1,classwise,3.534761,0.050259,16.265045,0.759067,11.208080,0.098817,0.909033,0.000449,0.016438,0.001644
2,cluster_random,2.900908,0.051154,11.489538,0.245529,8.914224,0.072875,0.904252,0.001039,0.005205,0.001058

../.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.866558,0.005477,20.374779,0.311264,7.948824,0.030618,0.900205,0.000693,0.041096,0.001501
1,classwise,3.534761,0.050259,16.265045,0.759067,11.208080,0.098817,0.909033,0.000449,0.016438,0.001644
2,cluster_random,2.900908,0.051154,11.489538,0.245529,8.914224,0.072875,0.904252,0.001039,0.005205,0.001058

../.cache/paper/varying_n/places365/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.866558,0.005477,20.374779,0.311264,7.948824,0.030618,0.900205,0.000693,0.041096,0.001501
1,classwise,3.534761,0.050259,16.265045,0.759067,11.208080,0.098817,0.909033,0.000449,0.016438,0.001644
2,cluster_random,2.900908,0.051154,11.489538,0.245529,8.914224,0.072875,0.904252,0.001039,0.005205,0.001058

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.986675,0.051262,46.357924,0.486381,3.158323,0.022356,0.899586,0.000714,0.200000,0.003081
1,classwise,5.798028,0.025292,28.096414,1.716999,148.658675,2.213236,0.909147,0.000532,0.033807,0.002203
2,cluster_random,5.668229,0.053423,45.684746,0.697744,3.732233,0.039540,0.898224,0.001004,0.139968,0.003382

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.986675,0.051262,46.357924,0.486381,3.158323,0.022356,0.899586,0.000714,0.200000,0.003081
1,classwise,5.798028,0.025292,28.096414,1.716999,148.658675,2.213236,0.909147,0.000532,0.033807,0.002203
2,cluster_random,5.668229,0.053423,45.684746,0.697744,3.732233,0.039540,0.898224,0.001004,0.139968,0.003382

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.986675,0.051262,46.357924,0.486381,3.158323,0.022356,0.899586,0.000714,0.200000,0.003081
1,classwise,5.798028,0.025292,28.096414,1.716999,148.658675,2.213236,0.909147,0.000532,0.033807,0.002203
2,cluster_random,5.668229,0.053423,45.684746,0.697744,3.732233,0.039540,0.898224,0.001004,0.139968,0.003382

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.217385,0.033882,59.282819,0.303284,8.323356,0.039037,0.899263,0.000624,0.097630,0.001577
1,classwise,5.830354,0.036480,32.051037,2.055952,153.924988,2.148021,0.908995,0.000702,0.033965,0.002530
2,cluster_random,3.875509,0.058155,59.243995,0.323587,8.627179,0.095196,0.897478,0.001182,0.075039,0.002450

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.217385,0.033882,59.282819,0.303284,8.323356,0.039037,0.899263,0.000624,0.097630,0.001577
1,classwise,5.830354,0.036480,32.051037,2.055952,153.924988,2.148021,0.908995,0.000702,0.033965,0.002530
2,cluster_random,3.875509,0.058155,59.243995,0.323587,8.627179,0.095196,0.897478,0.001182,0.075039,0.002450

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.217385,0.033882,59.282819,0.303284,8.323356,0.039037,0.899263,0.000624,0.097630,0.001577
1,classwise,5.830354,0.036480,32.051037,2.055952,153.924988,2.148021,0.908995,0.000702,0.033965,0.002530
2,cluster_random,3.875509,0.058155,59.243995,0.323587,8.627179,0.095196,0.897478,0.001182,0.075039,0.002450

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.977259,0.019893,56.643278,0.188147,5.142445,0.012277,0.898752,0.000506,0.132070,0.002050
1,classwise,5.828655,0.035067,31.601557,2.169927,155.059749,2.306336,0.908950,0.000553,0.033491,0.002243
2,cluster_random,4.531361,0.055639,56.385174,0.500161,5.541364,0.186116,0.896971,0.001236,0.100158,0.003625

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.977259,0.019893,56.643278,0.188147,5.142445,0.012277,0.898752,0.000506,0.132070,0.002050
1,classwise,5.828655,0.035067,31.601557,2.169927,155.059749,2.306336,0.908950,0.000553,0.033491,0.002243
2,cluster_random,4.531361,0.055639,56.385174,0.500161,5.541364,0.186116,0.896971,0.001236,0.100158,0.003625

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.977259,0.019893,56.643278,0.188147,5.142445,0.012277,0.898752,0.000506,0.132070,0.002050
1,classwise,5.828655,0.035067,31.601557,2.169927,155.059749,2.306336,0.908950,0.000553,0.033491,0.002243
2,cluster_random,4.531361,0.055639,56.385174,0.500161,5.541364,0.186116,0.896971,0.001236,0.100158,0.003625

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.249960,0.015928,38.509857,0.159223,1.920380,0.009199,0.899464,0.000475,0.0825,0.001961
1,classwise,2.814020,0.021727,13.692728,0.590741,4.100080,0.053897,0.905462,0.000330,0.0067,0.000872
2,cluster_random,2.806977,0.021005,13.982908,0.666886,2.749531,0.042868,0.901507,0.001041,0.0078,0.001121

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.249960,0.015928,38.509857,0.159223,1.920380,0.009199,0.899464,0.000475,0.0825,0.001961
1,classwise,2.814020,0.021727,13.692728,0.590741,4.100080,0.053897,0.905462,0.000330,0.0067,0.000872
2,cluster_random,2.806977,0.021005,13.982908,0.666886,2.749531,0.042868,0.901507,0.001041,0.0078,0.001121

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,5.249960,0.015928,38.509857,0.159223,1.920380,0.009199,0.899464,0.000475,0.0825,0.001961
1,classwise,2.814020,0.021727,13.692728,0.590741,4.100080,0.053897,0.905462,0.000330,0.0067,0.000872
2,cluster_random,2.806977,0.021005,13.982908,0.666886,2.749531,0.042868,0.901507,0.001041,0.0078,0.001121

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.546340,0.004100,21.182949,0.132455,25.630511,0.119060,0.899385,0.000377,0.0218,0.000276
1,classwise,2.859170,0.016090,14.301729,0.815958,34.428853,0.227908,0.905584,0.000344,0.0060,0.000762
2,cluster_random,2.182031,0.047692,13.184935,0.344602,27.113701,0.338869,0.899503,0.000946,0.0037,0.000530

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.546340,0.004100,21.182949,0.132455,25.630511,0.119060,0.899385,0.000377,0.0218,0.000276
1,classwise,2.859170,0.016090,14.301729,0.815958,34.428853,0.227908,0.905584,0.000344,0.0060,0.000762
2,cluster_random,2.182031,0.047692,13.184935,0.344602,27.113701,0.338869,0.899503,0.000946,0.0037,0.000530

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.546340,0.004100,21.182949,0.132455,25.630511,0.119060,0.899385,0.000377,0.0218,0.000276
1,classwise,2.859170,0.016090,14.301729,0.815958,34.428853,0.227908,0.905584,0.000344,0.0060,0.000762
2,cluster_random,2.182031,0.047692,13.184935,0.344602,27.113701,0.338869,0.899503,0.000946,0.0037,0.000530

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.977507,0.002048,24.811669,0.076847,5.114930,0.007694,0.899261,0.000321,0.0280,0.000400
1,classwise,2.842394,0.013009,15.048875,0.778591,7.148779,0.103050,0.905675,0.000300,0.0061,0.000943
2,cluster_random,2.374467,0.050119,14.657850,0.903216,7.089676,0.461088,0.900866,0.001014,0.0039,0.000591

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.977507,0.002048,24.811669,0.076847,5.114930,0.007694,0.899261,0.000321,0.0280,0.000400
1,classwise,2.842394,0.013009,15.048875,0.778591,7.148779,0.103050,0.905675,0.000300,0.0061,0.000943
2,cluster_random,2.374467,0.050119,14.657850,0.903216,7.089676,0.461088,0.900866,0.001014,0.0039,0.000591

../.cache/paper/varying_n/imagenet/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,2.977507,0.002048,24.811669,0.076847,5.114930,0.007694,0.899261,0.000321,0.0280,0.000400
1,classwise,2.842394,0.013009,15.048875,0.778591,7.148779,0.103050,0.905675,0.000300,0.0061,0.000943
2,cluster_random,2.374467,0.050119,14.657850,0.903216,7.089676,0.461088,0.900866,0.001014,0.0039,0.000591

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.112518,0.031261,13.208247,0.387584,7.958849,0.086790,0.900080,0.001277,0.052,0.006293
1,classwise,3.243329,0.080288,12.026896,1.274426,10.680258,0.133485,0.905858,0.001161,0.008,0.002757
2,cluster_random,2.745106,0.054037,10.252952,0.468674,9.246062,0.147502,0.902631,0.001114,0.007,0.002025

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.112518,0.031261,13.208247,0.387584,7.958849,0.086790,0.900080,0.001277,0.052,0.006293
1,classwise,3.243329,0.080288,12.026896,1.274426,10.680258,0.133485,0.905858,0.001161,0.008,0.002757
2,cluster_random,2.745106,0.054037,10.252952,0.468674,9.246062,0.147502,0.902631,0.001114,0.007,0.002025

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.112518,0.031261,13.208247,0.387584,7.958849,0.086790,0.900080,0.001277,0.052,0.006293
1,classwise,3.243329,0.080288,12.026896,1.274426,10.680258,0.133485,0.905858,0.001161,0.008,0.002757
2,cluster_random,2.745106,0.054037,10.252952,0.468674,9.246062,0.147502,0.902631,0.001114,0.007,0.002025

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.775848,0.041255,13.974948,0.506179,11.142298,0.115904,0.900351,0.001069,0.035,0.004528
1,classwise,3.227369,0.068573,11.741488,0.577090,13.543813,0.139402,0.905076,0.001179,0.012,0.002757
2,cluster_random,2.970761,0.082885,10.605678,0.511338,11.853653,0.263039,0.900982,0.001935,0.010,0.002828

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.775848,0.041255,13.974948,0.506179,11.142298,0.115904,0.900351,0.001069,0.035,0.004528
1,classwise,3.227369,0.068573,11.741488,0.577090,13.543813,0.139402,0.905076,0.001179,0.012,0.002757
2,cluster_random,2.970761,0.082885,10.605678,0.511338,11.853653,0.263039,0.900982,0.001935,0.010,0.002828

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.775848,0.041255,13.974948,0.506179,11.142298,0.115904,0.900351,0.001069,0.035,0.004528
1,classwise,3.227369,0.068573,11.741488,0.577090,13.543813,0.139402,0.905076,0.001179,0.012,0.002757
2,cluster_random,2.970761,0.082885,10.605678,0.511338,11.853653,0.263039,0.900982,0.001935,0.010,0.002828

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.856541,0.048770,16.030195,0.601333,8.167747,0.120218,0.900751,0.001285,0.073,0.006790
1,classwise,3.283866,0.049256,11.437608,0.650829,11.786213,0.100939,0.906653,0.001008,0.012,0.003406
2,cluster_random,3.379982,0.083709,12.034004,0.393510,9.632342,0.146488,0.902218,0.001172,0.020,0.004243

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.856541,0.048770,16.030195,0.601333,8.167747,0.120218,0.900751,0.001285,0.073,0.006790
1,classwise,3.283866,0.049256,11.437608,0.650829,11.786213,0.100939,0.906653,0.001008,0.012,0.003406
2,cluster_random,3.379982,0.083709,12.034004,0.393510,9.632342,0.146488,0.902218,0.001172,0.020,0.004243

../.cache/paper/varying_n/cifar-100/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.856541,0.048770,16.030195,0.601333,8.167747,0.120218,0.900751,0.001285,0.073,0.006790
1,classwise,3.283866,0.049256,11.437608,0.650829,11.786213,0.100939,0.906653,0.001008,0.012,0.003406
2,cluster_random,3.379982,0.083709,12.034004,0.393510,9.632342,0.146488,0.902218,0.001172,0.020,0.004243

../.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.560526,0.017672,22.233482,0.302304,6.911996,0.023916,0.900345,0.000449,0.065205,0.001010
1,classwise,2.975105,0.022185,12.334742,0.541222,9.255408,0.064104,0.906207,0.000572,0.006027,0.001082
2,cluster_random,2.804342,0.031968,11.834184,0.467306,7.963767,0.062975,0.904829,0.000944,0.005205,0.001473

../.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.560526,0.017672,22.233482,0.302304,6.911996,0.023916,0.900345,0.000449,0.065205,0.001010
1,classwise,2.975105,0.022185,12.334742,0.541222,9.255408,0.064104,0.906207,0.000572,0.006027,0.001082
2,cluster_random,2.804342,0.031968,11.834184,0.467306,7.963767,0.062975,0.904829,0.000944,0.005205,0.001473

../.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.560526,0.017672,22.233482,0.302304,6.911996,0.023916,0.900345,0.000449,0.065205,0.001010
1,classwise,2.975105,0.022185,12.334742,0.541222,9.255408,0.064104,0.906207,0.000572,0.006027,0.001082
2,cluster_random,2.804342,0.031968,11.834184,0.467306,7.963767,0.062975,0.904829,0.000944,0.005205,0.001473

../.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.274258,0.011877,18.289361,0.280069,10.804233,0.054477,0.899969,0.000668,0.030137,0.002050
1,classwise,3.036280,0.034534,13.953304,0.632113,13.313639,0.084890,0.905956,0.000472,0.009315,0.001297
2,cluster_random,2.571082,0.038097,11.406214,0.735215,11.715811,0.116417,0.902786,0.001258,0.003014,0.000984

../.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.274258,0.011877,18.289361,0.280069,10.804233,0.054477,0.899969,0.000668,0.030137,0.002050
1,classwise,3.036280,0.034534,13.953304,0.632113,13.313639,0.084890,0.905956,0.000472,0.009315,0.001297
2,cluster_random,2.571082,0.038097,11.406214,0.735215,11.715811,0.116417,0.902786,0.001258,0.003014,0.000984

../.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.274258,0.011877,18.289361,0.280069,10.804233,0.054477,0.899969,0.000668,0.030137,0.002050
1,classwise,3.036280,0.034534,13.953304,0.632113,13.313639,0.084890,0.905956,0.000472,0.009315,0.001297
2,cluster_random,2.571082,0.038097,11.406214,0.735215,11.715811,0.116417,0.902786,0.001258,0.003014,0.000984

../.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.879148,0.007117,20.222928,0.289862,7.958294,0.023571,0.900395,0.000556,0.041918,0.001735
1,classwise,3.007698,0.032855,13.960895,0.725053,10.356738,0.083408,0.906078,0.000357,0.009315,0.001237
2,cluster_random,2.775920,0.057447,11.920814,0.704038,8.994039,0.066785,0.904526,0.000918,0.004932,0.002043

../.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.879148,0.007117,20.222928,0.289862,7.958294,0.023571,0.900395,0.000556,0.041918,0.001735
1,classwise,3.007698,0.032855,13.960895,0.725053,10.356738,0.083408,0.906078,0.000357,0.009315,0.001237
2,cluster_random,2.775920,0.057447,11.920814,0.704038,8.994039,0.066785,0.904526,0.000918,0.004932,0.002043

../.cache/paper/varying_n/places365/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,3.879148,0.007117,20.222928,0.289862,7.958294,0.023571,0.900395,0.000556,0.041918,0.001735
1,classwise,3.007698,0.032855,13.960895,0.725053,10.356738,0.083408,0.906078,0.000357,0.009315,0.001237
2,cluster_random,2.775920,0.057447,11.920814,0.704038,8.994039,0.066785,0.904526,0.000918,0.004932,0.002043

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.972683,0.039343,46.215629,0.478789,3.162375,0.016725,0.899729,0.000538,0.198894,0.002029
1,classwise,4.847807,0.031768,30.939660,2.667140,55.267643,1.572883,0.905573,0.000591,0.036177,0.001253
2,cluster_random,5.269512,0.033618,45.711038,0.490918,3.815789,0.036412,0.899892,0.000567,0.127172,0.003308

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.972683,0.039343,46.215629,0.478789,3.162375,0.016725,0.899729,0.000538,0.198894,0.002029
1,classwise,4.847807,0.031768,30.939660,2.667140,55.267643,1.572883,0.905573,0.000591,0.036177,0.001253
2,cluster_random,5.269512,0.033618,45.711038,0.490918,3.815789,0.036412,0.899892,0.000567,0.127172,0.003308

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,6.972683,0.039343,46.215629,0.478789,3.162375,0.016725,0.899729,0.000538,0.198894,0.002029
1,classwise,4.847807,0.031768,30.939660,2.667140,55.267643,1.572883,0.905573,0.000591,0.036177,0.001253
2,cluster_random,5.269512,0.033618,45.711038,0.490918,3.815789,0.036412,0.899892,0.000567,0.127172,0.003308

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.210680,0.024724,59.217159,0.194292,8.327519,0.027481,0.899330,0.000440,0.098104,0.000960
1,classwise,4.765929,0.027824,31.896476,2.068599,60.578441,1.556788,0.905417,0.000485,0.033017,0.001708
2,cluster_random,3.570541,0.057425,58.965147,0.282955,8.699680,0.056278,0.898161,0.000813,0.062243,0.002720

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.210680,0.024724,59.217159,0.194292,8.327519,0.027481,0.899330,0.000440,0.098104,0.000960
1,classwise,4.765929,0.027824,31.896476,2.068599,60.578441,1.556788,0.905417,0.000485,0.033017,0.001708
2,cluster_random,3.570541,0.057425,58.965147,0.282955,8.699680,0.056278,0.898161,0.000813,0.062243,0.002720

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.210680,0.024724,59.217159,0.194292,8.327519,0.027481,0.899330,0.000440,0.098104,0.000960
1,classwise,4.765929,0.027824,31.896476,2.068599,60.578441,1.556788,0.905417,0.000485,0.033017,0.001708
2,cluster_random,3.570541,0.057425,58.965147,0.282955,8.699680,0.056278,0.898161,0.000813,0.062243,0.002720

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.962488,0.014267,56.630396,0.164319,5.150757,0.009313,0.899089,0.000387,0.131596,0.001612
1,classwise,4.825594,0.029151,30.878996,2.111035,62.826207,1.672555,0.905795,0.000521,0.033017,0.001966
2,cluster_random,4.136106,0.042801,56.115197,0.298581,5.510074,0.048898,0.898605,0.000718,0.081517,0.003569

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.962488,0.014267,56.630396,0.164319,5.150757,0.009313,0.899089,0.000387,0.131596,0.001612
1,classwise,4.825594,0.029151,30.878996,2.111035,62.826207,1.672555,0.905795,0.000521,0.033017,0.001966
2,cluster_random,4.136106,0.042801,56.115197,0.298581,5.510074,0.048898,0.898605,0.000718,0.081517,0.003569

../.cache/paper/varying_n/inaturalist/random_calset/n_totalcal=75/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se
0,standard,4.962488,0.014267,56.630396,0.164319,5.150757,0.009313,0.899089,0.000387,0.131596,0.001612
1,classwise,4.825594,0.029151,30.878996,2.111035,62.826207,1.672555,0.905795,0.000521,0.033017,0.001966
2,cluster_random,4.136106,0.042801,56.115197,0.298581,5.510074,0.048898,0.898605,0.000718,0.081517,0.003569

\begin{tabular}{lllcrcrcrcr}
\toprule
 &  &  & \multicolumn{2}{c}{$n_{	ext{avg}}=10$} & \multicolumn{2}{c}{$n_{	ext{avg}}=20$} & \multicolumn{2}{c}{$n_{	ext{avg}}=50$} & \multicolumn{2}{c}{$n_{	ext{avg}}=75$} \\
 &  &  & CovGap & AvgSize & CovGap & AvgSize & CovGap & AvgSize & CovGap & AvgSize \\
Dataset & Score func. & Method &  &  &  &  &  &  &  &  \\
\midrule
\multirow[t]{9}{*}{ImageNet} & \multirow[t]{3}{*}{$\softmax$} & $\standard$ & 5.2 (0.0) & 1.9 (0.0) & 5.2 (0.0) & 1.9 (0.0) & 5.3 (0.0) & 1.9 (0.0) & 5.2 (0.0) & 1.9 (0.0) \\
 &  & $\classwise$ & 7.7 (0.0) & 354.4 (2.0) & 5.4 (0.0) & 22.9 (0.9) & 3.5 (0.0) & 5.0 (0.1) & 2.8 (0.0) & 4.1 (0.1) \\
 &  & $\clustered$ & 4.8 (0.1) & 2.4 (0.1) & 3.8 (0.0) & 2.6 (0.0) & 3.1 (0.0) & 2.7 (0.1) & 2.8 (0.0) & 2.7 (0.0) \\
\cline{2-11}
 & \multirow[t]{3}{*}{$\APS$} & $\standard$ & 2.6 (0.0) & 25.9 (0.3) & 2.5 (0.0) & 25.7 (0.1) & 2.5 (0.0) & 25.6 (0.1) & 2.5 (0.0) & 25.6 (0.1) \\
 &  & $\classwise$ & 7.6 (0.0) & 394.2 (1.9) & 5.4 (0.0) & 76.5 (0.8) & 3.5 (0.0) & 39.0 (0.2) & 2.9 (0.0) & 34.4 (0.2) \\
 &  & $\clustered$ & 2.8 (0.1) & 27.7 (0.7) & 2.6 (0.1) & 26.3 (0.6) & 2.3 (0.0) & 27.6 (0.4) & 2.2 (0.0) & 27.1 (0.3) \\
\cline{2-11}
 & \multirow[t]{3}{*}{$\RAPS$} & $\standard$ & 3.0 (0.0) & 5.1 (0.0) & 3.0 (0.0) & 5.1 (0.0) & 3.0 (0.0) & 5.1 (0.0) & 3.0 (0.0) & 5.1 (0.0) \\
 &  & $\classwise$ & 7.6 (0.0) & 361.9 (1.9) & 5.4 (0.0) & 33.0 (1.0) & 3.5 (0.0) & 8.5 (0.3) & 2.8 (0.0) & 7.1 (0.1) \\
 &  & $\clustered$ & 3.2 (0.0) & 8.0 (0.9) & 2.9 (0.0) & 6.1 (0.4) & 2.6 (0.0) & 6.2 (0.4) & 2.4 (0.1) & 7.1 (0.5) \\
\cline{1-11} \cline{2-11}
\multirow[t]{9}{*}{\midrule
CIFAR-100} & \multirow[t]{3}{*}{$\softmax$} & $\standard$ & 4.0 (0.1) & 8.1 (0.2) & 4.0 (0.0) & 7.9 (0.2) & 4.1 (0.0) & 7.9 (0.1) & 4.1 (0.0) & 8.0 (0.1) \\
 &  & $\classwise$ & 7.6 (0.1) & 47.2 (0.6) & 5.6 (0.1) & 19.2 (0.5) & 3.8 (0.0) & 11.8 (0.2) & 3.2 (0.1) & 10.7 (0.1) \\
 &  & $\clustered$ & 4.1 (0.1) & 9.4 (0.4) & 3.7 (0.1) & 8.3 (0.3) & 2.9 (0.1) & 9.0 (0.2) & 2.7 (0.1) & 9.2 (0.1) \\
\cline{2-11}
 & \multirow[t]{3}{*}{$\APS$} & $\standard$ & 3.7 (0.1) & 11.3 (0.3) & 3.8 (0.0) & 10.8 (0.1) & 3.8 (0.0) & 11.1 (0.1) & 3.8 (0.0) & 11.1 (0.1) \\
 &  & $\classwise$ & 7.5 (0.1) & 49.3 (0.5) & 5.6 (0.1) & 22.5 (0.5) & 3.9 (0.0) & 14.9 (0.2) & 3.2 (0.1) & 13.5 (0.1) \\
 &  & $\clustered$ & 3.8 (0.1) & 12.1 (0.4) & 3.8 (0.1) & 11.0 (0.4) & 3.2 (0.1) & 11.7 (0.3) & 3.0 (0.1) & 11.9 (0.3) \\
\cline{2-11}
 & \multirow[t]{3}{*}{$\RAPS$} & $\standard$ & 4.7 (0.1) & 8.6 (0.3) & 4.8 (0.1) & 8.3 (0.2) & 4.8 (0.0) & 8.3 (0.1) & 4.9 (0.0) & 8.2 (0.1) \\
 &  & $\classwise$ & 7.6 (0.1) & 47.5 (0.7) & 5.6 (0.1) & 20.2 (0.6) & 3.7 (0.1) & 12.9 (0.2) & 3.3 (0.0) & 11.8 (0.1) \\
 &  & $\clustered$ & 4.8 (0.1) & 9.4 (0.4) & 4.5 (0.1) & 8.5 (0.3) & 3.7 (0.1) & 9.2 (0.2) & 3.4 (0.1) & 9.6 (0.1) \\
\cline{1-11} \cline{2-11}
\multirow[t]{9}{*}{\midrule
Places365} & \multirow[t]{3}{*}{$\softmax$} & $\standard$ & 4.5 (0.0) & 6.9 (0.1) & 4.5 (0.0) & 6.9 (0.0) & 4.6 (0.0) & 6.9 (0.0) & 4.6 (0.0) & 6.9 (0.0) \\
 &  & $\classwise$ & 7.6 (0.1) & 136.5 (1.7) & 5.4 (0.0) & 17.9 (0.2) & 3.5 (0.0) & 10.0 (0.1) & 3.0 (0.0) & 9.3 (0.1) \\
 &  & $\clustered$ & 4.5 (0.1) & 7.4 (0.3) & 3.7 (0.1) & 7.7 (0.2) & 3.0 (0.0) & 7.8 (0.1) & 2.8 (0.0) & 8.0 (0.1) \\
\cline{2-11}
 & \multirow[t]{3}{*}{$\APS$} & $\standard$ & 3.3 (0.0) & 10.9 (0.1) & 3.2 (0.0) & 10.9 (0.1) & 3.3 (0.0) & 10.8 (0.1) & 3.3 (0.0) & 10.8 (0.1) \\
 &  & $\classwise$ & 7.7 (0.0) & 140.5 (1.7) & 5.4 (0.1) & 23.4 (0.2) & 3.6 (0.1) & 14.3 (0.1) & 3.0 (0.0) & 13.3 (0.1) \\
 &  & $\clustered$ & 3.4 (0.1) & 11.4 (0.4) & 3.0 (0.1) & 11.3 (0.3) & 2.6 (0.0) & 11.8 (0.2) & 2.6 (0.0) & 11.7 (0.1) \\
\cline{2-11}
 & \multirow[t]{3}{*}{$\RAPS$} & $\standard$ & 3.9 (0.0) & 8.0 (0.1) & 3.9 (0.0) & 8.0 (0.0) & 3.9 (0.0) & 7.9 (0.0) & 3.9 (0.0) & 8.0 (0.0) \\
 &  & $\classwise$ & 7.6 (0.0) & 138.9 (1.7) & 5.4 (0.0) & 20.9 (0.3) & 3.5 (0.1) & 11.2 (0.1) & 3.0 (0.0) & 10.4 (0.1) \\
 &  & $\clustered$ & 4.0 (0.1) & 8.3 (0.2) & 3.4 (0.0) & 8.5 (0.2) & 2.9 (0.1) & 8.9 (0.1) & 2.8 (0.1) & 9.0 (0.1) \\
\cline{1-11} \cline{2-11}
\multirow[t]{9}{*}{\midrule
iNaturalist} & \multirow[t]{3}{*}{$\softmax$} & $\standard$ & 7.0 (0.1) & 3.1 (0.0) & 7.0 (0.1) & 3.1 (0.0) & 7.0 (0.1) & 3.2 (0.0) & 7.0 (0.0) & 3.2 (0.0) \\
 &  & $\classwise$ & 8.7 (0.0) & 469.4 (1.8) & 7.8 (0.0) & 364.0 (1.4) & 5.8 (0.0) & 148.7 (2.2) & 4.8 (0.0) & 55.3 (1.6) \\
 &  & $\clustered$ & 6.9 (0.1) & 3.1 (0.1) & 6.5 (0.1) & 3.4 (0.0) & 5.7 (0.1) & 3.7 (0.0) & 5.3 (0.0) & 3.8 (0.0) \\
\cline{2-11}
 & \multirow[t]{3}{*}{$\APS$} & $\standard$ & 4.2 (0.1) & 8.3 (0.1) & 4.2 (0.0) & 8.3 (0.0) & 4.2 (0.0) & 8.3 (0.0) & 4.2 (0.0) & 8.3 (0.0) \\
 &  & $\classwise$ & 8.7 (0.0) & 472.8 (1.8) & 7.8 (0.0) & 368.2 (1.4) & 5.8 (0.0) & 153.9 (2.1) & 4.8 (0.0) & 60.6 (1.6) \\
 &  & $\clustered$ & 4.4 (0.1) & 8.1 (0.1) & 4.3 (0.1) & 8.1 (0.1) & 3.9 (0.1) & 8.6 (0.1) & 3.6 (0.1) & 8.7 (0.1) \\
\cline{2-11}
 & \multirow[t]{3}{*}{$\RAPS$} & $\standard$ & 5.0 (0.0) & 5.1 (0.0) & 5.0 (0.0) & 5.1 (0.0) & 5.0 (0.0) & 5.1 (0.0) & 5.0 (0.0) & 5.2 (0.0) \\
 &  & $\classwise$ & 8.7 (0.0) & 473.6 (1.9) & 7.9 (0.0) & 369.0 (1.5) & 5.8 (0.0) & 155.1 (2.3) & 4.8 (0.0) & 62.8 (1.7) \\
 &  & $\clustered$ & 5.1 (0.1) & 5.1 (0.1) & 5.0 (0.1) & 5.3 (0.2) & 4.5 (0.1) & 5.5 (0.2) & 4.1 (0.0) & 5.5 (0.0) \\
\cline{1-11} \cline{2-11}
\bottomrule
\end{tabular}

## Additonal tables
Unused in paper

In [4]:
# # Investigate marginal coverage

# n_totalcals = {10: '$n_{\text{avg}}=10$', 
#                20: '$n_{\text{avg}}=20$', 
#                30: '$n_{\text{avg}}=30$', 
#                40: '$n_{\text{avg}}=40$', 
#                50: '$n_{\text{avg}}=50$', 
#                75: '$n_{\text{avg}}=75$',
#                100: '$n_{\text{avg}}=100$'}

# methods = {'standard': '$\standard$', 
#             'classwise': '$\classwise$',
#             'exact_coverage_classwise': 'ExactCov-$\classwise$',
#             'cluster_random': '$\clustered$',
#             'exact_coverage_cluster': 'ExactCov-$\clustered$'} 

# horizontal_dict = {}
# for n_totalcal, n_name in n_totalcals.items():
#     vertical_list = []
#     for dataset, save_folder in datasets.items():
#         for score, score_name in score_functions.items():
#             for method, method_name in methods.items(): 

#                 folder = f'{save_folder}/{calibration_sampling}_calset/n_totalcal={n_totalcal}/score={score}/'
#                 print(folder)
#                 df = average_results_across_seeds(folder, print_results=False, display_table=False, methods=methods.keys()) # df = results DataFrame
#                 s = pd.Series({'Dataset': dataset, 'Score func.': score_name, 'Method': method_name, 
#                               'MargCov': f"{df[df['method'] == method]['marginal_cov_mean'].values[0]*100:.1f}" 
#                                                    f" ({df[df['method'] == method]['marginal_cov_se'].values[0]*100:.1f})"})
#                 vertical_list.append(pd.DataFrame(s).transpose())                                        

#     df = pd.concat(vertical_list, ignore_index=True)                                                     
#     df = df.set_index(['Dataset', 'Score func.', 'Method'])
#     horizontal_dict[n_name] = df

# df = pd.concat(horizontal_dict, axis=1)
# df_str = df.to_latex(multicolumn_format='c', # To center multilevel column headers
#     escape=False # So that backslashes are printed as `\' rather than '\textbackslash'
#                  )
# # Post-process
# # df_str = df_str.replace('lllllllll', 'lllcrccrc')
# # df_str = df_str.replace('$n_{\\text{avg}}=75$ \\',
# #                '$n_{\\text{avg}}=75$ \\\\ \cmidrule(lr){4}\cmidrule(lr){5} \cmidrule(lr){6}\\')
# df_str = df_str.replace('CIFAR-100', '\midrule\nCIFAR-100')
# df_str = df_str.replace('Places365', '\midrule\nPlaces365')
# df_str = df_str.replace('iNaturalist', '\midrule\niNaturalist')
# print(df_str)

In [5]:
# df

Additionally include results for randomized methods

In [6]:
# methods = {'standard': '$\standard$', 
#             'exact_coverage_standard': 'Randomized $\standard$',
#             'classwise': '$\classwise$',
#             'exact_coverage_classwise': 'Randomized $\classwise$',
#             'cluster_random': '$\clustered$',
#             'exact_coverage_cluster': 'Randomized $\clustered$'}

In [7]:
# n_totalcals = {10: '$n_{\text{avg}}=10$', 20: '$n_{\text{avg}}=20$', 
#                50: '$n_{\text{avg}}=50$', 75: '$n_{\text{avg}}=75$'}

# datasets = {'ImageNet': '../.cache/paper/varying_n/imagenet',
#             'CIFAR-100': '../.cache/paper/varying_n/cifar-100',
#             'Places365': '../.cache/paper/varying_n/places365',
#             'iNaturalist': '../.cache/paper/varying_n/inaturalist'}

# horizontal_dict = {}
# for n_totalcal, n_name in n_totalcals.items():
#     vertical_list = []
#     for dataset, save_folder in datasets.items():
#         for score, score_name in score_functions.items():
#             for method, method_name in methods.items(): 

#                 folder = f'{save_folder}/{calibration_sampling}_calset/n_totalcal={n_totalcal}/score={score}/'
#                 print(folder)
#                 df = average_results_across_seeds(folder, print_results=False, display_table=False,methods=methods.keys()) # df = results DataFrame
#                 s = pd.Series({'Dataset': dataset, 'Score func.': score_name, 'Method': method_name, 
#                                'CovGap': f"{df[df['method'] == method]['class_cov_gap_mean'].values[0]:.1f}" 
#                                        f" ({df[df['method'] == method]['class_cov_gap_se'].values[0]:.1f})",
#                                'AvgSize': f"{df[df['method'] == method]['avg_set_size_mean'].values[0]:.1f}" 
#                                                f" ({df[df['method'] == method]['avg_set_size_se'].values[0]:.1f})"})
# #                                'MargCov': f"{df[df['method'] == method]['marginal_cov_mean'].values[0]*100:.1f}" 
# #                                                    f" ({df[df['method'] == method]['marginal_cov_se'].values[0]*100:.1f})"})
#                 vertical_list.append(pd.DataFrame(s).transpose())                                        

#     df = pd.concat(vertical_list, ignore_index=True)                                                     
#     df = df.set_index(['Dataset', 'Score func.', 'Method'])
#     horizontal_dict[n_name] = df

# df = pd.concat(horizontal_dict, axis=1)
# df_str = df.to_latex(multicolumn_format='c', # To center multilevel column headers
#     escape=False) # So that backslashes are printed as `\' rather than '\textbackslash'
                 
# # Post-process
# df_str = df_str.replace('lllllllllll', 'lllcrcrcrcr')
# df_str = df_str.replace('\\multicolumn{2}{c}{$n_{\\text{avg}}=75$} \\\\',
#                '\\multicolumn{2}{c}{$n_{\\text{avg}}=75$} \\\\ \cmidrule(lr){4-5}\cmidrule(lr){6-7} \cmidrule(lr){8-9} \cmidrule(lr){10-11}\\')
# df_str = df_str.replace('CIFAR-100', '\midrule\nCIFAR-100')
# df_str = df_str.replace('Places365', '\midrule\nPlaces365')
# df_str = df_str.replace('iNaturalist', '\midrule\niNaturalist')
# # Add horizontal lines between methods
# df_str = df_str.replace('& $\APS$', '\cline{3-11} & $\APS$')
# df_str = df_str.replace('& $\RAPS$', '\cline{3-11} & $\RAPS$')
# print(df_str)

In [8]:
# pd.set_option('display.max_rows', None) # Show all rows
# df